export default {
    "5A": {
       "Input": "",
       "Damage": "180",
       "Hit Type": "Mid",
       "Active On": "5",
       "Active For": "2",
       "Recovery": "12",
       "Overall": "18",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "5B": {
       "Input": "",
       "Damage": "380",
       "Hit Type": "Mid",
       "Active On": "6",
       "Active For": "4",
       "Recovery": "14",
       "Overall": "23",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "5C": {
       "Input": "",
       "Damage": "695",
       "Hit Type": "Mid / Mid",
       "Active On": "12",
       "Active For": "6",
       "Recovery": "21",
       "Overall": "38",
       "Frame Advantage": "-7",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "2A": {
       "Input": "",
       "Damage": "160",
       "Hit Type": "Mid",
       "Active On": "5",
       "Active For": "2",
       "Recovery": "13",
       "Overall": "19",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attribute": "Foot",
       "Notes": ""
    },
    "2B": {
       "Input": "",
       "Damage": "390",
       "Hit Type": "Low",
       "Active On": "8",
       "Active For": "2",
       "Recovery": "20",
       "Overall": "29",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attribute": "Foot",
       "Notes": ""
    },
    "2C": {
       "Input": "",
       "Damage": "600",
       "Hit Type": "Low",
       "Active On": "12",
       "Active For": "6",
       "Recovery": "24",
       "Overall": "41",
       "Frame Advantage": "-12",
       "Invincibility": "",
       "Attribute": "Foot",
       "Notes": ""
    },
    "j.A": {
       "Input": "",
       "Damage": "130",
       "Hit Type": "Overhead",
       "Active On": "7",
       "Active For": "2",
       "Recovery": "12",
       "Overall": "20",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.B": {
       "Input": "",
       "Damage": "380",
       "Hit Type": "Overhead",
       "Active On": "8",
       "Active For": "2",
       "Recovery": "18",
       "Overall": "27",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j,C": {
       "Input": "",
       "Damage": "560",
       "Hit Type": "Overhead",
       "Active On": "12",
       "Active For": "4",
       "Recovery": "17",
       "Overall": "32",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "66B": {
       "Input": "",
       "Damage": "810",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "3",
       "Recovery": "13",
       "Overall": "24",
       "Frame Advantage": "-1",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "66C": {
       "Input": "",
       "Damage": "892",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "4",
       "Recovery": "20",
       "Overall": "35",
       "Frame Advantage": "-4",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "66AB": {
       "Input": "",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "22",
       "Frame Advantage": "-",
       "Invincibility": "6～9 Head・Projectile/10～15 Strike/16～19 Projectile",
       "Attribute": "",
       "Notes": "コマンドを同時押しで成立させた場合でも、発生前にダッシュBを1F経由する"
    },
    "6B": {
       "Input": "",
       "Damage": "420",
       "Hit Type": "Mid",
       "Active On": "7",
       "Active For": "2",
       "Recovery": "18",
       "Overall": "26",
       "Frame Advantage": "-4",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "6C": {
       "Input": "→+C",
       "Damage": "500",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "6",
       "Recovery": "18",
       "Overall": "35",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "6CC": {
       "Input": "→+C",
       "Damage": "400",
       "Hit Type": "Mid",
       "Active On": "13",
       "Active For": "4",
       "Recovery": "22",
       "Overall": "38",
       "Frame Advantage": "-10",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "6CCC": {
       "Input": "→+C",
       "Damage": "600",
       "Hit Type": "Mid",
       "Active On": "21",
       "Active For": "5",
       "Recovery": "25",
       "Overall": "50",
       "Frame Advantage": "-12",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "j.6B": {
       "Input": "",
       "Damage": "370",
       "Hit Type": "Overhead",
       "Active On": "9",
       "Active For": "4",
       "Recovery": "15",
       "Overall": "27",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": ""
    },
    "j.6[B]": {
       "Input": "",
       "Damage": "450",
       "Hit Type": "Overhead",
       "Active On": "16",
       "Active For": "4",
       "Recovery": "15",
       "Overall": "34",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": ""
    },
    "j.2B": {
       "Input": "",
       "Damage": "310",
       "Hit Type": "Mid",
       "Active On": "13",
       "Active For": "Until landing",
       "Recovery": "11 upon landing",
       "Overall": "27",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "硬直差と全体は最低空時のもの"
    },
    "2AA": {
       "Input": "",
       "Damage": "160",
       "Hit Type": "Low",
       "Active On": "5",
       "Active For": "2",
       "Recovery": "13",
       "Overall": "19",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attribute": "Foot",
       "Notes": ""
    },
    "5CC": {
       "Input": "",
       "Damage": "410",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "3",
       "Recovery": "20",
       "Overall": "32",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "5C[C]": {
       "Input": "",
       "Damage": "800",
       "Hit Type": "Overhead",
       "Active On": "27",
       "Active For": "3",
       "Recovery": "24",
       "Overall": "53",
       "Frame Advantage": "-9",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "FF": {
       "Input": "B+C",
       "Damage": "0",
       "Hit Type": "",
       "Active On": "0",
       "Active For": "",
       "Recovery": "0",
       "Overall": "37",
       "Frame Advantage": "",
       "Invincibility": "1～14 Strike / 15～30 Head・Projectile",
       "Attribute": "",
       "Notes": ""
    },
    "FF (Vorpal)": {
       "Input": "B+C",
       "Damage": "0",
       "Hit Type": "",
       "Active On": "0",
       "Active For": "",
       "Recovery": "0",
       "Overall": "35",
       "Frame Advantage": "",
       "Invincibility": "1～14 Strike / 15～29 Head・Projectile",
       "Attribute": "",
       "Notes": ""
    },
    "FFX": {
       "Input": "AorBorC",
       "Damage": "1758",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "2",
       "Recovery": "20",
       "Overall": "31",
       "Frame Advantage": "-6",
       "Invincibility": "1～11Head",
       "Attribute": "",
       "Notes": ""
    },
    "Throw": {
       "Input": "A+D",
       "Damage": "1635",
       "Hit Type": "Throw",
       "Active On": "4",
       "Active For": "1",
       "Recovery": "22",
       "Overall": "26",
       "Frame Advantage": "",
       "Invincibility": "",
       "Attribute": "Throw",
       "Notes": "投げ無敵時金投げ"
    },
    "236A": {
       "Input": "↓↘→+A",
       "Damage": "810",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "21",
       "Active For": "10",
       "Recovery": "19",
       "Overall": "49",
       "Frame Advantage": "-7",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": ""
    },
    "236B": {
       "Input": "↓↘→+B",
       "Damage": "810",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "12",
       "Active For": "10",
       "Recovery": "24",
       "Overall": "45",
       "Frame Advantage": "-12",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": ""
    },
    "236[B]": {
       "Input": "↓↘→+B",
       "Damage": "954",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "25",
       "Active For": "5(2)4",
       "Recovery": "22",
       "Overall": "57",
       "Frame Advantage": "-4",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": ""
    },
    "236C": {
       "Input": "↓↘→+C",
       "Damage": "1734",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "15",
       "Recovery": "5",
       "Overall": "34",
       "Frame Advantage": "+25",
       "Invincibility": "1～3 Throw",
       "Attribute": "",
       "Notes": "硬直差は密着でガードさせた場合のもの"
    },
    "236X66": {
       "Input": "→→",
       "Damage": "0",
       "Hit Type": "",
       "Active On": "0",
       "Active For": "",
       "Recovery": "0",
       "Overall": "26",
       "Frame Advantage": "",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "623A": {
       "Input": "→↓↘+A",
       "Damage": "1369",
       "Hit Type": "Mid",
       "Active On": "5",
       "Active For": "2(2)4",
       "Recovery": "29",
       "Overall": "41",
       "Frame Advantage": "-15",
       "Invincibility": "5～12 Dive / 8～12 Head",
       "Attribute": "",
       "Notes": ""
    },
    "623B": {
       "Input": "→↓↘+B",
       "Damage": "1568",
       "Hit Type": "Mid",
       "Active On": "6",
       "Active For": "11(13)1",
       "Recovery": "38",
       "Overall": "68",
       "Frame Advantage": "-36",
       "Invincibility": "1～14 All / 15～16 Foot・Head",
       "Attribute": "",
       "Notes": ""
    },
    "623C": {
       "Input": "→↓↘+C",
       "Damage": "1826",
       "Hit Type": "Mid",
       "Active On": "5",
       "Active For": "9(12)5(17)9",
       "Recovery": "49",
       "Overall": "105",
       "Frame Advantage": "-76",
       "Invincibility": "1～6 Head / 7～13 Strike",
       "Attribute": "",
       "Notes": ""
    },
    "214A": {
       "Input": "↓↙←+A",
       "Damage": "836",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "1(9)4",
       "Recovery": "12",
       "Overall": "34",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "214B": {
       "Input": "↓↙←+B",
       "Damage": "836",
       "Hit Type": "Mid",
       "Active On": "11",
       "Active For": "1(11)3",
       "Recovery": "16",
       "Overall": "41",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "214C": {
       "Input": "↓↙←+C",
       "Damage": "2033",
       "Hit Type": "Mid",
       "Active On": "8",
       "Active For": "4(12)3(8)2(8)2(7)2(4)3(4)5(12)1",
       "Recovery": "19",
       "Overall": "103",
       "Frame Advantage": "+3",
       "Invincibility": "1～3 Throw",
       "Attribute": "",
       "Notes": ""
    },
    "214XA": {
       "Input": "A",
       "Damage": "640",
       "Hit Type": "Mid",
       "Active On": "8",
       "Active For": "1(11)3",
       "Recovery": "16",
       "Overall": "38",
       "Frame Advantage": "-1",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "214XB": {
       "Input": "B",
       "Damage": "1090",
       "Hit Type": "Mid",
       "Active On": "8",
       "Active For": "2(9)3(10)4",
       "Recovery": "17",
       "Overall": "52",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "214XC": {
       "Input": "C",
       "Damage": "1410",
       "Hit Type": "Mid",
       "Active On": "8",
       "Active For": "2(9)3(10)4(10)2",
       "Recovery": "23",
       "Overall": "70",
       "Frame Advantage": "-9",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "214XX66": {
       "Input": "→→",
       "Damage": "0",
       "Hit Type": "",
       "Active On": "0",
       "Active For": "",
       "Recovery": "0",
       "Overall": "26",
       "Frame Advantage": "",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "63214A": {
       "Input": "→↘↓↙←+A",
       "Damage": "1122",
       "Hit Type": "Mid",
       "Active On": "23",
       "Active For": "3",
       "Recovery": "23",
       "Overall": "48",
       "Frame Advantage": "-6",
       "Invincibility": "10～25 Foot",
       "Attribute": "",
       "Notes": ""
    },
    "63214B": {
       "Input": "→↘↓↙←+B",
       "Damage": "1253",
       "Hit Type": "Overhead",
       "Active On": "26",
       "Active For": "3",
       "Recovery": "19",
       "Overall": "47",
       "Frame Advantage": "-3",
       "Invincibility": "11～28 Foot",
       "Attribute": "",
       "Notes": ""
    },
    "63214[B]": {
       "Input": "→↘↓↙←+B",
       "Damage": "240・420",
       "Hit Type": "Mid / Low",
       "Active On": "20",
       "Active For": "7(7)4",
       "Recovery": "17",
       "Overall": "54",
       "Frame Advantage": "-9",
       "Invincibility": "11～16 Foot",
       "Attribute": "",
       "Notes": "初段は連続技中のみヒットする。ダメージは初段・二段目それぞれのもの。"
    },
    "63214C": {
       "Input": "→↘↓↙←+C",
       "Damage": "2010",
       "Hit Type": "Mid",
       "Active On": "23",
       "Active For": "4",
       "Recovery": "20",
       "Overall": "46",
       "Frame Advantage": "-5",
       "Invincibility": "1～13 All /14～26 Foot・Projectile",
       "Attribute": "",
       "Notes": ""
    },
    "j.236A": {
       "Input": "(In air)↓↘→+A",
       "Damage": "810",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "21",
       "Active For": "10",
       "Recovery": "8 upon landing",
       "Overall": "34",
       "Frame Advantage": "+6",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "硬直差は密着でジャンプの昇りから最速で出した場合のもの"
    },
    "j.236B": {
       "Input": "(In air)↓↘→+B",
       "Damage": "810",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "18",
       "Active For": "10",
       "Recovery": "8 upon landing",
       "Overall": "34",
       "Frame Advantage": "+3",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "硬直差は密着でジャンプの昇りから最速で出した場合のもの"
    },
    "j.236C": {
       "Input": "(In air)↓↘→+C",
       "Damage": "1734",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "15",
       "Recovery": "5 upon landing",
       "Overall": "26",
       "Frame Advantage": "+27",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "硬直差は密着でジャンプの昇りから最速で出した場合のもの"
    },
    "IW": {
       "Input": "←↙↓↘→+D",
       "Damage": "3271",
       "Hit Type": "Mid",
       "Active On": "13",
       "Active For": "14(8)8(8)8(8)19(17)6(9)80",
       "Recovery": "0",
       "Overall": "167",
       "Frame Advantage": "+20",
       "Invincibility": "1～26 All / 27～31 Throw",
       "Attribute": "",
       "Notes": "tl note: the active frames on this are a clusterfuck jesus christ"
    },
    "IWEXS": {
       "Input": "A+B+C+D",
       "Damage": "3810",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "6",
       "Recovery": "47",
       "Overall": "67",
       "Frame Advantage": "-25",
       "Invincibility": "1～26 All",
       "Attribute": "",
       "Notes": ""
    }
 }