export default {
    "5A": {
       "Input": "",
       "Damage": "180",
       "Hit Type": "Mid",
       "Active On": "6",
       "Active For": "2",
       "Recovery": "13",
       "Overall": "20",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "5B": {
       "Input": "",
       "Damage": "450",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "4",
       "Recovery": "21",
       "Overall": "34",
       "Frame Advantage": "-9",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "5C": {
       "Input": "",
       "Damage": "690",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "3",
       "Recovery": "23",
       "Overall": "37",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "2A": {
       "Input": "",
       "Damage": "150",
       "Hit Type": "Mid",
       "Active On": "6",
       "Active For": "2",
       "Recovery": "13",
       "Overall": "20",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "2B": {
       "Input": "",
       "Damage": "490",
       "Hit Type": "Low",
       "Active On": "9",
       "Active For": "5",
       "Recovery": "17",
       "Overall": "30",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attributes": "Foot",
       "Notes": ""
    },
    "2C": {
       "Input": "",
       "Damage": "620",
       "Hit Type": "Low",
       "Active On": "11",
       "Active For": "5",
       "Recovery": "25",
       "Overall": "40",
       "Frame Advantage": "-12",
       "Invincibility": "",
       "Attributes": "Foot",
       "Notes": ""
    },
    "j.A": {
       "Input": "",
       "Damage": "140",
       "Hit Type": "Overhead",
       "Active On": "8",
       "Active For": "2",
       "Recovery": "13",
       "Overall": "22",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.B": {
       "Input": "",
       "Damage": "440",
       "Hit Type": "Overhead",
       "Active On": "10",
       "Active For": "4",
       "Recovery": "26",
       "Overall": "39",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.C": {
       "Input": "",
       "Damage": "590",
       "Hit Type": "Overhead",
       "Active On": "12",
       "Active For": "4",
       "Recovery": "19",
       "Overall": "34",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "66B": {
       "Input": "",
       "Damage": "650",
       "Hit Type": "Low",
       "Active On": "9",
       "Active For": "16",
       "Recovery": "14",
       "Overall": "38",
       "Frame Advantage": "-12",
       "Invincibility": "",
       "Attributes": "Foot",
       "Notes": ""
    },
    "66C": {
       "Input": "",
       "Damage": "1228",
       "Hit Type": "Mid",
       "Active On": "15",
       "Active For": "18",
       "Recovery": "23",
       "Overall": "55",
       "Frame Advantage": "-9",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "3C": {
       "Input": "",
       "Damage": "620",
       "Hit Type": "Low",
       "Active On": "13",
       "Active For": "3",
       "Recovery": "22",
       "Overall": "37",
       "Frame Advantage": "-7",
       "Invincibility": "9～15 Head",
       "Attributes": "",
       "Notes": ""
    },
    "3[C]": {
       "Input": "",
       "Damage": "898",
       "Hit Type": "Oerhead",
       "Active On": "30",
       "Active For": "3",
       "Recovery": "22",
       "Overall": "54",
       "Frame Advantage": "-7",
       "Invincibility": "27～32 Head",
       "Attributes": "",
       "Notes": ""
    },
    "j.2C": {
       "Input": "",
       "Damage": "674",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "20",
       "Recovery": "9",
       "Overall": "40",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.2[C]": {
       "Input": "",
       "Damage": "1125",
       "Hit Type": "Mid",
       "Active On": "19",
       "Active For": "22",
       "Recovery": "9",
       "Overall": "49",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "FF": {
       "Input": "B+C",
       "Damage": "898",
       "Hit Type": "Overhead",
       "Active On": "26",
       "Active For": "4",
       "Recovery": "33",
       "Overall": "62",
       "Frame Advantage": "-19",
       "Invincibility": "12～36 Foot",
       "Attributes": "",
       "Notes": ""
    },
    "[FF] ": {
       "Input": "B+C",
       "Damage": "898",
       "Hit Type": "Overhead",
       "Active On": "31",
       "Active For": "4",
       "Recovery": "34",
       "Overall": "68",
       "Frame Advantage": "-20",
       "Invincibility": "18～42 Foot",
       "Attributes": "",
       "Notes": ""
    },
    "Throw": {
       "Input": "A+D",
       "Damage": "1570",
       "Hit Type": "Throw",
       "Active On": "4",
       "Active For": "1",
       "Recovery": "22",
       "Overall": "26",
       "Frame Advantage": "",
       "Invincibility": "",
       "Attributes": "Throw",
       "Notes": "投げ無敵時金投げ"
    },
    "236A": {
       "Input": "↓↘→+A",
       "Damage": "453",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "4",
       "Recovery": "26",
       "Overall": "41",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "236B": {
       "Input": "↓↘→+B",
       "Damage": "453",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "4",
       "Recovery": "27",
       "Overall": "42",
       "Frame Advantage": "-7",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "236C": {
       "Input": "↓↘→+C",
       "Damage": "2060",
       "Hit Type": "Mid",
       "Active On": "8",
       "Active For": "4(18)6(16)4(14)6(15)10(6)6",
       "Recovery": "33",
       "Overall": "145",
       "Frame Advantage": "-21",
       "Invincibility": "1～3 All / 4～11 Strike",
       "Attributes": "",
       "Notes": ""
    },
    "236AA": {
       "Input": "→+AorBorC",
       "Damage": "660",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "16",
       "Active For": "6",
       "Recovery": "28",
       "Overall": "49",
       "Frame Advantage": "-8",
       "Invincibility": "7～21Foot",
       "Attributes": "",
       "Notes": ""
    },
    "236BB": {
       "Input": "→+AorBorC",
       "Damage": "660",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "20",
       "Active For": "6",
       "Recovery": "32",
       "Overall": "57",
       "Frame Advantage": "-12",
       "Invincibility": "7～25 Foot",
       "Attributes": "",
       "Notes": ""
    },
    "236AAA": {
       "Input": "→+AorBorC",
       "Damage": "920",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "12(8)6",
       "Recovery": "33",
       "Overall": "67",
       "Frame Advantage": "-21",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "236BBB": {
       "Input": "→+AorBorC",
       "Damage": "920",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "12(8)6",
       "Recovery": "33",
       "Overall": "67",
       "Frame Advantage": "-21",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "623A": {
       "Input": "→↓↘+A",
       "Damage": "898",
       "Hit Type": "Throw",
       "Active On": "33",
       "Active For": "1",
       "Recovery": "39",
       "Overall": "72",
       "Frame Advantage": "-",
       "Invincibility": "13～32 Throw / 33～37 All",
       "Attributes": "Throw",
       "Notes": ""
    },
    "623[A]": {
       "Input": "→↓↘+A",
       "Damage": "898",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "47",
       "Active For": "12",
       "Recovery": "10",
       "Overall": "68",
       "Frame Advantage": "+12",
       "Invincibility": "13～28 Throw",
       "Attributes": "",
       "Notes": ""
    },
    "623B": {
       "Input": "→↓↘+B",
       "Damage": "898",
       "Hit Type": "Throw",
       "Active On": "35",
       "Active For": "1",
       "Recovery": "40",
       "Overall": "74",
       "Frame Advantage": "-",
       "Invincibility": "13～34 Throw / 35～39 All",
       "Attributes": "Throw",
       "Notes": ""
    },
    "623[B]": {
       "Input": "→↓↘+B",
       "Damage": "898",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "57",
       "Active For": "12",
       "Recovery": "4",
       "Overall": "72",
       "Frame Advantage": "+18",
       "Invincibility": "13～32 Throw",
       "Attributes": "",
       "Notes": ""
    },
    "623C": {
       "Input": "→↓↘+C",
       "Damage": "1390",
       "Hit Type": "Throw",
       "Active On": "13",
       "Active For": "2",
       "Recovery": "38",
       "Overall": "52",
       "Frame Advantage": "+1927",
       "Invincibility": "1～11 Throw / 12～17 All",
       "Attributes": "Throw",
       "Notes": "持続1F目は連続技中のみヒットする"
    },
    "214A": {
       "Input": "↓↙←+A",
       "Damage": "898",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "47",
       "Active For": "-",
       "Recovery": "4 Upon Landing",
       "Overall": "53",
       "Frame Advantage": "+22",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "214B": {
       "Input": "↓↙←+B",
       "Damage": "898",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "49",
       "Active For": "-",
       "Recovery": "6 Upon Landing",
       "Overall": "59",
       "Frame Advantage": "+18",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "214C": {
       "Input": "↓↙←+C",
       "Damage": "898",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "51",
       "Active For": "-",
       "Recovery": "6 Upon Landing",
       "Overall": "63",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "214XX": {
       "Input": "AorBorC",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "12 Upon Landing",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "214XXA": {
       "Input": "A",
       "Damage": "680",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "4",
       "Recovery": "12 Upon Landing",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Dive",
       "Notes": ""
    },
    "214XXB": {
       "Input": "B",
       "Damage": "898",
       "Hit Type": "Overhead",
       "Active On": "9",
       "Active For": "4",
       "Recovery": "12 Upon Landing",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Dive",
       "Notes": ""
    },
    "214XXC": {
       "Input": "C",
       "Damage": "898",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "4",
       "Recovery": "14 Upon Landing",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Dive",
       "Notes": ""
    },
    "214XXD": {
       "Input": "D",
       "Damage": "898",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "36",
       "Active For": "-",
       "Recovery": "12 Upon Landing",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "j,214A": {
       "Input": "空中↓↙←+A",
       "Damage": "898",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "43",
       "Active For": "-",
       "Recovery": "6 Upon Landing",
       "Overall": "-",
       "Frame Advantage": "+7",
       "Invincibility": "硬直差は最低空時のもの",
       "Attributes": "",
       "Notes": "[translator note] I have no idea what the invuln on 214X is"
    },
    "j.214B": {
       "Input": "空中↓↙←+B",
       "Damage": "898",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "45",
       "Active For": "-",
       "Recovery": "6 Upon Landing",
       "Overall": "-",
       "Frame Advantage": "+7",
       "Invincibility": "硬直差は最低空時のもの",
       "Attributes": "",
       "Notes": ""
    },
    "j.214C": {
       "Input": "空中↓↙←+C",
       "Damage": "898",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "47",
       "Active For": "-",
       "Recovery": "6 Upon Landing",
       "Overall": "-",
       "Frame Advantage": "+7",
       "Invincibility": "硬直差は最低空時のもの",
       "Attributes": "",
       "Notes": ""
    },
    "IW": {
       "Input": "←↙↓↘→+D",
       "Damage": "3150",
       "Hit Type": "Throw",
       "Active On": "9",
       "Active For": "30",
       "Recovery": "52",
       "Overall": "90",
       "Frame Advantage": "-",
       "Invincibility": "1～9 All / 10～38 Strike",
       "Attributes": "Throw",
       "Notes": ""
    },
    "IWEXS": {
       "Input": "A+B+C+D",
       "Damage": "3756",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "6",
       "Recovery": "47",
       "Overall": "67",
       "Frame Advantage": "-25",
       "Invincibility": "1～26 All",
       "Attributes": "",
       "Notes": ""
    }
 }