module.exports = {
    "5A": {
       "Input": "",
       "Damage": "180",
       "Hit Type": "Mid",
       "Active On": "6",
       "Active For": "2",
       "Recovery": "13",
       "Overall": "20",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "5B": {
       "Input": "",
       "Damage": "530",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "5",
       "Recovery": "16",
       "Overall": "29",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "5C": {
       "Input": "",
       "Damage": "610",
       "Hit Type": "Mid",
       "Active On": "15",
       "Active For": "3",
       "Recovery": "24",
       "Overall": "41",
       "Frame Advantage": "-9",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "2A": {
       "Input": "",
       "Damage": "170",
       "Hit Type": "Mid",
       "Active On": "7",
       "Active For": "2",
       "Recovery": "12",
       "Overall": "20",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "2B": {
       "Input": "",
       "Damage": "420",
       "Hit Type": "Low",
       "Active On": "7",
       "Active For": "5",
       "Recovery": "13",
       "Overall": "24",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attributes": "Foot",
       "Notes": ""
    },
    "2C": {
       "Input": "",
       "Damage": "540",
       "Hit Type": "Low",
       "Active On": "11",
       "Active For": "2",
       "Recovery": "29",
       "Overall": "41",
       "Frame Advantage": "-15",
       "Invincibility": "",
       "Attributes": "Foot",
       "Notes": ""
    },
    "j.A": {
       "Input": "",
       "Damage": "140",
       "Hit Type": "Overhead",
       "Active On": "8",
       "Active For": "2",
       "Recovery": "14",
       "Overall": "23",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.B": {
       "Input": "",
       "Damage": "410",
       "Hit Type": "Overhead",
       "Active On": "10",
       "Active For": "3",
       "Recovery": "17",
       "Overall": "29",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.C": {
       "Input": "",
       "Damage": "585",
       "Hit Type": "Overhead / Overhead",
       "Active On": "12",
       "Active For": "2",
       "Recovery": "34",
       "Overall": "47",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "初段ガード後は上段\n動作終了後は空中で行動可能"
    },
    "j.[C]": {
       "Input": "",
       "Damage": "772",
       "Hit Type": "Overhead / Overhead",
       "Active On": "25",
       "Active For": "3",
       "Recovery": "34",
       "Overall": "61",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "初段ガード後は上段\n動作終了後は空中で行動可能"
    },
    "66B": {
       "Input": "",
       "Damage": "564",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "3",
       "Recovery": "15",
       "Overall": "27",
       "Frame Advantage": "-4",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "66C": {
       "Input": "",
       "Damage": "850",
       "Hit Type": "Mid",
       "Active On": "18",
       "Active For": "4",
       "Recovery": "19",
       "Overall": "40",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "6B": {
       "Input": "",
       "Damage": "720",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "14",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "38",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attributes": "Projectile",
       "Notes": "Costs 300 life (150 in vorpal)"
    },
    "6BB": {
       "Input": "",
       "Damage": "720",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "18",
       "Active For": "7",
       "Recovery": "15",
       "Overall": "39",
       "Frame Advantage": "+3",
       "Invincibility": "",
       "Attributes": "Projectile",
       "Notes": ""
    },
    "3B": {
       "Input": "",
       "Damage": "564",
       "Hit Type": "Mid",
       "Active On": "8",
       "Active For": "3",
       "Recovery": "23",
       "Overall": "33",
       "Frame Advantage": "-6",
       "Invincibility": "7～10 Head",
       "Attributes": "",
       "Notes": ""
    },
    "6C": {
       "Input": "",
       "Damage": "550",
       "Hit Type": "Mid",
       "Active On": "13",
       "Active For": "3",
       "Recovery": "23",
       "Overall": "38",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "6[C]": {
       "Input": "",
       "Damage": "740",
       "Hit Type": "Overhead",
       "Active On": "27",
       "Active For": "3",
       "Recovery": "26",
       "Overall": "55",
       "Frame Advantage": "-11",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "3C": {
       "Input": "",
       "Damage": "710",
       "Hit Type": "Mid",
       "Active On": "15",
       "Active For": "5",
       "Recovery": "20",
       "Overall": "39",
       "Frame Advantage": "-9",
       "Invincibility": "11～16 Head",
       "Attributes": "",
       "Notes": ""
    },
    "3[C]": {
       "Input": "",
       "Damage": "890",
       "Hit Type": "Mid",
       "Active On": "20",
       "Active For": "5",
       "Recovery": "20",
       "Overall": "44",
       "Frame Advantage": "-7",
       "Invincibility": "17～21 Head",
       "Attributes": "",
       "Notes": ""
    },
    "j.6B": {
       "Input": "",
       "Damage": "720",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "20",
       "Active For": "-",
       "Recovery": "10 Upon Landing",
       "Overall": "31",
       "Frame Advantage": "+11",
       "Invincibility": "",
       "Attributes": "Projectile",
       "Notes": "硬直差は最低空で出してガードさせた場合のもの\nCosts 300 life (150 in vorpal)"
    },
    "j.6BB": {
       "Input": "",
       "Damage": "720",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "7",
       "Recovery": "9 Upon Landing",
       "Overall": "48",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attributes": "Projectile",
       "Notes": "硬直差は最低空で出してガードさせた場合のもの"
    },
    "5BB": {
       "Input": "",
       "Damage": "490",
       "Hit Type": "Mid",
       "Active On": "14",
       "Active For": "7",
       "Recovery": "14",
       "Overall": "34",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "FF": {
       "Input": "B+C",
       "Damage": "320",
       "Hit Type": "Mid",
       "Active On": "15",
       "Active For": "3",
       "Recovery": "25",
       "Overall": "42",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attributes": "Foot",
       "Notes": "Costs 300 life"
    },
    "FF (Vorpal)": {
       "Input": "B+C",
       "Damage": "320",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "3",
       "Recovery": "25",
       "Overall": "39",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attributes": "Foot",
       "Notes": "Costs 150 life"
    },
    "j.FF": {
       "Input": "Jump B+C",
       "Damage": "320",
       "Hit Type": "Mid",
       "Active On": "15",
       "Active For": "3",
       "Recovery": "19",
       "Overall": "36",
       "Frame Advantage": "+1",
       "Invincibility": "",
       "Attributes": "Foot",
       "Notes": "動作終了後は空中で行動可能\nCosts 300 life"
    },
    "j.FF (Vorpal)": {
       "Input": "Jump B+C",
       "Damage": "320",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "3",
       "Recovery": "19",
       "Overall": "33",
       "Frame Advantage": "+1",
       "Invincibility": "",
       "Attributes": "Foot",
       "Notes": "動作終了後は空中で行動可能\nCosts 150 life"
    },
    "Throw": {
       "Input": "A+D",
       "Damage": "1536",
       "Hit Type": "Throw",
       "Active On": "4",
       "Active For": "1",
       "Recovery": "22",
       "Overall": "26",
       "Frame Advantage": "",
       "Invincibility": "",
       "Attributes": "Throw",
       "Notes": "Recovers 400 health。投げ無敵時金投げ"
    },
    "236A": {
       "Input": "↓↘→+A",
       "Damage": "1337",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "34",
       "Active For": "37",
       "Recovery": "-",
       "Overall": "34",
       "Frame Advantage": "+72",
       "Invincibility": "",
       "Attributes": "Projectile",
       "Notes": "Costs 300 life (250 in vorpal)"
    },
    "236B": {
       "Input": "↓↘→+B",
       "Damage": "1337",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "34",
       "Active For": "37",
       "Recovery": "-",
       "Overall": "34",
       "Frame Advantage": "+72",
       "Invincibility": "",
       "Attributes": "Projectile",
       "Notes": "Costs 300 life (250 in vorpal)"
    },
    "236C": {
       "Input": "↓↘→+C",
       "Damage": "1665",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "19",
       "Active For": "52",
       "Recovery": "-",
       "Overall": "34",
       "Frame Advantage": "+62",
       "Invincibility": "1～3 Throw",
       "Attributes": "Projectile",
       "Notes": "Costs 300 life (250 in vorpal)"
    },
    "236X (Dissolve)": {
       "Input": "",
       "Damage": "720",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "30",
       "Active For": "18",
       "Recovery": "-",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Foot",
       "Notes": ""
    },
    "j.236A": {
       "Input": "Jump ↓↘→+A",
       "Damage": "1337",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "37",
       "Active For": "37",
       "Recovery": "10 Upon Landing",
       "Overall": "40",
       "Frame Advantage": "+69",
       "Invincibility": "",
       "Attributes": "",
       "Notes": "After going through lag, you retain all air momentum.\nCosts 300 life (250 in vorpal)"
    },
    "j.236B": {
       "Input": "Jump↓↘→+B",
       "Damage": "1337",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "37",
       "Active For": "37",
       "Recovery": "10 Upon Landing",
       "Overall": "40",
       "Frame Advantage": "+69",
       "Invincibility": "",
       "Attributes": "",
       "Notes": "After going through lag, you retain all air momentum.\nCosts 300 life (250 in vorpal)"
    },
    "j.236C": {
       "Input": "Jump↓↘→+C",
       "Damage": "1665",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "22",
       "Active For": "52",
       "Recovery": "10 Upon Landing",
       "Overall": "40",
       "Frame Advantage": "+59",
       "Invincibility": "",
       "Attributes": "",
       "Notes": "After going through lag, you retain all air momentum.\nCosts 300 life (250 in vorpal)"
    },
    "j.236X (Dissolve)": {
       "Input": "",
       "Damage": "720",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "30",
       "Active For": "18",
       "Recovery": "-",
       "Overall": "-",
       "Frame Advantage": "",
       "Invincibility": "",
       "Attributes": "Foot",
       "Notes": ""
    },
    "623A": {
       "Input": "→↓↘+A",
       "Damage": "1352",
       "Hit Type": "Low",
       "Active On": "18",
       "Active For": "6",
       "Recovery": "12",
       "Overall": "35",
       "Frame Advantage": "-4",
       "Invincibility": "15～23 Dive / 18～23 Head",
       "Attributes": "",
       "Notes": ""
    },
    "623B": {
       "Input": "→↓↘+B",
       "Damage": "1393",
       "Hit Type": "Low",
       "Active On": "11",
       "Active For": "6",
       "Recovery": "18",
       "Overall": "34",
       "Frame Advantage": "-10",
       "Invincibility": "6～16 Dive / 11～16 Head",
       "Attributes": "",
       "Notes": ""
    },
    "623C": {
       "Input": "→↓↘+C",
       "Damage": "1812",
       "Hit Type": "Mid",
       "Active On": "13",
       "Active For": "12",
       "Recovery": "20",
       "Overall": "44",
       "Frame Advantage": "-12",
       "Invincibility": "1～7 All /8～9 Throw",
       "Attributes": "",
       "Notes": ""
    },
    "623A (Dissolve)": {
       "Input": "",
       "Damage": "1040",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "24",
       "Active For": "7",
       "Recovery": "-",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Foot",
       "Notes": ""
    },
    "623B (Dissolve)": {
       "Input": "",
       "Damage": "1040",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "17",
       "Active For": "7",
       "Recovery": "-",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Foot",
       "Notes": ""
    },
    "623C (Dissolve)": {
       "Input": "",
       "Damage": "1040",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "16",
       "Active For": "7",
       "Recovery": "-",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Foot",
       "Notes": ""
    },
    "214A": {
       "Input": "↓↙←+A",
       "Damage": "1673",
       "Hit Type": "Mid",
       "Active On": "13",
       "Active For": "2(9)7",
       "Recovery": "24",
       "Overall": "54",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "214[A]": {
       "Input": "↓↙←+A",
       "Damage": "788・893",
       "Hit Type": "Mid / Mid",
       "Active On": "31・20",
       "Active For": "5・3",
       "Recovery": "18",
       "Overall": "53",
       "Frame Advantage": "-1",
       "Invincibility": "",
       "Attributes": "",
       "Notes": "ダメージ、発生、持続はそれぞれ「設置・解放」時のもの\nCosts 300 life (250 in vorpal)"
    },
    "214B": {
       "Input": "↓↙←+B",
       "Damage": "1673",
       "Hit Type": "Mid",
       "Active On": "14",
       "Active For": "2(13)7",
       "Recovery": "27",
       "Overall": "62",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "214[B]": {
       "Input": "↓↙←+B",
       "Damage": "788・893",
       "Hit Type": "Mid / Mid",
       "Active On": "31・20",
       "Active For": "5・3",
       "Recovery": "18",
       "Overall": "53",
       "Frame Advantage": "-1",
       "Invincibility": "",
       "Attributes": "",
       "Notes": "ダメージ、発生、持続はそれぞれ「設置・解放」時のもの\nCosts 300 life (250 in vorpal)"
    },
    "214C": {
       "Input": "↓↙←+C",
       "Damage": "1766",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "16",
       "Active For": "8",
       "Recovery": "36",
       "Overall": "59",
       "Frame Advantage": "+6",
       "Invincibility": "1～3 Throw",
       "Attributes": "",
       "Notes": "ダメージはは8ヒット時のもの"
    },
    "22A": {
       "Input": "↓↓+A",
       "Damage": "893",
       "Hit Type": "Mid",
       "Active On": "18",
       "Active For": "3",
       "Recovery": "25",
       "Overall": "45",
       "Frame Advantage": "+1",
       "Invincibility": "",
       "Attributes": "",
       "Notes": "Costs 300 life (250 in vorpal)"
    },
    "22B": {
       "Input": "↓↓+B",
       "Damage": "893",
       "Hit Type": "Mid",
       "Active On": "18",
       "Active For": "3",
       "Recovery": "25",
       "Overall": "45",
       "Frame Advantage": "+1",
       "Invincibility": "",
       "Attributes": "",
       "Notes": "Costs 300 life (250 in vorpal)"
    },
    "22C": {
       "Input": "↓↓+C",
       "Damage": "1344",
       "Hit Type": "Mid",
       "Active On": "16",
       "Active For": "3",
       "Recovery": "24",
       "Overall": "42",
       "Frame Advantage": "+2",
       "Invincibility": "1～3 Throw",
       "Attributes": "",
       "Notes": "Costs 300 life (250 in vorpal)"
    },
    "22X (Dissolve)": {
       "Input": "",
       "Damage": "893",
       "Hit Type": "Mid",
       "Active On": "18",
       "Active For": "3",
       "Recovery": "-",
       "Overall": "-",
       "Frame Advantage": "",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "63214C": {
       "Input": "→↘↓↙←+C",
       "Damage": "1265",
       "Hit Type": "Throw",
       "Active On": "9",
       "Active For": "2",
       "Recovery": "36",
       "Overall": "46",
       "Frame Advantage": "",
       "Invincibility": "1～10 All",
       "Attributes": "Throw",
       "Notes": "持続1F目は連続技中のみヒットする\nRecovers 1200 health\n投げ無敵時金投げ"
    },
    "IW": {
       "Input": "←↙↓↘→+D",
       "Damage": "3159",
       "Hit Type": "Low ※/ Mid (Air Blockable)",
       "Active On": "12",
       "Active For": "21",
       "Recovery": "46",
       "Overall": "78",
       "Frame Advantage": "-38",
       "Invincibility": "1～29 All / 30～31 Throw",
       "Attributes": "",
       "Notes": "硬直差は密着の場合のもの。少し離れて飛び道具部分を当てると-31\n足元部分の攻撃判定のみ下段"
    },
    "IWEXS": {
       "Input": "A+B+C+D",
       "Damage": "3756",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "6",
       "Recovery": "47",
       "Overall": "67",
       "Frame Advantage": "-25",
       "Invincibility": "1～26 All",
       "Attributes": "",
       "Notes": ""
    }
 }