export default {
    "5A": {
       "Command": "",
       "Damage": "180",
       "Hit Type": "Mid",
       "Active On": "6",
       "Active For": "2",
       "Recovery": "12",
       "Total": "19",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "5B": {
       "Command": "",
       "Damage": "400",
       "Hit Type": "Mid",
       "Active On": "8",
       "Active For": "2",
       "Recovery": "19",
       "Total": "28",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "5C": {
       "Command": "",
       "Damage": "510",
       "Hit Type": "Mid",
       "Active On": "11",
       "Active For": "3",
       "Recovery": "22",
       "Total": "35",
       "Frame Advantage": "-7",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "2A": {
       "Command": "",
       "Damage": "140",
       "Hit Type": "Low",
       "Active On": "6",
       "Active For": "2",
       "Recovery": "11",
       "Total": "18",
       "Frame Advantage": "-1",
       "Invincibility": "",
       "Attributes": "Foot",
       "Notes": ""
    },
    "2B": {
       "Command": "",
       "Damage": "400",
       "Hit Type": "Low",
       "Active On": "9",
       "Active For": "3",
       "Recovery": "16",
       "Total": "27",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attributes": "Foot",
       "Notes": ""
    },
    "2C": {
       "Command": "",
       "Damage": "580",
       "Hit Type": "Low",
       "Active On": "12",
       "Active For": "3",
       "Recovery": "26",
       "Total": "40",
       "Frame Advantage": "-11",
       "Invincibility": "",
       "Attributes": "Foot",
       "Notes": ""
    },
    "j.A": {
       "Command": "",
       "Damage": "140",
       "Hit Type": "Overhead",
       "Active On": "8",
       "Active For": "2",
       "Recovery": "19",
       "Total": "28",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.B": {
       "Command": "",
       "Damage": "400",
       "Hit Type": "Overhead",
       "Active On": "10",
       "Active For": "4",
       "Recovery": "20",
       "Total": "33",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.C": {
       "Command": "",
       "Damage": "520",
       "Hit Type": "Overhead",
       "Active On": "12",
       "Active For": "2",
       "Recovery": "23",
       "Total": "36",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "66B": {
       "Command": "",
       "Damage": "400",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "2",
       "Recovery": "20",
       "Total": "31",
       "Frame Advantage": "-4",
       "Invincibility": "9～11Head",
       "Attributes": "",
       "Notes": ""
    },
    "66C": {
       "Command": "",
       "Damage": "780",
       "Hit Type": "Mid",
       "Active On": "11",
       "Active For": "3",
       "Recovery": "21",
       "Total": "34",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "6C": {
       "Command": "→+C",
       "Damage": "640",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "14",
       "Active For": "14",
       "Recovery": "29",
       "Total": "56",
       "Frame Advantage": "-15",
       "Invincibility": "",
       "Attributes": "",
       "Notes": "硬直差は持続1F目をガードさせた場合のもの\n硬直の終わり際5Fはガードのみ可能"
    },
    "j.2C": {
       "Command": "",
       "Damage": "620",
       "Hit Type": "Overhead",
       "Active On": "12",
       "Active For": "4",
       "Recovery": "17",
       "Total": "32",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "5BB": {
       "Command": "",
       "Damage": "450",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "2",
       "Recovery": "20",
       "Total": "33",
       "Frame Advantage": "-6",
       "Invincibility": "10～11Foot",
       "Attributes": "",
       "Notes": ""
    },
    "5CC": {
       "Command": "",
       "Damage": "427",
       "Hit Type": "Mid",
       "Active On": "6",
       "Active For": "5",
       "Recovery": "26",
       "Total": "36",
       "Frame Advantage": "-13",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "FF": {
       "Command": "B+C",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Total": "33",
       "Frame Advantage": "-",
       "Invincibility": "3～26Head/3～26 Projectile /8～25Strike",
       "Attributes": "",
       "Notes": ""
    },
    "Throw": {
       "Command": "A+D",
       "Damage": "1570",
       "Hit Type": "Throw",
       "Active On": "4",
       "Active For": "1",
       "Recovery": "22",
       "Total": "26",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Throw",
       "Notes": "投げ無敵時金投げ"
    },
    "236A": {
       "Command": "↓↘→+A",
       "Damage": "650",
       "Hit Type": "Mid",
       "Active On": "15",
       "Active For": "5",
       "Recovery": "32",
       "Total": "51",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "236B": {
       "Command": "↓↘→+B",
       "Damage": "710",
       "Hit Type": "Mid",
       "Active On": "14",
       "Active For": "8",
       "Recovery": "30",
       "Total": "51",
       "Frame Advantage": "-9",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "236[B]": {
       "Command": "↓↘→+B",
       "Damage": "820",
       "Hit Type": "Mid",
       "Active On": "20",
       "Active For": "10",
       "Recovery": "12",
       "Total": "51",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "236C": {
       "Command": "↓↘→+C",
       "Damage": "1672",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "5(1)5(25)4",
       "Recovery": "3",
       "Total": "51",
       "Frame Advantage": "First hit -2\nSecond +38",
       "Invincibility": "1～3 Throw",
       "Attributes": "",
       "Notes": "最終段前に両者行動可能"
    },
    "(Azhi in Air) 236A": {
       "Command": "↓↘→+A",
       "Damage": "650",
       "Hit Type": "Mid",
       "Active On": "着地後1",
       "Active For": "5",
       "Recovery": "-",
       "Total": "51",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "",
       "Notes": "発生、硬直差はアジ・ダハーカの高度依存"
    },
    "(Azhi in Air) 236B": {
       "Command": "↓↘→+B",
       "Damage": "710",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "4",
       "Recovery": "-",
       "Total": "51",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "",
       "Notes": "硬直差はアジ・ダハーカの高度依存"
    },
    "(Azhi in Air) 236C": {
       "Command": "↓↘→+C",
       "Damage": "1672",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "Until Landing (1)5(25)4",
       "Recovery": "",
       "Total": "51",
       "Frame Advantage": "-",
       "Invincibility": "1～3 Throw",
       "Attributes": "",
       "Notes": "硬直差はアジ・ダハーカの高度依存"
    },
    "j.236A": {
       "Command": "空中↓↘→+A",
       "Damage": "650",
       "Hit Type": "Mid",
       "Active On": "18",
       "Active For": "5",
       "Recovery": "12 upon landing",
       "Total": "71",
       "Frame Advantage": "-25",
       "Invincibility": "",
       "Attributes": "",
       "Notes": "硬直差はジャンプの昇りから最速で出した場合のもの"
    },
    "j.236B": {
       "Command": "空中↓↘→+B",
       "Damage": "710",
       "Hit Type": "Mid",
       "Active On": "17",
       "Active For": "8",
       "Recovery": "12 upon landing",
       "Total": "71",
       "Frame Advantage": "-26",
       "Invincibility": "",
       "Attributes": "",
       "Notes": "硬直差はジャンプの昇りから最速で出した場合のもの"
    },
    "j.236[B]": {
       "Command": "空中↓↘→+B",
       "Damage": "820",
       "Hit Type": "Mid",
       "Active On": "23",
       "Active For": "10",
       "Recovery": "12 upon landing",
       "Total": "71",
       "Frame Advantage": "-20",
       "Invincibility": "",
       "Attributes": "",
       "Notes": "硬直差はジャンプの昇りから最速で出した場合のもの"
    },
    "j.236C": {
       "Command": "空中↓↘→+C",
       "Damage": "1672",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "5(1)5(25)4",
       "Recovery": "12 upon landing",
       "Total": "71",
       "Frame Advantage": "+21",
       "Invincibility": "1～3 Throw",
       "Attributes": "",
       "Notes": "硬直差はジャンプの昇りから最速で出した場合のもの"
    },
    "(Azhi in Air) j,236A": {
       "Command": "空中↓↘→+A",
       "Damage": "650",
       "Hit Type": "Mid",
       "Active On": "着地後1",
       "Active For": "5",
       "Recovery": "12 upon landing",
       "Total": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "",
       "Notes": "発生、硬直差はアジ・ダハーカの高度依存"
    },
    "(Azhi in Air) j.236B": {
       "Command": "空中↓↘→+B",
       "Damage": "710",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "4",
       "Recovery": "12 upon landing",
       "Total": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "",
       "Notes": "硬直差はアジ・ダハーカの高度依存"
    },
    "(Azhi in Air) j.236C": {
       "Command": "空中↓↘→+C",
       "Damage": "1672",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "Until Landing  (1)5(25)4",
       "Recovery": "12 upon landing",
       "Total": "-",
       "Frame Advantage": "-",
       "Invincibility": "1～3 Throw",
       "Attributes": "",
       "Notes": "硬直差はアジ・ダハーカの高度依存"
    },
    "623A": {
       "Command": "→↓↘+A",
       "Damage": "570",
       "Hit Type": "Mid",
       "Active On": "23",
       "Active For": "5",
       "Recovery": "16",
       "Total": "43",
       "Frame Advantage": "+6",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "623B": {
       "Command": "→↓↘+B",
       "Damage": "690",
       "Hit Type": "Mid",
       "Active On": "27",
       "Active For": "5",
       "Recovery": "12",
       "Total": "43",
       "Frame Advantage": "+10",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "623C": {
       "Command": "→↓↘+C",
       "Damage": "1382",
       "Hit Type": "Mid",
       "Active On": "14",
       "Active For": "5(12)5",
       "Recovery": "8",
       "Total": "43",
       "Frame Advantage": "+17",
       "Invincibility": "1～3 Throw",
       "Attributes": "",
       "Notes": ""
    },
    "(Azhi in Air) 623A": {
       "Command": "→↓↘+A",
       "Damage": "570",
       "Hit Type": "Mid",
       "Active On": "14",
       "Active For": "5",
       "Recovery": "35",
       "Total": "43",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "(Azhi in Air) 623B": {
       "Command": "→↓↘+B",
       "Damage": "690",
       "Hit Type": "Mid",
       "Active On": "18",
       "Active For": "5",
       "Recovery": "21",
       "Total": "43",
       "Frame Advantage": "+1",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "(Azhi in Air) 623C": {
       "Command": "→↓↘+C",
       "Damage": "1382",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "5(12)5",
       "Recovery": "7",
       "Total": "43",
       "Frame Advantage": "+18",
       "Invincibility": "1～3 Throw",
       "Attributes": "",
       "Notes": ""
    },
    "j.623A": {
       "Command": "空中→↓↘+A",
       "Damage": "570",
       "Hit Type": "Mid",
       "Active On": "26",
       "Active For": "5",
       "Recovery": "12 upon landing",
       "Total": "71",
       "Frame Advantage": "-19",
       "Invincibility": "",
       "Attributes": "",
       "Notes": "硬直差はジャンプの昇りから最速で出した場合のもの"
    },
    "j.623B": {
       "Command": "空中→↓↘+B",
       "Damage": "690",
       "Hit Type": "Mid",
       "Active On": "30",
       "Active For": "5",
       "Recovery": "12 upon landing",
       "Total": "71",
       "Frame Advantage": "-15",
       "Invincibility": "",
       "Attributes": "",
       "Notes": "硬直差はジャンプの昇りから最速で出した場合のもの"
    },
    "j.623C": {
       "Command": "空中→↓↘+C",
       "Damage": "1382",
       "Hit Type": "Mid",
       "Active On": "17",
       "Active For": "5(12)5",
       "Recovery": "12 upon landing",
       "Total": "71",
       "Frame Advantage": "-8",
       "Invincibility": "1～3 Throw",
       "Attributes": "",
       "Notes": "硬直差はジャンプの昇りから最速で出した場合のもの"
    },
    "(Azhi in Air) j.623A": {
       "Command": "空中→↓↘+A",
       "Damage": "570",
       "Hit Type": "Mid",
       "Active On": "17",
       "Active For": "5",
       "Recovery": "12 upon landing",
       "Total": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "(Azhi in Air) j.623B": {
       "Command": "空中→↓↘+B",
       "Damage": "690",
       "Hit Type": "Mid",
       "Active On": "21",
       "Active For": "5",
       "Recovery": "12 upon landing",
       "Total": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "(Azhi in Air) j.623C": {
       "Command": "空中→↓↘+C",
       "Damage": "1382",
       "Hit Type": "Mid",
       "Active On": "13",
       "Active For": "5(12)5",
       "Recovery": "12 upon landing",
       "Total": "-",
       "Frame Advantage": "-",
       "Invincibility": "1～3 Throw",
       "Attributes": "",
       "Notes": ""
    },
    "214A": {
       "Command": "↓↙←+A",
       "Damage": "550",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "18",
       "Active For": "-",
       "Recovery": "-",
       "Total": "47",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "硬直差は密着から立ち状態のハイドにガードさせた場合のもの"
    },
    "214[A]": {
       "Command": "↓↙←+A",
       "Damage": "1171",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "32",
       "Active For": "-",
       "Recovery": "-",
       "Total": "47",
       "Frame Advantage": "+12",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "硬直差は密着から立ち状態のハイドにガードさせた場合のもの\nダメージは全段同時にヒットさせた場合のもの"
    },
    "214B": {
       "Command": "↓↙←+B",
       "Damage": "550",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "18",
       "Active For": "-",
       "Recovery": "-",
       "Total": "47",
       "Frame Advantage": "±0",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "硬直差は近距離から立ち状態のハイドにガードさせた場合のもの"
    },
    "214[B]": {
       "Command": "↓↙←+B",
       "Damage": "1171",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "32",
       "Active For": "-",
       "Recovery": "-",
       "Total": "47",
       "Frame Advantage": "+15",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "硬直差は密着から立ち状態のハイドにガードさせた場合のもの\nダメージは全段同時にヒットさせた場合のもの"
    },
    "214C": {
       "Command": "↓↙←+C",
       "Damage": "1722",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "18",
       "Active For": "-",
       "Recovery": "-",
       "Total": "47",
       "Frame Advantage": "+42",
       "Invincibility": "1～3 Throw",
       "Attributes": "Head",
       "Notes": "硬直差は立ち状態のハイドに最終段までガードさせた場合のもの"
    },
    "(Azhi in Air) 214A": {
       "Command": "↓↙←+A",
       "Damage": "550",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "17",
       "Active For": "-",
       "Recovery": "-",
       "Total": "47",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": ""
    },
    "(Azhi in Air) 214[A]": {
       "Command": "↓↙←+A",
       "Damage": "1171",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "31",
       "Active For": "-",
       "Recovery": "-",
       "Total": "47",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": ""
    },
    "(Azhi in Air) 214B": {
       "Command": "↓↙←+B",
       "Damage": "550",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "17",
       "Active For": "-",
       "Recovery": "-",
       "Total": "47",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": ""
    },
    "(Azhi in Air) 214[B]": {
       "Command": "↓↙←+B",
       "Damage": "1171",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "31",
       "Active For": "-",
       "Recovery": "-",
       "Total": "47",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": ""
    },
    "(Azhi in Air) 214C": {
       "Command": "↓↙←+C",
       "Damage": "1722",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "14",
       "Active For": "-",
       "Recovery": "-",
       "Total": "47",
       "Frame Advantage": "-",
       "Invincibility": "1～3 Throw",
       "Attributes": "Head",
       "Notes": ""
    },
    "j.214A": {
       "Command": "空中↓↙←+A",
       "Damage": "550",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "21",
       "Active For": "-",
       "Recovery": "12 upon landing",
       "Total": "71",
       "Frame Advantage": "-23",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "硬直差はジャンプの昇りから最速で出し、立ち状態のハイドにガードさせた場合のもの場合のもの"
    },
    "j.214[A]": {
       "Command": "空中↓↙←+A",
       "Damage": "1171",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "35",
       "Active For": "-",
       "Recovery": "12 upon landing",
       "Total": "71",
       "Frame Advantage": "-9",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "硬直差はジャンプの昇りから最速で出し、立ち状態のハイドにガードさせた場合のもの場合のもの"
    },
    "j.214B": {
       "Command": "空中↓↙←+B",
       "Damage": "550",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "21",
       "Active For": "-",
       "Recovery": "12 upon landing",
       "Total": "71",
       "Frame Advantage": "-20",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "硬直差はジャンプの昇りから最速で出し、立ち状態のハイドにガードさせた場合のもの場合のもの"
    },
    "j.214[B]": {
       "Command": "空中↓↙←+B",
       "Damage": "1171",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "35",
       "Active For": "-",
       "Recovery": "12 upon landing",
       "Total": "71",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "硬直差はジャンプの昇りから最速で出し、立ち状態のハイドにガードさせた場合のもの場合のもの"
    },
    "j.214C": {
       "Command": "空中↓↙←+C",
       "Damage": "1722",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "21",
       "Active For": "-",
       "Recovery": "12 upon landing",
       "Total": "71",
       "Frame Advantage": "+21",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "硬直差はジャンプの昇りから最速で出し、立ち状態のハイドにガードさせた場合のもの場合のもの"
    },
    "(Azhi in Air) j.214A": {
       "Command": "空中↓↙←+A",
       "Damage": "550",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "20",
       "Active For": "-",
       "Recovery": "12 upon landing",
       "Total": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": ""
    },
    "(Azhi in Air) j.214[A]": {
       "Command": "空中↓↙←+A",
       "Damage": "1171",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "34",
       "Active For": "-",
       "Recovery": "12 upon landing",
       "Total": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": ""
    },
    "(Azhi in Air) j.214B": {
       "Command": "空中↓↙←+B",
       "Damage": "550",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "20",
       "Active For": "-",
       "Recovery": "12 upon landing",
       "Total": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": ""
    },
    "(Azhi in Air) j.214[B]": {
       "Command": "空中↓↙←+B",
       "Damage": "1171",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "34",
       "Active For": "-",
       "Recovery": "12 upon landing",
       "Total": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": ""
    },
    "(Azhi in Air) j.214C": {
       "Command": "空中↓↙←+C",
       "Damage": "1722",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "17",
       "Active For": "-",
       "Recovery": "12 upon landing",
       "Total": "-",
       "Frame Advantage": "",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": ""
    },
    "22A": {
       "Command": "↓↓+A",
       "Damage": "1139",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "37",
       "Active For": "2",
       "Recovery": "0",
       "Total": "21",
       "Frame Advantage": "+36",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "22B": {
       "Command": "↓↓+B",
       "Damage": "1139",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "64",
       "Active For": "2",
       "Recovery": "0",
       "Total": "33",
       "Frame Advantage": "+57",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "22C": {
       "Command": "↓↓+C",
       "Damage": "1649",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "54",
       "Active For": "2",
       "Recovery": "0",
       "Total": "21",
       "Frame Advantage": "+53",
       "Invincibility": "1～3 Throw",
       "Attributes": "",
       "Notes": ""
    },
    "j,22A": {
       "Command": "空中↓↓+A",
       "Damage": "1139",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "41",
       "Active For": "2",
       "Recovery": "12 upon landing",
       "Total": "71",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attributes": "",
       "Notes": "硬直差はジャンプの昇りから最速で出した場合のもの"
    },
    "j.22B": {
       "Command": "空中↓↓+B",
       "Damage": "1139",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "68",
       "Active For": "2",
       "Recovery": "12 upon landing",
       "Total": "71",
       "Frame Advantage": "+25",
       "Invincibility": "",
       "Attributes": "",
       "Notes": "硬直差はジャンプの昇りから最速で出した場合のもの"
    },
    "j.22C": {
       "Command": "空中↓↓+C",
       "Damage": "1649",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "58",
       "Active For": "2",
       "Recovery": "12 upon landing",
       "Total": "71",
       "Frame Advantage": "+15",
       "Invincibility": "1～3 Throw",
       "Attributes": "",
       "Notes": "硬直差はジャンプの昇りから最速で出した場合のもの"
    },
    "IW": {
       "Command": "←↙↓↘→+D",
       "Damage": "3042",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "13",
       "Active For": "2",
       "Recovery": "55",
       "Total": "69",
       "Frame Advantage": "-39",
       "Invincibility": "1～14 All /15～31 Throw",
       "Attributes": "",
       "Notes": ""
    },
    "IWEXS": {
       "Command": "A+B+C+D",
       "Damage": "3760",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "6",
       "Recovery": "47",
       "Total": "67",
       "Frame Advantage": "-25",
       "Invincibility": "1～26 All",
       "Attributes": "",
       "Notes": ""
    }
 };