module.exports = {
    "5A": {
       "Input": "",
       "Damage": "368",
       "Hit Type": "Mid",
       "Active On": "6",
       "Active For": "2(6)2",
       "Recovery": "11",
       "Overall": "26",
       "Frame Advantage": "-1",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "5B": {
       "Input": "",
       "Damage": "580",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "3",
       "Recovery": "20",
       "Overall": "31",
       "Frame Advantage": "-7",
       "Invincibility": "",
       "Attribute": "",
       "備考": "HAVOC発生時、B>B>B>C>C>CまでHACVOC継続"
    },
    "5C": {
       "Input": "",
       "Damage": "690",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "4",
       "Recovery": "30",
       "Overall": "45",
       "Frame Advantage": "-16",
       "Invincibility": "",
       "Attribute": "",
       "備考": "HAVOC発生時、C>C>CまでHACVOC継続"
    },
    "5[C]": {
       "Input": "",
       "Damage": "1807",
       "Hit Type": "Overhead",
       "Active On": "29",
       "Active For": "5",
       "Recovery": "32",
       "Overall": "65",
       "Frame Advantage": "-19",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "2A": {
       "Input": "",
       "Damage": "160",
       "Hit Type": "Low",
       "Active On": "6",
       "Active For": "2",
       "Recovery": "14",
       "Overall": "21",
       "Frame Advantage": "-4",
       "Invincibility": "",
       "Attribute": "Foot",
       "備考": ""
    },
    "2B": {
       "Input": "",
       "Damage": "490",
       "Hit Type": "Mid",
       "Active On": "8",
       "Active For": "4",
       "Recovery": "21",
       "Overall": "32",
       "Frame Advantage": "-9",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "2C": {
       "Input": "",
       "Damage": "700",
       "Hit Type": "Low",
       "Active On": "12",
       "Active For": "3",
       "Recovery": "32",
       "Overall": "46",
       "Frame Advantage": "-17",
       "Invincibility": "",
       "Attribute": "Foot",
       "備考": "HAVOC発生時、2+C>2+C>2+CまでHACVOC継続"
    },
    "2[C]": {
       "Input": "",
       "Damage": "850",
       "Hit Type": "Low",
       "Active On": "25",
       "Active For": "4",
       "Recovery": "37",
       "Overall": "65",
       "Frame Advantage": "-18",
       "Invincibility": "",
       "Attribute": "Foot",
       "備考": "HAVOC発生時、2+C>2+C>2+CまでHACVOC継続"
    },
    "j.A": {
       "Input": "",
       "Damage": "150",
       "Hit Type": "Overhead",
       "Active On": "7",
       "Active For": "4",
       "Recovery": "14",
       "Overall": "24",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "備考": "Behaviour in air allowed after use"
    },
    "j.B": {
       "Input": "",
       "Damage": "510",
       "Hit Type": "Overhead",
       "Active On": "11",
       "Active For": "3",
       "Recovery": "15",
       "Overall": "28",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "備考": "Behaviour in air allowed after use"
    },
    "j.C": {
       "Input": "",
       "Damage": "610",
       "Hit Type": "Overhead",
       "Active On": "12",
       "Active For": "4",
       "Recovery": "20",
       "Overall": "35",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "備考": "Behaviour in air allowed after use"
    },
    "66B": {
       "Input": "",
       "Damage": "660",
       "Hit Type": "Mid",
       "Active On": "11",
       "Active For": "7",
       "Recovery": "9",
       "Overall": "26",
       "Frame Advantage": "-4",
       "Invincibility": "9～17 Foot",
       "Attribute": "",
       "備考": ""
    },
    "66C": {
       "Input": "",
       "Damage": "980",
       "Hit Type": "Mid",
       "Active On": "17",
       "Active For": "15",
       "Recovery": "18",
       "Overall": "49",
       "Frame Advantage": "-15",
       "Invincibility": "6～31 Foot",
       "Attribute": "",
       "備考": ""
    },
    "6C": {
       "Input": "",
       "Damage": "720",
       "Hit Type": "Mid",
       "Active On": "18",
       "Active For": "4",
       "Recovery": "24",
       "Overall": "45",
       "Frame Advantage": "-4",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "6[C]": {
       "Input": "",
       "Damage": "900",
       "Hit Type": "Overhead",
       "Active On": "27",
       "Active For": "4",
       "Recovery": "29",
       "Overall": "59",
       "Frame Advantage": "-10",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "3C": {
       "Input": "",
       "Damage": "640",
       "Hit Type": "Mid",
       "Active On": "15",
       "Active For": "4",
       "Recovery": "27",
       "Overall": "45",
       "Frame Advantage": "-13",
       "Invincibility": "4～14 Projectile / 8～18 Head",
       "Attribute": "",
       "備考": ""
    },
    "3[C]": {
       "Input": "",
       "Damage": "690",
       "Hit Type": "Mid",
       "Active On": "30",
       "Active For": "4",
       "Recovery": "29",
       "Overall": "62",
       "Frame Advantage": "-15",
       "Invincibility": "4～29 Projectile / 8～33 Head",
       "Attribute": "",
       "備考": ""
    },
    "4C": {
       "Input": "",
       "Damage": "710",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "11",
       "Active For": "5",
       "Recovery": "25",
       "Overall": "40",
       "Frame Advantage": "-12",
       "Invincibility": "7～15 Head",
       "Attribute": "",
       "備考": "11～15弾属性相殺判定あり"
    },
    "j.CC": {
       "Input": "",
       "Damage": "480",
       "Hit Type": "Mid",
       "Active On": "11",
       "Active For": "3",
       "Recovery": "27",
       "Overall": "40",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "備考": "動作後は空中で行動可"
    },
    "5BB": {
       "Input": "",
       "Damage": "900",
       "Hit Type": "Mid",
       "Active On": "11",
       "Active For": "4",
       "Recovery": "15",
       "Overall": "29",
       "Frame Advantage": "-3",
       "Invincibility": "1～14 Foot",
       "Attribute": "",
       "備考": ""
    },
    "5BBB": {
       "Input": "",
       "Damage": "1100",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "11",
       "Active For": "3",
       "Recovery": "23",
       "Overall": "36",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "5BBBC": {
       "Input": "",
       "Damage": "690",
       "Hit Type": "Mid",
       "Active On": "11",
       "Active For": "4",
       "Recovery": "30",
       "Overall": "44",
       "Frame Advantage": "-16",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "5CC": {
       "Input": "",
       "Damage": "900",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "11",
       "Active For": "2",
       "Recovery": "29",
       "Overall": "41",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "5CCC": {
       "Input": "",
       "Damage": "1400",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "4",
       "Recovery": "26",
       "Overall": "44",
       "Frame Advantage": "-12",
       "Invincibility": "",
       "Attribute": "",
       "備考": "ヒット時GRD0.5個吸収"
    },
    "2CC": {
       "Input": "",
       "Damage": "900",
       "Hit Type": "Mid",
       "Active On": "7",
       "Active For": "4",
       "Recovery": "25",
       "Overall": "35",
       "Frame Advantage": "-11",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "2CCC": {
       "Input": "",
       "Damage": "1200",
       "Hit Type": "Mid",
       "Active On": "20",
       "Active For": "5",
       "Recovery": "25",
       "Overall": "49",
       "Frame Advantage": "-10",
       "Invincibility": "",
       "Attribute": "",
       "備考": "ヒット時GRD0.5個吸収"
    },
    "FF": {
       "Input": "B+C",
       "Damage": "1372(Normal Hit)/\n1893(HAVOC)",
       "Hit Type": "Low/Mid",
       "Active On": "10",
       "Active For": "2(4)2(5)2(6)2",
       "Recovery": "42",
       "Overall": "74",
       "Frame Advantage": "-32",
       "Invincibility": "8～17 Head",
       "Attribute": "",
       "備考": "HAVOC発生時はヒット数増加\nダメージはHAVOC効果込みのもの"
    },
    "Throw": {
       "Input": "A+D",
       "Damage": "1610",
       "Hit Type": "Throw",
       "Active On": "4",
       "Active For": "1",
       "Recovery": "22",
       "Overall": "26",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Throw",
       "備考": "投げ無敵時金投げ"
    },
    "236A": {
       "Input": "↓↘→+A",
       "Damage": "500",
       "Hit Type": "Mid",
       "Active On": "11",
       "Active For": "5",
       "Recovery": "20",
       "Overall": "35",
       "Frame Advantage": "-7",
       "Invincibility": "",
       "Attribute": "",
       "備考": "HAVOC発生時、参之戒：穿と参之戒(裏)：烈までHAVOC継続"
    },
    "236B": {
       "Input": "↓↘→+B",
       "Damage": "500",
       "Hit Type": "Mid",
       "Active On": "14",
       "Active For": "5",
       "Recovery": "20",
       "Overall": "38",
       "Frame Advantage": "-7",
       "Invincibility": "",
       "Attribute": "",
       "備考": "HAVOC発生時、参之戒：穿と参之戒(裏)：烈までHAVOC継続"
    },
    "236[B]": {
       "Input": "↓↘→+B",
       "Damage": "1400",
       "Hit Type": "Mid",
       "Active On": "21",
       "Active For": "5",
       "Recovery": "23",
       "Overall": "48",
       "Frame Advantage": "-10",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "236C": {
       "Input": "↓↘→+C",
       "Damage": "1971",
       "Hit Type": "Mid",
       "Active On": "8",
       "Active For": "8",
       "Recovery": "36",
       "Overall": "51",
       "Frame Advantage": "-13",
       "Invincibility": "1～3 Throw / 3～15 Projectile",
       "Attribute": "",
       "備考": ""
    },
    "236XA": {
       "Input": "→+A",
       "Damage": "900",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "11",
       "Active For": "2",
       "Recovery": "29",
       "Overall": "41",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "236XB": {
       "Input": "→+BorC",
       "Damage": "1250",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "16",
       "Active For": "12(6)8",
       "Recovery": "34",
       "Overall": "75",
       "Frame Advantage": "-24",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "236XXA": {
       "Input": "→+A",
       "Damage": "900",
       "Hit Type": "Low (Air Blockable)",
       "Active On": "12",
       "Active For": "2",
       "Recovery": "24",
       "Overall": "37",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "236XXB": {
       "Input": "→+BorC",
       "Damage": "1100",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "4",
       "Recovery": "38",
       "Overall": "53",
       "Frame Advantage": "-24",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "623A": {
       "Input": "→↓↘+A",
       "Damage": "1402",
       "Hit Type": "Mid",
       "Active On": "7",
       "Active For": "4(8)4",
       "Recovery": "26",
       "Overall": "48",
       "Frame Advantage": "-12",
       "Invincibility": "5～22 Head / 5～22 Dive",
       "Attribute": "",
       "備考": ""
    },
    "623B": {
       "Input": "→↓↘+B",
       "Damage": "1550",
       "Hit Type": "Mid",
       "Active On": "8",
       "Active For": "4(8)4",
       "Recovery": "26",
       "Overall": "49",
       "Frame Advantage": "-12",
       "Invincibility": "6～23 Head / 6～23 Dive",
       "Attribute": "",
       "備考": ""
    },
    "623C": {
       "Input": "→↓↘+C",
       "Damage": "1812",
       "Hit Type": "Mid",
       "Active On": "7",
       "Active For": "4(10)3(13)3",
       "Recovery": "23",
       "Overall": "62",
       "Frame Advantage": "-8",
       "Invincibility": "1～6 All / 7～10 Strike",
       "Attribute": "",
       "備考": ""
    },
    "214A": {
       "Input": "↓↙←+A",
       "Damage": "",
       "Hit Type": "",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "31",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "",
       "備考": "5～23当身投げ判定"
    },
    "214A (Hit)": {
       "Input": "↓↙←+A",
       "Damage": "1015(Mid・Overhead)/\n710(Low)",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "3",
       "Active For": "1",
       "Recovery": "30",
       "Overall": "33",
       "Frame Advantage": "-13",
       "Invincibility": "1～33 Strike",
       "Attribute": "",
       "備考": "\nダメージは上・中段判定の技と下段判定の攻撃を受け止めた時で変化"
    },
    "214B": {
       "Input": "↓↙←+B",
       "Damage": "",
       "Hit Type": "",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "39",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "",
       "備考": "7～16当身投げ判定"
    },
    "214B (Hit)": {
       "Input": "↓↙←+B",
       "Damage": "1319(Mid・Overhead)/\n1294(Low)",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "3",
       "Active For": "1",
       "Recovery": "30",
       "Overall": "33",
       "Frame Advantage": "-13",
       "Invincibility": "1～33 Strike",
       "Attribute": "",
       "備考": "\nダメージは上・中段判定の技と下段判定の攻撃を受け止めた時で変化"
    },
    "214C": {
       "Input": "↓↙←+C",
       "Damage": "",
       "Hit Type": "",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "57",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "",
       "備考": "1～27当身投げ判定"
    },
    "214C (CS)": {
       "Input": "↓↙←+C",
       "Damage": "2022",
       "Hit Type": "Mid",
       "Active On": "3",
       "Active For": "4",
       "Recovery": "24",
       "Overall": "30",
       "Frame Advantage": "-6",
       "Invincibility": "1～着地後11まで打撃",
       "Attribute": "",
       "備考": "チェインシフト後に攻撃を受け止めた場合のもの"
    },
    "214C (Parried Mid)": {
       "Input": "↓↙←+C",
       "Damage": "1500",
       "Hit Type": "Mid",
       "Active On": "5",
       "Active For": "4",
       "Recovery": "23",
       "Overall": "31",
       "Frame Advantage": "-6",
       "Invincibility": "1～着地まで打撃",
       "Attribute": "",
       "備考": "上・中段判定の攻撃を受け止めた場合のもの"
    },
    "214C (Parried Low)": {
       "Input": "↓↙←+C",
       "Damage": "1226",
       "Hit Type": "Mid",
       "Active On": "5",
       "Active For": "4",
       "Recovery": "23",
       "Overall": "31",
       "Frame Advantage": "-3",
       "Invincibility": "1～着地まで打撃",
       "Attribute": "",
       "備考": "下段判定の攻撃を受け止めた場合のもの"
    },
    "22A": {
       "Input": "↓↓+A",
       "Damage": "550",
       "Hit Type": "Mid",
       "Active On": "17",
       "Active For": "6",
       "Recovery": "22",
       "Overall": "44",
       "Frame Advantage": "-3",
       "Invincibility": "^ unsure about these ones, its strke invuln but idk how long it lasts.",
       "Attribute": "",
       "備考": ""
    },
    "22B": {
       "Input": "↓↓+B",
       "Damage": "650",
       "Hit Type": "Mid",
       "Active On": "26",
       "Active For": "6",
       "Recovery": "19",
       "Overall": "50",
       "Frame Advantage": "±0",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "22C": {
       "Input": "↓↓+C",
       "Damage": "1308",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "9",
       "Active For": "15",
       "Recovery": "20",
       "Overall": "43",
       "Frame Advantage": "+4",
       "Invincibility": "1～3 Throw",
       "Attribute": "",
       "備考": ""
    },
    "j.236A": {
       "Input": "空中↓↘→+A",
       "Damage": "850",
       "Hit Type": "Mid",
       "Active On": "13",
       "Active For": "Until Landing",
       "Recovery": "16 Upon Landing",
       "Overall": "-",
       "Frame Advantage": "-4",
       "Invincibility": "",
       "Attribute": "空突",
       "備考": "硬直差は密着でジャンプの昇りから最速で出してガードさせた場合のもの"
    },
    "j.236B": {
       "Input": "空中↓↘→+B",
       "Damage": "850",
       "Hit Type": "Mid",
       "Active On": "15",
       "Active For": "Until Landing",
       "Recovery": "16 Upon Landing",
       "Overall": "-",
       "Frame Advantage": "-4",
       "Invincibility": "",
       "Attribute": "空突",
       "備考": "硬直差は密着でジャンプの昇りから最速で出してガードさせた場合のもの"
    },
    "j.236C": {
       "Input": "空中↓↘→+C",
       "Damage": "1400",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "Until Landing",
       "Recovery": "16 Upon Landing",
       "Overall": "-",
       "Frame Advantage": "-3",
       "Invincibility": "1～3 Throw",
       "Attribute": "空突",
       "備考": "硬直差は密着でジャンプの昇りから最速で出してガードさせた場合のもの"
    },
    "IW": {
       "Input": "←↙↓↘→+D",
       "Damage": "3160(Point blank hit)/\n2112(Projectile hit)",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "8",
       "Active For": "1(初段のみ)",
       "Recovery": "51",
       "Overall": "59",
       "Frame Advantage": "-17",
       "Invincibility": "1～12 All / 13～31Throw",
       "Attribute": "",
       "備考": "硬直差は密着でガードさせた場合のもの"
    },
    "IWEXS": {
       "Input": "A+B+C+D",
       "Damage": "3750",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "6",
       "Recovery": "47",
       "Overall": "67",
       "Frame Advantage": "-25",
       "Invincibility": "1～26 All",
       "Attribute": "",
       "備考": ""
    }
 }