export default {
    "5A": {
       "Input": "",
       "Damage": "180",
       "Hit Type": "Low",
       "Active On": "6",
       "Active For": "2",
       "Recovery": "12",
       "Overall": "19",
       "Frame Advantage": "-1",
       "Invincibility": "",
       "Attribute": "Foot",
       "備考": ""
    },
    "5B": {
       "Input": "",
       "Damage": "510",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "4",
       "Recovery": "17",
       "Overall": "29",
       "Frame Advantage": "±0",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "5C": {
       "Input": "",
       "Damage": "690",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "16",
       "Active For": "6",
       "Recovery": "38",
       "Overall": "59",
       "Frame Advantage": "-26",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "5[C]": {
       "Input": "",
       "Damage": "950",
       "Hit Type": "Overhead",
       "Active On": "30",
       "Active For": "6",
       "Recovery": "37",
       "Overall": "72",
       "Frame Advantage": "-25",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "2A": {
       "Input": "",
       "Damage": "160",
       "Hit Type": "Mid",
       "Active On": "7",
       "Active For": "2",
       "Recovery": "13",
       "Overall": "21",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "2B": {
       "Input": "",
       "Damage": "490",
       "Hit Type": "Low",
       "Active On": "8",
       "Active For": "3",
       "Recovery": "17",
       "Overall": "27",
       "Frame Advantage": "-4",
       "Invincibility": "",
       "Attribute": "Foot",
       "備考": ""
    },
    "2C": {
       "Input": "",
       "Damage": "744",
       "Hit Type": "Low / Mid",
       "Active On": "8",
       "Active For": "3(5)6",
       "Recovery": "22",
       "Overall": "43",
       "Frame Advantage": "-10",
       "Invincibility": "14～18 Head",
       "Attribute": "Foot (First Hit)",
       "備考": ""
    },
    "j.A": {
       "Input": "",
       "Damage": "140",
       "Hit Type": "Overhead",
       "Active On": "8",
       "Active For": "4",
       "Recovery": "13",
       "Overall": "24",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "備考": "Behaviour in air allowed after use"
    },
    "j.B": {
       "Input": "",
       "Damage": "582",
       "Hit Type": "Overhead / Overhead",
       "Active On": "8",
       "Active For": "2(8)6",
       "Recovery": "23",
       "Overall": "45",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "備考": "初段ガード後は上段\n動作後は空中で行動可"
    },
    "j.C": {
       "Input": "",
       "Damage": "610",
       "Hit Type": "Overhead",
       "Active On": "13",
       "Active For": "4",
       "Recovery": "72",
       "Overall": "88",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "備考": "Behaviour in air allowed after use"
    },
    "j.[C]": {
       "Input": "",
       "Damage": "750",
       "Hit Type": "Overhead",
       "Active On": "21",
       "Active For": "5",
       "Recovery": "64",
       "Overall": "96",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "備考": "Behaviour in air allowed after use"
    },
    "66B": {
       "Input": "",
       "Damage": "660",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "2",
       "Recovery": "12",
       "Overall": "23",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "66C": {
       "Input": "",
       "Damage": "980",
       "Hit Type": "Mid",
       "Active On": "11",
       "Active For": "12",
       "Recovery": "12",
       "Overall": "34",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "6B": {
       "Input": "",
       "Damage": "720",
       "Hit Type": "Overhead",
       "Active On": "27",
       "Active For": "5",
       "Recovery": "16",
       "Overall": "47",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "4B": {
       "Input": "",
       "Damage": "520",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "2",
       "Recovery": "16",
       "Overall": "27",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "3C": {
       "Input": "",
       "Damage": "610",
       "Hit Type": "Low",
       "Active On": "11",
       "Active For": "10",
       "Recovery": "13",
       "Overall": "33",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attribute": "Foot",
       "備考": ""
    },
    "3[C}": {
       "Input": "",
       "Damage": "710",
       "Hit Type": "Low",
       "Active On": "17",
       "Active For": "10",
       "Recovery": "15",
       "Overall": "41",
       "Frame Advantage": "-7",
       "Invincibility": "",
       "Attribute": "Foot",
       "備考": ""
    },
    "FF": {
       "Input": "B+C",
       "Damage": "1221",
       "Hit Type": "Mid",
       "Active On": "21",
       "Active For": "4",
       "Recovery": "24",
       "Overall": "48",
       "Frame Advantage": "+1",
       "Invincibility": "10～26 Head",
       "Attribute": "Projectile",
       "備考": ""
    },
    "FF (Vorpal)": {
       "Input": "B+C",
       "Damage": "1527",
       "Hit Type": "Mid",
       "Active On": "18",
       "Active For": "4",
       "Recovery": "24",
       "Overall": "45",
       "Frame Advantage": "+1",
       "Invincibility": "8～23 Head",
       "Attribute": "Projectile",
       "備考": ""
    },
    "Throw": {
       "Input": "A+D",
       "Damage": "1510\n(1450)",
       "Hit Type": "Throw",
       "Active On": "4",
       "Active For": "1",
       "Recovery": "22",
       "Overall": "26",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Throw",
       "備考": "追撃可\n()内のダメージは追加入力をした場合のもの\n投げ無敵時金投げ"
    },
    "236A": {
       "Input": "↓↘→+A",
       "Damage": "1434",
       "Hit Type": "Mid/Mid(Air Blockable)",
       "Active On": "16",
       "Active For": "4(4)6",
       "Recovery": "15",
       "Overall": "44",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "236B": {
       "Input": "↓↘→+B",
       "Damage": "1434",
       "Hit Type": "Mid/Mid(Air Blockable)",
       "Active On": "22",
       "Active For": "4(4)6",
       "Recovery": "17",
       "Overall": "52",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "236C": {
       "Input": "↓↘→+C",
       "Damage": "2039",
       "Hit Type": "Mid/Mid(Air Blockable)",
       "Active On": "14",
       "Active For": "2(4)3",
       "Recovery": "27",
       "Overall": "49",
       "Frame Advantage": "+5",
       "Invincibility": "1～3 Throw",
       "Attribute": "",
       "備考": ""
    },
    "236XX": {
       "Input": "→+AorBorC",
       "Damage": "850",
       "Hit Type": "Mid(Air Blockable)",
       "Active On": "9",
       "Active For": "2",
       "Recovery": "27",
       "Overall": "37",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "236XXX": {
       "Input": "→+AorBorC",
       "Damage": "1600",
       "Hit Type": "Throw",
       "Active On": "16",
       "Active For": "4",
       "Recovery": "30",
       "Overall": "49",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Throw",
       "備考": "持続1フレーム目は連続技中の相手にのみヒットする\n投げ無敵時金投げ"
    },
    "623A": {
       "Input": "→↓↘+A",
       "Damage": "1345",
       "Hit Type": "Mid",
       "Active On": "15",
       "Active For": "6(9)3",
       "Recovery": "19",
       "Overall": "51",
       "Frame Advantage": "-6",
       "Invincibility": "15～16 Head/13～16 Dive",
       "Attribute": "",
       "備考": ""
    },
    "623B": {
       "Input": "→↓↘+B",
       "Damage": "1415",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "6(9)3",
       "Recovery": "28",
       "Overall": "54",
       "Frame Advantage": "-15",
       "Invincibility": "9～10 Head / 7～10 Dive",
       "Attribute": "",
       "備考": ""
    },
    "623C": {
       "Input": "→↓↘+C",
       "Damage": "1851",
       "Hit Type": "Mid",
       "Active On": "7",
       "Active For": "6(9)3(10)6(9)4",
       "Recovery": "32",
       "Overall": "85",
       "Frame Advantage": "-18",
       "Invincibility": "1～8 All",
       "Attribute": "",
       "備考": ""
    },
    "214A": {
       "Input": "↓↙←+A",
       "Damage": "1200",
       "Hit Type": "Throw",
       "Active On": "11",
       "Active For": "2",
       "Recovery": "27",
       "Overall": "39",
       "Frame Advantage": "-",
       "Invincibility": "1～12 Throw",
       "Attribute": "Throw",
       "備考": "持続1フレーム目は連続技中の相手にのみヒットする。投げ無敵無効(金)"
    },
    "214B": {
       "Input": "↓↙←+B",
       "Damage": "1500",
       "Hit Type": "Throw",
       "Active On": "8",
       "Active For": "5",
       "Recovery": "23",
       "Overall": "35",
       "Frame Advantage": "-",
       "Invincibility": "6～12 Head・Dive",
       "Attribute": "Throw",
       "備考": "地上の相手には当たらない。投げ無敵無効"
    },
    "214C": {
       "Input": "↓↙←+C",
       "Damage": "1600",
       "Hit Type": "Throw",
       "Active On": "12",
       "Active For": "2",
       "Recovery": "25",
       "Overall": "38",
       "Frame Advantage": "-",
       "Invincibility": "1～13 All",
       "Attribute": "Throw",
       "備考": "持続1フレーム目は連続技中の相手にのみヒットする\n投げ無敵時金投げ"
    },
    "22A": {
       "Input": "↓↓+A",
       "Damage": "550",
       "Hit Type": "Mid",
       "Active On": "21",
       "Active For": "3",
       "Recovery": "15",
       "Overall": "38",
       "Frame Advantage": "+7",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "22B": {
       "Input": "↓↓+B",
       "Damage": "1484",
       "Hit Type": "Mid/Mid/Overhead",
       "Active On": "14",
       "Active For": "4(12)17(11)5",
       "Recovery": "34",
       "Overall": "96",
       "Frame Advantage": "-9",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "22C": {
       "Input": "↓↓+C",
       "Damage": "2005",
       "Hit Type": "Mid/Mid/Overhead",
       "Active On": "9",
       "Active For": "5(20)42(11)6",
       "Recovery": "35",
       "Overall": "127",
       "Frame Advantage": "-23",
       "Invincibility": "1～28 All",
       "Attribute": "",
       "備考": ""
    },
    "j.236A": {
       "Input": "空中↓↘→+A",
       "Damage": "1575",
       "Hit Type": "Mid",
       "Active On": "7",
       "Active For": "2(10)8",
       "Recovery": "9 Upon Landing",
       "Overall": "43",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Attribute": "",
       "備考": "硬直差はジャンプの昇りから最速で出して立ち状態のハイドにガードさせた場合のもの"
    },
    "j.236B": {
       "Input": "空中↓↘→+B",
       "Damage": "1575",
       "Hit Type": "Mid",
       "Active On": "7",
       "Active For": "2(10)8",
       "Recovery": "9 Upon Landing",
       "Overall": "49",
       "Frame Advantage": "-14",
       "Invincibility": "",
       "Attribute": "",
       "備考": "硬直差はジャンプの昇りから最速で出して立ち状態のハイドにガードさせた場合のもの"
    },
    "j.236C": {
       "Input": "空中↓↘→+C",
       "Damage": "2022",
       "Hit Type": "Mid",
       "Active On": "14",
       "Active For": "9",
       "Recovery": "9 Upon Landing",
       "Overall": "40",
       "Frame Advantage": "+8",
       "Invincibility": "",
       "Attribute": "",
       "備考": "硬直差はジャンプの昇りから最速で出して立ち状態のハイドにガードさせた場合のもの"
    },
    "j.214A": {
       "Input": "空中↓↙←+A",
       "Damage": "625",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "12",
       "Active For": "17",
       "Recovery": "9 Upon Landing",
       "Overall": "41",
       "Frame Advantage": "+1",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "j.214B": {
       "Input": "空中↓↙←+B",
       "Damage": "1170",
       "Hit Type": "Mid (Air Blockable)/Overhead (Air Blockable)",
       "Active On": "13",
       "Active For": "12(着地後3まで)3",
       "Recovery": "28",
       "Overall": "65",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "j.214C": {
       "Input": "空中↓↙←+C",
       "Damage": "1353",
       "Hit Type": "Mid (Air Blockable)/Overhead (Air Blockable)",
       "Active On": "12",
       "Active For": "36(着地後3まで)5",
       "Recovery": "34",
       "Overall": "94",
       "Frame Advantage": "-21",
       "Invincibility": "",
       "Attribute": "",
       "備考": "ダメージは7ヒット時のもの"
    },
    "IW": {
       "Input": "←↙↓↘→+D",
       "Damage": "3095",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "13",
       "Active For": "3(12)3(11)4(15)6(24)5(8)3(3)3(3)3(6)3",
       "Recovery": "19",
       "Overall": "157",
       "Frame Advantage": "-4",
       "Invincibility": "1～27 All /28～31 Throw",
       "Attribute": "",
       "備考": ""
    },
    "IWEXS": {
       "Input": "A+B+C+D",
       "Damage": "3820",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "6",
       "Recovery": "47",
       "Overall": "67",
       "Frame Advantage": "-25",
       "Invincibility": "1～26 All",
       "Attribute": "",
       "備考": ""
    }
 }