module.exports = {
    "5A": {
       "Input": "",
       "Damage": "170",
       "Hit Type": "Mid",
       "Active On": "8",
       "Active For": "2",
       "Recovery": "13",
       "Overall": "22",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "5B": {
       "Input": "",
       "Damage": "410",
       "Hit Type": "Mid",
       "Active On": "11",
       "Active For": "3",
       "Recovery": "29",
       "Overall": "42",
       "Frame Advantage": "-16",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "5C": {
       "Input": "",
       "Damage": "510",
       "Hit Type": "Mid",
       "Active On": "15",
       "Active For": "3",
       "Recovery": "38",
       "Overall": "55",
       "Frame Advantage": "-23",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "5[C]": {
       "Input": "",
       "Damage": "1200",
       "Hit Type": "Overhead",
       "Active On": "36",
       "Active For": "15",
       "Recovery": "38",
       "Overall": "88",
       "Frame Advantage": "-16",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "初段ガード後は上段"
    },
    "2A": {
       "Input": "",
       "Damage": "120",
       "Hit Type": "Low",
       "Active On": "6",
       "Active For": "2",
       "Recovery": "13",
       "Overall": "20",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attribute": "Foot",
       "Notes": ""
    },
    "2B": {
       "Input": "",
       "Damage": "420",
       "Hit Type": "Mid",
       "Active On": "13",
       "Active For": "4",
       "Recovery": "22",
       "Overall": "38",
       "Frame Advantage": "-10",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "2C": {
       "Input": "",
       "Damage": "490",
       "Hit Type": "Mid",
       "Active On": "14",
       "Active For": "3",
       "Recovery": "29",
       "Overall": "45",
       "Frame Advantage": "-14",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "j.A": {
       "Input": "",
       "Damage": "140",
       "Hit Type": "Overhead",
       "Active On": "8",
       "Active For": "2",
       "Recovery": "19",
       "Overall": "28",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.B": {
       "Input": "",
       "Damage": "380",
       "Hit Type": "Overhead",
       "Active On": "10",
       "Active For": "3",
       "Recovery": "24",
       "Overall": "36",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.C": {
       "Input": "",
       "Damage": "440",
       "Hit Type": "Overhead",
       "Active On": "16",
       "Active For": "5",
       "Recovery": "16",
       "Overall": "36",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.[C]": {
       "Input": "",
       "Damage": "855",
       "Hit Type": "Overhead",
       "Active On": "21",
       "Active For": "4(8)7",
       "Recovery": "19",
       "Overall": "58",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "初段ガード後は上段\nBehaviour in air allowed after use"
    },
    "66B": {
       "Input": "",
       "Damage": "910",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "11",
       "Recovery": "32",
       "Overall": "51",
       "Frame Advantage": "-11",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "66C": {
       "Input": "",
       "Damage": "981",
       "Hit Type": "Mid",
       "Active On": "13",
       "Active For": "11",
       "Recovery": "32",
       "Overall": "52",
       "Frame Advantage": "-11",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "3B": {
       "Input": "",
       "Damage": "444",
       "Hit Type": "Mid",
       "Active On": "11",
       "Active For": "2",
       "Recovery": "23",
       "Overall": "35",
       "Frame Advantage": "-7",
       "Invincibility": "8～12 Head",
       "Attribute": "",
       "Notes": ""
    },
    "3C": {
       "Input": "",
       "Damage": "490",
       "Hit Type": "Mid",
       "Active On": "11",
       "Active For": "3",
       "Recovery": "21",
       "Overall": "34",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "j.2C": {
       "Input": "",
       "Damage": "880",
       "Hit Type": "Mid",
       "Active On": "15",
       "Active For": "1",
       "Recovery": "10",
       "Overall": "25",
       "Frame Advantage": "+1",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": ""
    },
    "5BB": {
       "Input": "",
       "Damage": "910",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "8",
       "Recovery": "32",
       "Overall": "51",
       "Frame Advantage": "-11",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "5CC": {
       "Input": "",
       "Damage": "420",
       "Hit Type": "Mid",
       "Active On": "24",
       "Active For": "1",
       "Recovery": "24",
       "Overall": "48",
       "Frame Advantage": "±0",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "2CC": {
       "Input": "",
       "Damage": "420",
       "Hit Type": "Low",
       "Active On": "16",
       "Active For": "3",
       "Recovery": "32",
       "Overall": "50",
       "Frame Advantage": "-12",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "3CC": {
       "Input": "",
       "Damage": "420",
       "Hit Type": "Mid",
       "Active On": "16",
       "Active For": "3",
       "Recovery": "32",
       "Overall": "50",
       "Frame Advantage": "-12",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "j.CC": {
       "Input": "",
       "Damage": "420",
       "Hit Type": "Mid",
       "Active On": "15",
       "Active For": "4",
       "Recovery": "22",
       "Overall": "40",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "Behaviour in air allowed after use"
    },
    "FF": {
       "Input": "B+C",
       "Damage": "1156",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "9",
       "Recovery": "28",
       "Overall": "51",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "[FF]": {
       "Input": "B+C",
       "Damage": "1156",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "24",
       "Active For": "12",
       "Recovery": "42",
       "Overall": "77",
       "Frame Advantage": "-21",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "j.FF": {
       "Input": "空中B+C",
       "Damage": "1156",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "9",
       "Recovery": "10 Upon Landing",
       "Overall": "-",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "j.[FF]": {
       "Input": "空中B+C",
       "Damage": "1156",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "24",
       "Active For": "12",
       "Recovery": "12 Upon Landing",
       "Overall": "-",
       "Frame Advantage": "-23",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "FF~A": {
       "Input": "A",
       "Damage": "700",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "7",
       "Active For": "2",
       "Recovery": "6 Upon Landing",
       "Overall": "-",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "ヒットorガード時は着地硬直0\n硬直差は最低空で出してガードさせた場合のもの"
    },
    "FF~2A": {
       "Input": "↓+A",
       "Damage": "700",
       "Hit Type": "Overhead",
       "Active On": "17",
       "Active For": "3",
       "Recovery": "8 Upon Landing",
       "Overall": "-",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "硬直差は最低空で出してガードさせた場合のもの"
    },
    "Throw": {
       "Input": "A+D",
       "Damage": "1605",
       "Hit Type": "Throw",
       "Active On": "4",
       "Active For": "1",
       "Recovery": "22",
       "Overall": "26",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Throw",
       "Notes": "投げ無敵時金投げ"
    },
    "236A": {
       "Input": "↓↘→+A",
       "Damage": "880",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "17",
       "Active For": "8",
       "Recovery": "24",
       "Overall": "48",
       "Frame Advantage": "-10",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "しゃがみには当たらない"
    },
    "236B": {
       "Input": "↓↘→+B",
       "Damage": "880",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "39",
       "Active For": "8",
       "Recovery": "8",
       "Overall": "54",
       "Frame Advantage": "+6",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "しゃがみには当たらない"
    },
    "236C": {
       "Input": "↓↘→+C",
       "Damage": "1520",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "14",
       "Active For": "8",
       "Recovery": "25",
       "Overall": "46",
       "Frame Advantage": "-4",
       "Invincibility": "1～3 Throw",
       "Attribute": "Projectile",
       "Notes": ""
    },
    "j.236A": {
       "Input": "空中↓↘→+A",
       "Damage": "880",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "19",
       "Active For": "8",
       "Recovery": "2 Upon Landing",
       "Overall": "51",
       "Frame Advantage": "-9",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "j.236B": {
       "Input": "空中↓↘→+B",
       "Damage": "880",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "35",
       "Active For": "8",
       "Recovery": "2 Upon Landing",
       "Overall": "53",
       "Frame Advantage": "+5",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "j.236C": {
       "Input": "空中↓↘→+C",
       "Damage": "1520",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "11",
       "Active For": "8",
       "Recovery": "2 Upon Landing",
       "Overall": "35",
       "Frame Advantage": "+4",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "623A": {
       "Input": "→↓↘+A",
       "Damage": "720",
       "Hit Type": "Mid",
       "Active On": "15",
       "Active For": "3",
       "Recovery": "21",
       "Overall": "38",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "623B": {
       "Input": "→↓↘+B",
       "Damage": "910",
       "Hit Type": "Mid",
       "Active On": "37",
       "Active For": "3",
       "Recovery": "9",
       "Overall": "48",
       "Frame Advantage": "+13",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "623C": {
       "Input": "→↓↘+C",
       "Damage": "1390",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "3",
       "Recovery": "19",
       "Overall": "33",
       "Frame Advantage": "-3",
       "Invincibility": "1～3 Throw",
       "Attribute": "",
       "Notes": ""
    },
    "214A": {
       "Input": "↓↙←+A",
       "Damage": "1904",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "82",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "57",
       "Frame Advantage": "+74",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "ダメージは8ヒット時のもの"
    },
    "214B": {
       "Input": "↓↙←+B",
       "Damage": "2486",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "86",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "69",
       "Frame Advantage": "+71",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "ダメージは11ヒット時のもの"
    },
    "214C": {
       "Input": "↓↙←+C",
       "Damage": "2379",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "77",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "34",
       "Frame Advantage": "+130",
       "Invincibility": "1～3 Throw",
       "Attribute": "Projectile",
       "Notes": "ダメージは15ヒット時のもの"
    },
    "j.214A": {
       "Input": "空中↓↙←+A",
       "Damage": "1904",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "82",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "51",
       "Frame Advantage": "-9",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "ダメージは8ヒット時のもの"
    },
    "j.214B": {
       "Input": "空中↓↙←+B",
       "Damage": "2486",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "86",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "64",
       "Frame Advantage": "+5",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "ダメージは11ヒット時のもの"
    },
    "j.214C": {
       "Input": "空中↓↙←+C",
       "Damage": "2379",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "77",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "50",
       "Frame Advantage": "+4",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "ダメージは15ヒット時のもの"
    },
    "421A": {
       "Input": "←↓↙+A",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "4 Upon Landing",
       "Overall": "49",
       "Frame Advantage": "-",
       "Invincibility": "7～12 Head・Projectile・Dive / 13～18 Strike / 19～20 All",
       "Attribute": "",
       "Notes": ""
    },
    "421B": {
       "Input": "←↓↙+B",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "0 Upon Landing",
       "Overall": "40",
       "Frame Advantage": "-",
       "Invincibility": "9～14 Head・Projectile・Dive / 15～21 Strike / 22～23 Throw",
       "Attribute": "",
       "Notes": "41Fから空中で行動可"
    },
    "421C": {
       "Input": "←↓↙+C",
       "Damage": "1983",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "43",
       "Active For": "-",
       "Recovery": "20 Upon Landing",
       "Overall": "74",
       "Frame Advantage": "+13",
       "Invincibility": "9～14 Head・Projectile・Dive / 15～21 Strike",
       "Attribute": "Projectile",
       "Notes": "ダメージは13ヒット時のもの\n硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "j.421A": {
       "Input": "空中←↓↙+A",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "4 Upon Landing",
       "Overall": "49",
       "Frame Advantage": "-",
       "Invincibility": "7～12 Head・Projectile・Dive/13～20 All",
       "Attribute": "",
       "Notes": ""
    },
    "j.421B": {
       "Input": "空中←↓↙+B",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "0 Upon Landing",
       "Overall": "21",
       "Frame Advantage": "-",
       "Invincibility": "9～14 Head・Projectile・Dive/15～23 Throw",
       "Attribute": "",
       "Notes": "41Fから空中で行動可"
    },
    "j.421C": {
       "Input": "空中←↓↙+C",
       "Damage": "1983",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "41",
       "Active For": "-",
       "Recovery": "20 Upon Landing",
       "Overall": "71",
       "Frame Advantage": "+13",
       "Invincibility": "7～12 Head・Projectile・Dive/13～18 All",
       "Attribute": "Projectile",
       "Notes": "ダメージは13ヒット時のもの\n硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "{A} (L1)": {
       "Input": "Aタメて離す",
       "Damage": "660",
       "Hit Type": "Overhead",
       "Active On": "18",
       "Active For": "17",
       "Recovery": "-",
       "Overall": "51",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "屈相手には29Fにヒット。硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "{A} (L2)": {
       "Input": "Aタメて離す",
       "Damage": "770",
       "Hit Type": "Overhead",
       "Active On": "16",
       "Active For": "17",
       "Recovery": "-",
       "Overall": "49",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "屈相手には27Fにヒット。硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "{A} (L3)": {
       "Input": "Aタメて離す",
       "Damage": "880",
       "Hit Type": "Overhead",
       "Active On": "15",
       "Active For": "17",
       "Recovery": "-",
       "Overall": "48",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "屈相手には26Fにヒット。硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "{A} (L4)": {
       "Input": "Aタメて離す",
       "Damage": "1485",
       "Hit Type": "Overhead",
       "Active On": "14",
       "Active For": "17",
       "Recovery": "-",
       "Overall": "47",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "屈相手には25Fにヒット。硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "{A} (L5)": {
       "Input": "Aタメて離す",
       "Damage": "1485×3",
       "Hit Type": "Overhead",
       "Active On": "14",
       "Active For": "17",
       "Recovery": "-",
       "Overall": "47",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "屈相手には25Fにヒット。硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "{B} (L1)": {
       "Input": "Bタメて離す",
       "Damage": "660",
       "Hit Type": "Overhead",
       "Active On": "18",
       "Active For": "17",
       "Recovery": "-",
       "Overall": "51",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "屈相手には29Fにヒット。硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "{B} (L2)": {
       "Input": "Bタメて離す",
       "Damage": "770",
       "Hit Type": "Overhead",
       "Active On": "16",
       "Active For": "17",
       "Recovery": "-",
       "Overall": "49",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "屈相手には27Fにヒット。硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "{B} (L3)": {
       "Input": "Bタメて離す",
       "Damage": "880",
       "Hit Type": "Overhead",
       "Active On": "15",
       "Active For": "17",
       "Recovery": "-",
       "Overall": "48",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "屈相手には26Fにヒット。硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "{B} (L4)": {
       "Input": "Bタメて離す",
       "Damage": "1485",
       "Hit Type": "Overhead",
       "Active On": "14",
       "Active For": "17",
       "Recovery": "-",
       "Overall": "47",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "屈相手には25Fにヒット。硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "{B} (L5)": {
       "Input": "Bタメて離す",
       "Damage": "1485×3",
       "Hit Type": "Overhead",
       "Active On": "14",
       "Active For": "17",
       "Recovery": "-",
       "Overall": "47",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "屈相手には25Fにヒット。硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "{C} (L1)": {
       "Input": "Cタメて離す",
       "Damage": "660",
       "Hit Type": "Overhead",
       "Active On": "18",
       "Active For": "17",
       "Recovery": "-",
       "Overall": "51",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "屈相手には29Fにヒット。硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "{C} (L2)": {
       "Input": "Cタメて離す",
       "Damage": "770",
       "Hit Type": "Overhead",
       "Active On": "16",
       "Active For": "17",
       "Recovery": "-",
       "Overall": "49",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "屈相手には27Fにヒット。硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "{C} (L3)": {
       "Input": "Cタメて離す",
       "Damage": "880",
       "Hit Type": "Overhead",
       "Active On": "15",
       "Active For": "17",
       "Recovery": "-",
       "Overall": "48",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "屈相手には26Fにヒット。硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "{C} (L4)": {
       "Input": "Cタメて離す",
       "Damage": "1485",
       "Hit Type": "Overhead",
       "Active On": "14",
       "Active For": "17",
       "Recovery": "-",
       "Overall": "47",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "屈相手には25Fにヒット。硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "{C} (L5)": {
       "Input": "Cタメて離す",
       "Damage": "1485×3",
       "Hit Type": "Overhead",
       "Active On": "14",
       "Active For": "17",
       "Recovery": "-",
       "Overall": "47",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "屈相手には25Fにヒット。硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "22A": {
       "Input": "↓↓+A",
       "Damage": "880",
       "Hit Type": "Low",
       "Active On": "15",
       "Active For": "3",
       "Recovery": "17",
       "Overall": "34",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "22B": {
       "Input": "↓↓+B",
       "Damage": "880",
       "Hit Type": "Low",
       "Active On": "15",
       "Active For": "3",
       "Recovery": "17",
       "Overall": "34",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "22C": {
       "Input": "↓↓+C",
       "Damage": "1880",
       "Hit Type": "Low (Air Blockable)",
       "Active On": "11",
       "Active For": "3",
       "Recovery": "27",
       "Overall": "40",
       "Frame Advantage": "-2",
       "Invincibility": "1～3 Throw",
       "Attribute": "",
       "Notes": ""
    },
    "41236C": {
       "Input": "←↙↓↘→+C",
       "Damage": "2564",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "27",
       "Active For": "12",
       "Recovery": "-",
       "Overall": "38",
       "Frame Advantage": "+16",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "ダメージは6ヒット時のもの\n硬直差は密着からガードさせた場合のもの"
    },
    "j.41236C": {
       "Input": "空中←↙↓↘→+C",
       "Damage": "3112",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "21",
       "Active For": "5",
       "Recovery": "14",
       "Overall": "58",
       "Frame Advantage": "+52",
       "Invincibility": "",
       "Attribute": "Projectile",
       "Notes": "ダメージは17ヒット時のもの\n硬直差は密着から立ち状態のハイドにガードさせた場合のもの\n動作後は空中で行動可"
    },
    "IW": {
       "Input": "←↙↓↘→+D",
       "Damage": "3087",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "12",
       "Active For": "5",
       "Recovery": "54",
       "Overall": "70",
       "Frame Advantage": "-41",
       "Invincibility": "1～16 All / 17～31 Throw",
       "Attribute": "",
       "Notes": ""
    },
    "IWEXS": {
       "Input": "A+B+C+D",
       "Damage": "3880",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "6",
       "Recovery": "47",
       "Overall": "67",
       "Frame Advantage": "-25",
       "Invincibility": "1～26 All",
       "Attribute": "",
       "Notes": ""
    }
 }