module.exports = {
    "5A": {
       "Input": "",
       "Damage": "180",
       "Hit Type": "Mid",
       "Active On": "7",
       "Active For": "3",
       "Recovery": "15",
       "Overall": "24",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "5B": {
       "Input": "",
       "Damage": "550",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "4",
       "Recovery": "18",
       "Overall": "30",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "5C": {
       "Input": "",
       "Damage": "690",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "5",
       "Recovery": "19",
       "Overall": "35",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "5[C]": {
       "Input": "",
       "Damage": "780",
       "Hit Type": "Mid",
       "Active On": "23",
       "Active For": "5",
       "Recovery": "17",
       "Overall": "44",
       "Frame Advantage": "+1",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "2A": {
       "Input": "",
       "Damage": "150",
       "Hit Type": "Low",
       "Active On": "5",
       "Active For": "2",
       "Recovery": "12",
       "Overall": "18",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "Foot",
       "備考": ""
    },
    "2B": {
       "Input": "",
       "Damage": "480",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "4",
       "Recovery": "16",
       "Overall": "29",
       "Frame Advantage": "-4",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "2C": {
       "Input": "",
       "Damage": "620",
       "Hit Type": "Low",
       "Active On": "12",
       "Active For": "5",
       "Recovery": "17",
       "Overall": "33",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attribute": "Foot",
       "備考": ""
    },
    "j.A": {
       "Input": "",
       "Damage": "155",
       "Hit Type": "Overhead / Overhead",
       "Active On": "9",
       "Active For": "10",
       "Recovery": "5",
       "Overall": "23",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "備考": "初段ガード後は上段\n動作終了後は空中で行動可能"
    },
    "j.B": {
       "Input": "",
       "Damage": "410",
       "Hit Type": "Overhead",
       "Active On": "11",
       "Active For": "2",
       "Recovery": "18",
       "Overall": "30",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "備考": "動作終了後は空中で行動可能"
    },
    "j.C": {
       "Input": "",
       "Damage": "580",
       "Hit Type": "Overhead",
       "Active On": "13",
       "Active For": "3",
       "Recovery": "19",
       "Overall": "34",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "備考": "動作終了後は空中で行動可能"
    },
    "j.[C]": {
       "Input": "",
       "Damage": "750",
       "Hit Type": "Overhead",
       "Active On": "21",
       "Active For": "3",
       "Recovery": "19",
       "Overall": "42",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "備考": "動作終了後は空中で行動可能"
    },
    "66B": {
       "Input": "",
       "Damage": "550",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "2",
       "Recovery": "12",
       "Overall": "23",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "Head",
       "備考": ""
    },
    "66C": {
       "Input": "",
       "Damage": "810",
       "Hit Type": "Mid",
       "Active On": "15",
       "Active For": "2",
       "Recovery": "26",
       "Overall": "42",
       "Frame Advantage": "-5",
       "Invincibility": "11～14 Foot",
       "Attribute": "",
       "備考": ""
    },
    "6B": {
       "Input": "",
       "Damage": "1030",
       "Hit Type": "Mid",
       "Active On": "8",
       "Active For": "2(10)2",
       "Recovery": "24",
       "Overall": "45",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "3B": {
       "Input": "",
       "Damage": "540",
       "Hit Type": "Low",
       "Active On": "9",
       "Active For": "3",
       "Recovery": "24",
       "Overall": "35",
       "Frame Advantage": "-11",
       "Invincibility": "",
       "Attribute": "Foot",
       "備考": ""
    },
    "3C": {
       "Input": "",
       "Damage": "780",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "2",
       "Recovery": "23",
       "Overall": "33",
       "Frame Advantage": "-7",
       "Invincibility": "7～10 Head",
       "Attribute": "",
       "備考": ""
    },
    "j.6C": {
       "Input": "",
       "Damage": "480",
       "Hit Type": "Overhead",
       "Active On": "12",
       "Active For": "3",
       "Recovery": "19",
       "Overall": "33",
       "Frame Advantage": "",
       "Invincibility": "",
       "Attribute": "Head",
       "備考": "動作終了後は空中で行動可能"
    },
    "j.2C": {
       "Input": "",
       "Damage": "570",
       "Hit Type": "Overhead / Overhead",
       "Active On": "14",
       "Active For": "3",
       "Recovery": "23",
       "Overall": "39",
       "Frame Advantage": "",
       "Invincibility": "",
       "Attribute": "Head",
       "備考": "初段ガード後は上段\n動作終了後は空中で行動可能"
    },
    "FF": {
       "Input": "B+C",
       "Damage": "1250",
       "Hit Type": "Mid",
       "Active On": "20",
       "Active For": "2",
       "Recovery": "27",
       "Overall": "48",
       "Frame Advantage": "-11",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "[FF]": {
       "Input": "B+C",
       "Damage": "1450",
       "Hit Type": "Overhead",
       "Active On": "32",
       "Active For": "2",
       "Recovery": "27",
       "Overall": "60",
       "Frame Advantage": "-11",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "FF (Vorpal)": {
       "Input": "B+C",
       "Damage": "1350",
       "Hit Type": "Mid",
       "Active On": "20",
       "Active For": "2",
       "Recovery": "22",
       "Overall": "43",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "[FF] (Vorpal)": {
       "Input": "B+C",
       "Damage": "1550",
       "Hit Type": "Overhead",
       "Active On": "30",
       "Active For": "2",
       "Recovery": "22",
       "Overall": "53",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "Throw": {
       "Input": "A+D",
       "Damage": "1420",
       "Hit Type": "Throw",
       "Active On": "4",
       "Active For": "1",
       "Recovery": "22",
       "Overall": "26",
       "Frame Advantage": "",
       "Invincibility": "",
       "Attribute": "Throw",
       "備考": "追撃可。投げ無敵時金投げ"
    },
    "236A": {
       "Input": "↓↘→+A",
       "Damage": "810",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "13",
       "Active For": "",
       "Recovery": "29",
       "Overall": "42",
       "Frame Advantage": "-7",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": ""
    },
    "236B": {
       "Input": "↓↘→+B",
       "Damage": "810",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "11",
       "Active For": "",
       "Recovery": "33",
       "Overall": "44",
       "Frame Advantage": "-11",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": ""
    },
    "236C": {
       "Input": "↓↘→+C",
       "Damage": "1518",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "10",
       "Active For": "",
       "Recovery": "24",
       "Overall": "34",
       "Frame Advantage": "+28",
       "Invincibility": "1～3 Throw",
       "Attribute": "Projectile",
       "備考": ""
    },
    "236X236A": {
       "Input": "↓↘→+A",
       "Damage": "552",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "14",
       "Active For": "15※",
       "Recovery": "22",
       "Overall": "50",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": "持続は飛び道具部分"
    },
    "236X236B": {
       "Input": "↓↘→+BorC",
       "Damage": "720",
       "Hit Type": "Mid",
       "Active On": "22",
       "Active For": "2",
       "Recovery": "31",
       "Overall": "54",
       "Frame Advantage": "-8",
       "Invincibility": "7～21 Foot",
       "Attribute": "",
       "備考": ""
    },
    "623A": {
       "Input": "→↓↘+A",
       "Damage": "1291",
       "Hit Type": "Mid",
       "Active On": "5",
       "Active For": "9",
       "Recovery": "40",
       "Overall": "53",
       "Frame Advantage": "-26",
       "Invincibility": "7～11 Head / 5～11 Dive",
       "Attribute": "",
       "備考": ""
    },
    "623B": {
       "Input": "→↓↘+B",
       "Damage": "1763",
       "Hit Type": "Mid",
       "Active On": "5",
       "Active For": "12",
       "Recovery": "55",
       "Overall": "71",
       "Frame Advantage": "-27",
       "Invincibility": "1～16 All",
       "Attribute": "",
       "備考": ""
    },
    "623C": {
       "Input": "→↓↘+C",
       "Damage": "1981",
       "Hit Type": "Mid",
       "Active On": "5",
       "Active For": "9",
       "Recovery": "55",
       "Overall": "68",
       "Frame Advantage": "-38",
       "Invincibility": "1～4 All / 5～13 All",
       "Attribute": "",
       "備考": ""
    },
    "214A": {
       "Input": "↓↙←+A",
       "Damage": "450",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "11",
       "Active For": "4",
       "Recovery": "35",
       "Overall": "49",
       "Frame Advantage": "-21",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "214B": {
       "Input": "↓↙←+B",
       "Damage": "450",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "11",
       "Active For": "4",
       "Recovery": "47",
       "Overall": "61",
       "Frame Advantage": "-33",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "214C": {
       "Input": "↓↙←+C",
       "Damage": "2190",
       "Hit Type": "Mid",
       "Active On": "5",
       "Active For": "6(10)2(6)2(7)2(10)2(23)4",
       "Recovery": "4",
       "Overall": "113",
       "Frame Advantage": "-75",
       "Invincibility": "1～3 Throw",
       "Attribute": "",
       "備考": ""
    },
    "214XX": {
       "Input": "←+AorBorC",
       "Damage": "600",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "3",
       "Recovery": "着地14",
       "Overall": "-",
       "Frame Advantage": "1～-8",
       "Invincibility": "",
       "Attribute": "",
       "備考": "硬直差は虚空ヲ分ツ断層 - 壱層(A)から出した場合"
    },
    "214XXX": {
       "Input": "←+AorBorC",
       "Damage": "950",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "19",
       "Active For": "4",
       "Recovery": "着地14",
       "Overall": "-",
       "Frame Advantage": "-9～-13",
       "Invincibility": "",
       "Attribute": "",
       "備考": "硬直差は虚空ヲ分ツ断層 - 壱層(A)から出した場合"
    },
    "22A": {
       "Input": "↓↓+A",
       "Damage": "1518",
       "Hit Type": "Low / Mid (Air Blockable)",
       "Active On": "11",
       "Active For": "2(2)5",
       "Recovery": "26",
       "Overall": "45",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attribute": "Projectile※",
       "備考": "※地面から吹き出す衝撃波は弾属性"
    },
    "22B": {
       "Input": "↓↓+B",
       "Damage": "1537",
       "Hit Type": "Low / Mid (Air Blockable)",
       "Active On": "22",
       "Active For": "2(2)5",
       "Recovery": "19",
       "Overall": "49",
       "Frame Advantage": "+1",
       "Invincibility": "",
       "Attribute": "Projectile※",
       "備考": "※地面から吹き出す衝撃波は弾属性"
    },
    "22C": {
       "Input": "↓↓+C",
       "Damage": "1749",
       "Hit Type": "Low / Mid (Air Blockable)",
       "Active On": "14",
       "Active For": "6※8(4)×9",
       "Recovery": "30",
       "Overall": "49",
       "Frame Advantage": "8～80",
       "Invincibility": "1～3 Throw",
       "Attribute": "Projectile※",
       "備考": "ダメージは11ヒット時のもの\n※地面から吹き出す衝撃波は弾属性　ダメージは11ヒット時のもの　※の持続は衝撃波部分"
    },
    "j.236A": {
       "Input": "空中↓↘→+A",
       "Damage": "1269",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "9",
       "Active For": "3(25)10",
       "Recovery": "3 upon landing",
       "Overall": "59",
       "Frame Advantage": "+14",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": ""
    },
    "j.236B": {
       "Input": "空中↓↘→+B",
       "Damage": "1269",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "9",
       "Active For": "3(26)10",
       "Recovery": "3 upon landing",
       "Overall": "60",
       "Frame Advantage": "+14",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": ""
    },
    "j.236C": {
       "Input": "空中↓↘→+C",
       "Damage": "1707",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "16",
       "Active For": "16",
       "Recovery": "3 upon landing",
       "Overall": "33",
       "Frame Advantage": "+24",
       "Invincibility": "1～3 Throw",
       "Attribute": "Projectile",
       "備考": ""
    },
    "41236C": {
       "Input": "←↙↓↘→+C",
       "Damage": "2045",
       "Hit Type": "Mid",
       "Active On": "8",
       "Active For": "6(5)5(2)8",
       "Recovery": "50",
       "Overall": "83",
       "Frame Advantage": "-29",
       "Invincibility": "1～23 All / 24～28 Strike",
       "Attribute": "",
       "備考": ""
    },
    "IW": {
       "Input": "←↙↓↘→+D",
       "Damage": "2433",
       "Hit Type": "Mid",
       "Active On": "13",
       "Active For": "6(2)10(2)10",
       "Recovery": "55",
       "Overall": "97",
       "Frame Advantage": "-18",
       "Invincibility": "1～55 All",
       "Attribute": "",
       "備考": ""
    },
    "IWEXS": {
       "Input": "A+B+C+D",
       "Damage": "3760",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "6",
       "Recovery": "47",
       "Overall": "67",
       "Frame Advantage": "-25",
       "Invincibility": "1～26 All",
       "Attribute": "",
       "備考": ""
    }
 }