export default {
    "5A": {
       "Input": "",
       "Damage": "160",
       "Hit Type": "Mid",
       "Active On": "8",
       "Active For": "4",
       "Recovery": "11",
       "Overall": "22",
       "Frame Advantage": "-3",
       "Invincible": "",
       "Attributes": "",
       "Notes": ""
    },
    "5B": {
       "Input": "",
       "Damage": "440",
       "Hit Type": "Mid",
       "Active On": "11",
       "Active For": "2",
       "Recovery": "22",
       "Overall": "34",
       "Frame Advantage": "-12",
       "Invincible": "",
       "Attributes": "",
       "Notes": ""
    },
    "5C": {
       "Input": "",
       "Damage": "710",
       "Hit Type": "Mid",
       "Active On": "14",
       "Active For": "5",
       "Recovery": "23",
       "Overall": "41",
       "Frame Advantage": "-10",
       "Invincible": "",
       "Attributes": "",
       "Notes": ""
    },
    "5[C]": {
       "Input": "",
       "Damage": "805",
       "Hit Type": "Mid",
       "Active On": "26",
       "Active For": "5",
       "Recovery": "23",
       "Overall": "53",
       "Frame Advantage": "-10",
       "Invincible": "",
       "Attributes": "",
       "Notes": ""
    },
    "2A": {
       "Input": "",
       "Damage": "327",
       "Hit Type": "Low",
       "Active On": "6",
       "Active For": "3(6)2",
       "Recovery": "12",
       "Overall": "28",
       "Frame Advantage": "-2",
       "Invincible": "",
       "Attributes": "Foot",
       "Notes": ""
    },
    "2B": {
       "Input": "",
       "Damage": "445",
       "Hit Type": "Low",
       "Active On": "7",
       "Active For": "2(6)4",
       "Recovery": "12",
       "Overall": "30",
       "Frame Advantage": "-4",
       "Invincible": "",
       "Attributes": "Foot",
       "Notes": ""
    },
    "2C": {
       "Input": "",
       "Damage": "570",
       "Hit Type": "Low",
       "Active On": "12",
       "Active For": "7",
       "Recovery": "24",
       "Overall": "42",
       "Frame Advantage": "-15",
       "Invincible": "",
       "Attributes": "Foot",
       "Notes": ""
    },
    "j.A": {
       "Input": "",
       "Damage": "180",
       "Hit Type": "Overhead",
       "Active On": "9",
       "Active For": "2",
       "Recovery": "17",
       "Overall": "27",
       "Frame Advantage": "-",
       "Invincible": "",
       "Attributes": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.B": {
       "Input": "",
       "Damage": "507",
       "Hit Type": "Overhead",
       "Active On": "10",
       "Active For": "4",
       "Recovery": "15",
       "Overall": "27",
       "Frame Advantage": "-",
       "Invincible": "",
       "Attributes": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.C": {
       "Input": "",
       "Damage": "666",
       "Hit Type": "Overhead",
       "Active On": "15",
       "Active For": "4",
       "Recovery": "24",
       "Overall": "42",
       "Frame Advantage": "-",
       "Invincible": "",
       "Attributes": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "66B": {
       "Input": "",
       "Damage": "789",
       "Hit Type": "Low",
       "Active On": "7",
       "Active For": "3(7)4",
       "Recovery": "10",
       "Overall": "30",
       "Frame Advantage": "-2",
       "Invincible": "",
       "Attributes": "Foot",
       "Notes": ""
    },
    "66C": {
       "Input": "",
       "Damage": "1178",
       "Hit Type": "Mid/Overhead",
       "Active On": "6",
       "Active For": "2(18)6",
       "Recovery": "19",
       "Overall": "50",
       "Frame Advantage": "-7",
       "Invincible": "",
       "Attributes": "Head (second hit only)",
       "Notes": "The mid hit only hits aerial opponents."
    },
    "Fly": {
       "Input": "In air ↖or↑or↗",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "16 upon landing",
       "Overall": "99",
       "Frame Advantage": "-",
       "Invincible": "",
       "Attributes": "",
       "Notes": "Cannot act frames 1～17"
    },
    "Glide": {
       "Input": "During fly →→",
       "Damage": "666",
       "Hit Type": "Overhead",
       "Active On": "20",
       "Active For": "12",
       "Recovery": "16 upon landing",
       "Overall": "54",
       "Frame Advantage": "-17",
       "Invincible": "",
       "Attributes": "Head",
       "Notes": "硬直差は密着・最低空でガードさせた場合のもの"
    },
    "4B": {
       "Input": "",
       "Damage": "666",
       "Hit Type": "Mid",
       "Active On": "12 (AA - 10)",
       "Active For": "5",
       "Recovery": "19",
       "Overall": "33",
       "Frame Advantage": "-4",
       "Invincible": "8～11 Head",
       "Attributes": "",
       "Notes": "Frames 10-11 anti air hitbox"
    },
    "6C": {
       "Input": "",
       "Damage": "754",
       "Hit Type": "Mid",
       "Active On": "18",
       "Active For": "6",
       "Recovery": "20",
       "Overall": "43",
       "Frame Advantage": "-8",
       "Invincible": "",
       "Attributes": "",
       "Notes": ""
    },
    "6[C]": {
       "Input": "",
       "Damage": "862",
       "Hit Type": "Mid",
       "Active On": "28",
       "Active For": "6",
       "Recovery": "21",
       "Overall": "54",
       "Frame Advantage": "-9",
       "Invincible": "",
       "Attributes": "",
       "Notes": ""
    },
    "3C": {
       "Input": "",
       "Damage": "612",
       "Hit Type": "Mid/Overhead",
       "Active On": "7",
       "Active For": "3(20)11",
       "Recovery": "14",
       "Overall": "54",
       "Frame Advantage": "-9",
       "Invincible": "",
       "Attributes": "",
       "Notes": "The mid hit only hits aerial opponents."
    },
    "3[C]": {
       "Input": "",
       "Damage": "",
       "Hit Type": "Mid",
       "Active On": "7",
       "Active For": "5",
       "Recovery": "33",
       "Overall": "44",
       "Frame Advantage": "-",
       "Invincible": "",
       "Attributes": "",
       "Notes": "The mid hit only hits aerial opponents"
    },
    "4C": {
       "Input": "",
       "Damage": "862",
       "Hit Type": "Overhead",
       "Active On": "29",
       "Active For": "2",
       "Recovery": "23",
       "Overall": "53",
       "Frame Advantage": "-7",
       "Invincible": "",
       "Attributes": "",
       "Notes": ""
    },
    "j.2C": {
       "Input": "",
       "Damage": "410",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "> landing",
       "Recovery": "10 upon landing",
       "Overall": "24",
       "Frame Advantage": "-6",
       "Invincible": "",
       "Attributes": "Head",
       "Notes": "硬直差はジャンプの昇りから出してガードさせた場合のもの"
    },
    "5BB": {
       "Input": "",
       "Damage": "293",
       "Hit Type": "Mid",
       "Active On": "3",
       "Active For": "4",
       "Recovery": "21",
       "Overall": "27",
       "Frame Advantage": "-9",
       "Invincible": "",
       "Attributes": "",
       "Notes": ""
    },
    "2CC": {
       "Input": "",
       "Damage": "466",
       "Hit Type": "Mid",
       "Active On": "15",
       "Active For": "3",
       "Recovery": "24",
       "Overall": "41",
       "Frame Advantage": "-11",
       "Invincible": "",
       "Attributes": "",
       "Notes": ""
    },
    "FF": {
       "Input": "B+C",
       "Damage": "1426～1790",
       "Hit Type": "Mid",
       "Active On": "11",
       "Active For": "3",
       "Recovery": "22",
       "Overall": "35",
       "Frame Advantage": "-9",
       "Invincible": "",
       "Attributes": "",
       "Notes": "Do 360 motions + mash buttons to get all hits."
    },
    "FF (Vorpal)": {
       "Input": "B+C",
       "Damage": "1526～1890",
       "Hit Type": "Mid",
       "Active On": "11",
       "Active For": "3",
       "Recovery": "22",
       "Overall": "35",
       "Frame Advantage": "-9",
       "Invincible": "",
       "Attributes": "",
       "Notes": "Do 360 motions + mash buttons to get all hits."
    },
    "Throw": {
       "Input": "A+D",
       "Damage": "1110～1850",
       "Hit Type": "Throw",
       "Active On": "4",
       "Active For": "1",
       "Recovery": "22",
       "Overall": "26",
       "Frame Advantage": "-",
       "Invincible": "",
       "Attributes": "Throw",
       "Notes": "Do 646... motions + mash buttons to get all 8 hits. Invincible during entire throwing animation."
    },
    "236A": {
       "Input": "↓↘→+A",
       "Damage": "1335",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "8",
       "Recovery": "25",
       "Overall": "41",
       "Frame Advantage": "-5",
       "Invincible": "",
       "Attributes": "",
       "Notes": ""
    },
    "236B": {
       "Input": "↓↘→+B",
       "Damage": "1510",
       "Hit Type": "Mid",
       "Active On": "13",
       "Active For": "8",
       "Recovery": "29",
       "Overall": "49",
       "Frame Advantage": "-9",
       "Invincible": "",
       "Attributes": "",
       "Notes": ""
    },
    "236C": {
       "Input": "↓↘→+C",
       "Damage": "1955",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "16",
       "Recovery": "22",
       "Overall": "49",
       "Frame Advantage": "-2",
       "Invincible": "1～11all/12～19 Dive・head・projectile",
       "Attributes": "",
       "Notes": ""
    },
    "623A": {
       "Input": "→↓↘+A",
       "Damage": "1430",
       "Hit Type": "Mid",
       "Active On": "14",
       "Active For": "14",
       "Recovery": "20",
       "Overall": "47",
       "Frame Advantage": "+1",
       "Invincible": "14～17 head・Dive",
       "Attributes": "",
       "Notes": "硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "623B": {
       "Input": "→↓↘+B",
       "Damage": "1616",
       "Hit Type": "Mid",
       "Active On": "7",
       "Active For": "28",
       "Recovery": "24",
       "Overall": "58",
       "Frame Advantage": "-8",
       "Invincible": "5～16 head・Dive",
       "Attributes": "",
       "Notes": "硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "623C": {
       "Input": "→↓↘+C",
       "Damage": "1841",
       "Hit Type": "Mid",
       "Active On": "7",
       "Active For": "28",
       "Recovery": "18 upon landing",
       "Overall": "62",
       "Frame Advantage": "-36",
       "Invincible": "1～4 all /5～6 strike/7～16 head",
       "Attributes": "",
       "Notes": "硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "214A": {
       "Input": "↓↙←+A",
       "Damage": "1499",
       "Hit Type": "Mid (doesnt hit in air)",
       "Active On": "13",
       "Active For": "16",
       "Recovery": "10",
       "Overall": "38～47",
       "Frame Advantage": "-14",
       "Invincible": "",
       "Attributes": "",
       "Notes": "Frame Advantage at point blank"
    },
    "214B": {
       "Input": "↓↙←+B",
       "Damage": "1499",
       "Hit Type": "Mid",
       "Active On": "11",
       "Active For": "16",
       "Recovery": "10",
       "Overall": "36～46",
       "Frame Advantage": "-",
       "Invincible": "",
       "Attributes": "",
       "Notes": "Frame Advantage at point blank"
    },
    "214C": {
       "Input": "↓↙←+C",
       "Damage": "1985",
       "Hit Type": "Mid",
       "Active On": "5",
       "Active For": "21",
       "Recovery": "7",
       "Overall": "34",
       "Frame Advantage": "-12",
       "Invincible": "1～3 throw",
       "Attributes": "",
       "Notes": "Frame Advantage at point blank"
    },
    "22A": {
       "Input": "↓↓+A",
       "Damage": "427",
       "Hit Type": "Mid(air blockable)",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "42",
       "Frame Advantage": "+57",
       "Invincible": "",
       "Attributes": "",
       "Notes": ""
    },
    "22B": {
       "Input": "↓↓+B",
       "Damage": "427・427",
       "Hit Type": "Mid(air blockable)",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "55",
       "Frame Advantage": "+44",
       "Invincible": "",
       "Attributes": "",
       "Notes": ""
    },
    "22C": {
       "Input": "↓↓+C",
       "Damage": "999・427×3・427×3・427×3",
       "Hit Type": "Overhead/Mid(air blockable)×3",
       "Active On": "18",
       "Active For": "1",
       "Recovery": "22",
       "Overall": "40",
       "Frame Advantage": "-5",
       "Invincible": "",
       "Attributes": "",
       "Notes": ""
    },
    "j.214A": {
       "Input": "In air↓↙←+A",
       "Damage": "700",
       "Hit Type": "Mid(air unblockable)",
       "Active On": "14",
       "Active For": "-",
       "Recovery": "4 upon landing",
       "Overall": "41",
       "Frame Advantage": "+1",
       "Invincible": "",
       "Attributes": "Projectile",
       "Notes": "Frame Advantage at point blank on a standing Hyde"
    },
    "j.214[A]": {
       "Input": "In air↓↙←+A",
       "Damage": "1056",
       "Hit Type": "Mid(air unblockable)",
       "Active On": "21",
       "Active For": "-",
       "Recovery": "4 upon landing",
       "Overall": "48",
       "Frame Advantage": "+8",
       "Invincible": "",
       "Attributes": "Projectile",
       "Notes": "Frame Advantage at point blank on a standing Hyde"
    },
    "j.214B": {
       "Input": "In air ↙←+B",
       "Damage": "700",
       "Hit Type": "Mid(air blockable)",
       "Active On": "15",
       "Active For": "-",
       "Recovery": "4 upon landing",
       "Overall": "44",
       "Frame Advantage": "-1",
       "Invincible": "",
       "Attributes": "Projectile",
       "Notes": "Frame Advantage at point blank on a standing Hyde"
    },
    "j.214[B]": {
       "Input": "In air↓↙←+B",
       "Damage": "1056",
       "Hit Type": "Mid(air blockable)",
       "Active On": "21",
       "Active For": "-",
       "Recovery": "4 upon landing",
       "Overall": "50",
       "Frame Advantage": "+6",
       "Invincible": "",
       "Attributes": "Projectile",
       "Notes": "Frame Advantage at point blank on a standing Hyde"
    },
    "j.214C": {
       "Input": "In air↓↙←+C",
       "Damage": "1725",
       "Hit Type": "Mid(air blockable)",
       "Active On": "6",
       "Active For": "-",
       "Recovery": "4 upon landing",
       "Overall": "95",
       "Frame Advantage": "-6",
       "Invincible": "",
       "Attributes": "Projectile",
       "Notes": "Frame Advantage at point blank on a standing Hyde"
    },
    "41236C": {
       "Input": "←↙↓↘→+C",
       "Damage": "2109",
       "Hit Type": "Mid(air blockable)",
       "Active On": "14",
       "Active For": "18",
       "Recovery": "15",
       "Overall": "46",
       "Frame Advantage": "-6",
       "Invincible": "1～1 all /2～3 throw",
       "Attributes": "",
       "Notes": ""
    },
    "IW": {
       "Input": "←↙↓↘→+D",
       "Damage": "3062",
       "Hit Type": "Mid(air blockable)",
       "Active On": "13",
       "Active For": "72",
       "Recovery": "44",
       "Overall": "128",
       "Frame Advantage": "-30",
       "Invincible": "1～31 all /32～84 strike",
       "Attributes": "",
       "Notes": ""
    },
    "IWEXS": {
       "Input": "A+B+C+D",
       "Damage": "3780",
       "Hit Type": "Mid(air blockable)",
       "Active On": "15",
       "Active For": "6",
       "Recovery": "47",
       "Overall": "67",
       "Frame Advantage": "-25",
       "Invincible": "1～26 all ",
       "Attributes": "",
       "Notes": ""
    }
 }