module.exports = {
    "5A": {
       "Input": "",
       "Damage": "190",
       "Hit Type": "Mid",
       "Active On": "5",
       "Active For": "2",
       "Recovery": "12",
       "Overall": "18",
       "Frame Advantage": "-1",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "5B": {
       "Input": "",
       "Damage": "510",
       "Hit Type": "Mid",
       "Active On": "7",
       "Active For": "5",
       "Recovery": "16",
       "Overall": "27",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "5C": {
       "Input": "",
       "Damage": "710",
       "Hit Type": "Mid",
       "Active On": "11",
       "Active For": "3",
       "Recovery": "19",
       "Overall": "32",
       "Frame Advantage": "-4",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "5[C]": {
       "Input": "",
       "Damage": "780",
       "Hit Type": "Mid",
       "Active On": "21",
       "Active For": "4",
       "Recovery": "23",
       "Overall": "47",
       "Frame Advantage": "-1",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "2A": {
       "Input": "",
       "Damage": "180",
       "Hit Type": "Low",
       "Active On": "5",
       "Active For": "2",
       "Recovery": "12",
       "Overall": "18",
       "Frame Advantage": "-1",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "2B": {
       "Input": "",
       "Damage": "480",
       "Hit Type": "Low",
       "Active On": "7",
       "Active For": "5",
       "Recovery": "15",
       "Overall": "26",
       "Frame Advantage": "-4",
       "Invincibility": "",
       "Attributes": "Foot",
       "Notes": ""
    },
    "2C": {
       "Input": "",
       "Damage": "620",
       "Hit Type": "Mid",
       "Active On": "13",
       "Active For": "3",
       "Recovery": "20",
       "Overall": "35",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "j.A": {
       "Input": "",
       "Damage": "150",
       "Hit Type": "Overhead",
       "Active On": "7",
       "Active For": "3",
       "Recovery": "14",
       "Overall": "23",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.B": {
       "Input": "",
       "Damage": "450",
       "Hit Type": "Overhead",
       "Active On": "8",
       "Active For": "5",
       "Recovery": "15",
       "Overall": "27",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.C": {
       "Input": "",
       "Damage": "620",
       "Hit Type": "Overhead",
       "Active On": "12",
       "Active For": "4",
       "Recovery": "18",
       "Overall": "33",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.[C]": {
       "Input": "",
       "Damage": "780",
       "Hit Type": "Overhead",
       "Active On": "19",
       "Active For": "4",
       "Recovery": "20",
       "Overall": "42",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "66B": {
       "Input": "",
       "Damage": "707",
       "Hit Type": "Mid/Low",
       "Active On": "8",
       "Active For": "19",
       "Recovery": "15",
       "Overall": "41",
       "Frame Advantage": "-7",
       "Invincibility": "",
       "Attributes": "Foot",
       "Notes": "15F以降下段判定"
    },
    "66C": {
       "Input": "",
       "Damage": "980",
       "Hit Type": "Overhead",
       "Active On": "26",
       "Active For": "6",
       "Recovery": "34",
       "Overall": "65",
       "Frame Advantage": "-9",
       "Invincibility": "8～31Foot",
       "Attributes": "",
       "Notes": ""
    },
    "3B": {
       "Input": "",
       "Damage": "650",
       "Hit Type": "Mid",
       "Active On": "13",
       "Active For": "11",
       "Recovery": "12",
       "Overall": "35",
       "Frame Advantage": "-7",
       "Invincibility": "10～21 Foot",
       "Attributes": "",
       "Notes": ""
    },
    "3C": {
       "Input": "",
       "Damage": "612",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "2",
       "Recovery": "22",
       "Overall": "32",
       "Frame Advantage": "-6",
       "Invincibility": "7～10 Head",
       "Attributes": "",
       "Notes": ""
    },
    "j.AA": {
       "Input": "",
       "Damage": "719",
       "Hit Type": "Mid",
       "Active On": "5",
       "Active For": "2(4)2(2)2(4)3",
       "Recovery": "15",
       "Overall": "38",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "5BB": {
       "Input": "",
       "Damage": "790",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "16",
       "Active For": "4",
       "Recovery": "28",
       "Overall": "47",
       "Frame Advantage": "-14",
       "Invincibility": "",
       "Attributes": "Projectiel",
       "Notes": "3～19弾相殺"
    },
    "FF": {
       "Input": "B+C",
       "Damage": "855",
       "Hit Type": "Mid",
       "Active On": "21",
       "Active For": "9",
       "Recovery": "49",
       "Overall": "78",
       "Frame Advantage": "-23",
       "Invincibility": "1～4 Throw",
       "Attributes": "",
       "Notes": ""
    },
    "[FF]": {
       "Input": "B+C",
       "Damage": "1222",
       "Hit Type": "Overhead",
       "Active On": "29",
       "Active For": "8",
       "Recovery": "49",
       "Overall": "85",
       "Frame Advantage": "-23",
       "Invincibility": "1～4 Throw",
       "Attributes": "",
       "Notes": ""
    },
    "j.FF": {
       "Input": "B+C",
       "Damage": "855",
       "Hit Type": "Mid",
       "Active On": "15",
       "Active For": "Until landing + 6F",
       "Recovery": "57",
       "Overall": "-",
       "Frame Advantage": "-31",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": ""
    },
    "j.[FF]": {
       "Input": "B+C",
       "Damage": "1222",
       "Hit Type": "Overhead",
       "Active On": "29",
       "Active For": "Until landing + 6F",
       "Recovery": "57",
       "Overall": "-",
       "Frame Advantage": "-31",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": ""
    },
    "Throw": {
       "Input": "A+D",
       "Damage": "1720",
       "Hit Type": "Throw",
       "Active On": "4",
       "Active For": "1",
       "Recovery": "22",
       "Overall": "26",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Throw",
       "Notes": "投げ無敵時金投げ"
    },
    "236A": {
       "Input": "↓↘→+A",
       "Damage": "750",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "16",
       "Active For": "20",
       "Recovery": "14",
       "Overall": "49",
       "Frame Advantage": "-12",
       "Invincibility": "",
       "Attributes": "",
       "Notes": "動作後は空中で行動可"
    },
    "236B": {
       "Input": "↓↘→+B",
       "Damage": "750",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "13",
       "Active For": "16",
       "Recovery": "4(9 upon landing)",
       "Overall": "32",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attributes": "",
       "Notes": "動作終了後は空中で行動可能\n何もせずに着地すると着地硬直発生"
    },
    "236C": {
       "Input": "↓↘→+C",
       "Damage": "800",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "5",
       "Active For": "20",
       "Recovery": "17",
       "Overall": "41",
       "Frame Advantage": "-15",
       "Invincibility": "1～3 Throw",
       "Attributes": "",
       "Notes": ""
    },
    "j.236A": {
       "Input": "空中↓↘→+A",
       "Damage": "750",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "16",
       "Active For": "20",
       "Recovery": "16 upon landing",
       "Overall": "-",
       "Frame Advantage": "-26",
       "Invincibility": "",
       "Attributes": "Dive",
       "Notes": "全体と硬直差は密着から最低空で出した場合のもの"
    },
    "j.236B": {
       "Input": "空中↓↘→+B",
       "Damage": "750",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "16",
       "Active For": "16",
       "Recovery": "16 upon landing",
       "Overall": "-",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attributes": "Dive",
       "Notes": "全体と硬直差は密着から最低空で出した場合のもの"
    },
    "j.236C": {
       "Input": "空中↓↘→+C",
       "Damage": "800",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "5",
       "Active For": "20",
       "Recovery": "13 upon landing",
       "Overall": "-",
       "Frame Advantage": "-19",
       "Invincibility": "",
       "Attributes": "Dive",
       "Notes": "全体と硬直差は密着から最低空で出した場合のもの"
    },
    "236X,8": {
       "Input": "↑+AorBorC",
       "Damage": "750",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "9",
       "Active For": "10",
       "Recovery": "6(15 upon landing)",
       "Overall": "24",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Dive",
       "Notes": "動作終了後は空中で行動可能\n何もせずに着地すると着地硬直発生"
    },
    "236X,7/9": {
       "Input": "↖or↗+AorBorC",
       "Damage": "750",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "12",
       "Active For": "12",
       "Recovery": "6(15 upon landing)",
       "Overall": "29",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Dive",
       "Notes": "動作終了後は空中で行動可能\n何もせずに着地すると着地硬直発生"
    },
    "236X,4/6": {
       "Input": "←or→+AorBorC",
       "Damage": "750",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "12",
       "Active For": "16",
       "Recovery": "15 upon landing",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Dive",
       "Notes": ""
    },
    "236X,1/3": {
       "Input": "↙or↘+AorBorC",
       "Damage": "750",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "12",
       "Active For": "16",
       "Recovery": "15 upon landing",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Dive",
       "Notes": ""
    },
    "236X,2": {
       "Input": "↓+AorBorC",
       "Damage": "750",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "12",
       "Active For": "16",
       "Recovery": "15 upon landing",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Dive",
       "Notes": ""
    },
    "236C,8": {
       "Input": "↑+AorBorC",
       "Damage": "750",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "8",
       "Active For": "16",
       "Recovery": "7(12 upon landing)",
       "Overall": "30",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Dive",
       "Notes": "動作終了後は空中で行動可能\n何もせずに着地すると着地硬直発生"
    },
    "236C,7/9": {
       "Input": "↖or↗+AorBorC",
       "Damage": "750",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "10",
       "Active For": "16",
       "Recovery": "6(12 upon landing",
       "Overall": "31",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Dive",
       "Notes": "動作終了後は空中で行動可能\n何もせずに着地すると着地硬直発生"
    },
    "236C,4/6": {
       "Input": "←or→+AorBorC",
       "Damage": "750",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "10",
       "Active For": "16",
       "Recovery": "着地12",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Dive",
       "Notes": ""
    },
    "236C,1/3": {
       "Input": "↙or↘+AorBorC",
       "Damage": "750",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "10",
       "Active For": "16",
       "Recovery": "着地12",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Dive",
       "Notes": ""
    },
    "236C,2": {
       "Input": "↓+AorBorC",
       "Damage": "750",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "10",
       "Active For": "16",
       "Recovery": "着地12",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Dive",
       "Notes": ""
    },
    "623A": {
       "Input": "→↓↘+A",
       "Damage": "952",
       "Hit Type": "Mid",
       "Active On": "7",
       "Active For": "12",
       "Recovery": "21",
       "Overall": "39",
       "Frame Advantage": "-2",
       "Invincibility": "5～12 Head / 5～12 Dive",
       "Attributes": "",
       "Notes": ""
    },
    "623B": {
       "Input": "→↓↘+B",
       "Damage": "1020",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "12",
       "Recovery": "26",
       "Overall": "46",
       "Frame Advantage": "-7",
       "Invincibility": "7～14 Head ・ Dive",
       "Attributes": "",
       "Notes": ""
    },
    "623C": {
       "Input": "→↓↘+C",
       "Damage": "1720",
       "Hit Type": "Mid",
       "Active On": "7",
       "Active For": "36",
       "Recovery": "44",
       "Overall": "86",
       "Frame Advantage": "-51",
       "Invincibility": "1～6 All / 7～14 Strike",
       "Attributes": "",
       "Notes": ""
    },
    "623CC": {
       "Input": "→↓↘+C",
       "Damage": "1720",
       "Hit Type": "Mid",
       "Active On": "7",
       "Active For": "36",
       "Recovery": "24",
       "Overall": "66",
       "Frame Advantage": "-7",
       "Invincibility": "1～6 All / 7～14 Strike",
       "Attributes": "",
       "Notes": ""
    },
    "623AA": {
       "Input": "A",
       "Damage": "967",
       "Hit Type": "Mid",
       "Active On": "4",
       "Active For": "24",
       "Recovery": "32",
       "Overall": "59",
       "Frame Advantage": "-24",
       "Invincibility": "1～13 Projectile / 4～13 Head・Dive",
       "Attributes": "",
       "Notes": "硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "623BB": {
       "Input": "B",
       "Damage": "967",
       "Hit Type": "Mid",
       "Active On": "4",
       "Active For": "24",
       "Recovery": "33",
       "Overall": "60",
       "Frame Advantage": "-25",
       "Invincibility": "1～13 Projectile / 4～13 Head・Dive",
       "Attributes": "",
       "Notes": "硬直差は立ち状態のハイドにガードさせた場合のもの"
    },
    "360C": {
       "Input": "１回転+C",
       "Damage": "2047～2545",
       "Hit Type": "Throw",
       "Active On": "3",
       "Active For": "1",
       "Recovery": "53",
       "Overall": "56",
       "Frame Advantage": "-",
       "Invincibility": "1～3 Throw",
       "Attributes": "Throw",
       "Notes": "追加入力のタイミングでダメージ変動"
    },
    "214A": {
       "Input": "↓↙←+A",
       "Damage": "1350",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "9",
       "Recovery": "20",
       "Overall": "37",
       "Frame Advantage": "-",
       "Invincibility": "1～17 Throw",
       "Attributes": "Throw",
       "Notes": "着地前の攻撃判定(9～15F)は連続技中のみヒットする\n投げ無敵時金投げ"
    },
    "214B": {
       "Input": "↓↙←+B",
       "Damage": "1620",
       "Hit Type": "Mid",
       "Active On": "17",
       "Active For": "12",
       "Recovery": "20",
       "Overall": "48",
       "Frame Advantage": "-",
       "Invincibility": "1～28 Throw",
       "Attributes": "Throw",
       "Notes": "着地前の攻撃判定(17～26F)は連続技中のみヒットする\n投げ無敵時金投げ"
    },
    "214C": {
       "Input": "↓↙←+C",
       "Damage": "2080",
       "Hit Type": "Mid",
       "Active On": "6",
       "Active For": "着地まで+着地後2",
       "Recovery": "20",
       "Overall": "38",
       "Frame Advantage": "-",
       "Invincibility": "3～2 after landing・feet",
       "Attributes": "Throw",
       "Notes": "着地前の攻撃判定は連続技中のみヒットする\n着地前の持続は相手との距離によって変わる\n投げ無敵時金投げ"
    },
    "IW": {
       "Input": "←↙↓↘→+D",
       "Damage": "3140",
       "Hit Type": "Mid/Overhead",
       "Active On": "11",
       "Active For": "12(20)12",
       "Recovery": "53",
       "Overall": "107",
       "Frame Advantage": "-42",
       "Invincibility": "1～22 All / 23～31 Throw",
       "Attributes": "",
       "Notes": ""
    },
    "IWEXS": {
       "Input": "A+B+C+D",
       "Damage": "3750",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "6",
       "Recovery": "47",
       "Overall": "67",
       "Frame Advantage": "-25",
       "Invincibility": "1～26 All",
       "Attributes": "",
       "Notes": ""
    }
 }