export default {
    "5A": {
       "Input": "",
       "Damage": "190",
       "Hit Type": "Mid",
       "Active On": "6",
       "Active For": "2",
       "Recovery": "12",
       "Overall": "19",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "5B": {
       "Input": "",
       "Damage": "390",
       "Hit Type": "Mid",
       "Active On": "8",
       "Active For": "3",
       "Recovery": "17",
       "Overall": "27",
       "Frame Advantage": "-4",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "5C": {
       "Input": "",
       "Damage": "580",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "3",
       "Recovery": "23",
       "Overall": "37",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "5[C]": {
       "Input": "",
       "Damage": "673",
       "Hit Type": "Mid",
       "Active On": "17",
       "Active For": "3",
       "Recovery": "26",
       "Overall": "45",
       "Frame Advantage": "-10",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "2A": {
       "Input": "",
       "Damage": "140",
       "Hit Type": "Mid",
       "Active On": "5",
       "Active For": "2",
       "Recovery": "12",
       "Overall": "18",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "2B": {
       "Input": "",
       "Damage": "440",
       "Hit Type": "Low",
       "Active On": "9",
       "Active For": "3",
       "Recovery": "18",
       "Overall": "29",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attribute": "Foot",
       "Notes": ""
    },
    "2C": {
       "Input": "",
       "Damage": "560",
       "Hit Type": "Low",
       "Active On": "12",
       "Active For": "4",
       "Recovery": "23",
       "Overall": "38",
       "Frame Advantage": "-9",
       "Invincibility": "",
       "Attribute": "Foot",
       "Notes": ""
    },
    "j.A": {
       "Input": "",
       "Damage": "130",
       "Hit Type": "Overhead",
       "Active On": "7",
       "Active For": "2",
       "Recovery": "15",
       "Overall": "23",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.B": {
       "Input": "",
       "Damage": "380",
       "Hit Type": "Overhead",
       "Active On": "11",
       "Active For": "3",
       "Recovery": "19",
       "Overall": "32",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.C": {
       "Input": "",
       "Damage": "520",
       "Hit Type": "Overhead",
       "Active On": "12",
       "Active For": "5",
       "Recovery": "18",
       "Overall": "34",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.[C]": {
       "Input": "",
       "Damage": "720",
       "Hit Type": "Overhead",
       "Active On": "18",
       "Active For": "3",
       "Recovery": "25",
       "Overall": "45",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "66B": {
       "Input": "",
       "Damage": "444",
       "Hit Type": "Low",
       "Active On": "18",
       "Active For": "13",
       "Recovery": "9",
       "Overall": "39",
       "Frame Advantage": "-4",
       "Invincibility": "12～17 Foot",
       "Attribute": "Foot",
       "Notes": ""
    },
    "66C": {
       "Input": "",
       "Damage": "666",
       "Hit Type": "Overhead",
       "Active On": "27",
       "Active For": "4",
       "Recovery": "16",
       "Overall": "46",
       "Frame Advantage": "-2",
       "Invincibility": "15～26 Foot",
       "Attribute": "",
       "Notes": ""
    },
    "3C": {
       "Input": "",
       "Damage": "570",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "3",
       "Recovery": "29",
       "Overall": "40",
       "Frame Advantage": "-14",
       "Invincibility": "7～11 Head",
       "Attribute": "",
       "Notes": ""
    },
    "j.2C": {
       "Input": "",
       "Damage": "520",
       "Hit Type": "Overhead",
       "Active On": "13",
       "Active For": "3",
       "Recovery": "Until Landing",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": ""
    },
    "j.2[C]": {
       "Input": "",
       "Damage": "750",
       "Hit Type": "Overhead",
       "Active On": "17",
       "Active For": "3",
       "Recovery": "Until Landing",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": ""
    },
    "j.8C": {
       "Input": "",
       "Damage": "650",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "4",
       "Recovery": "15",
       "Overall": "30",
       "Frame Advantage": "-",
       "Invincibility": "8～15 Head",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.BB": {
       "Input": "",
       "Damage": "510",
       "Hit Type": "Overhead",
       "Active On": "9",
       "Active For": "3",
       "Recovery": "16",
       "Overall": "27",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "FF": {
       "Input": "B+C",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "51",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "4Fから空中で行動可"
    },
    "j.FF": {
       "Input": "空中B+C",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "51",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "13Fから空中で行動可"
    },
    "Throw": {
       "Input": "A+D",
       "Damage": "1640",
       "Hit Type": "Throw",
       "Active On": "4",
       "Active For": "1",
       "Recovery": "22",
       "Overall": "26",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Throw",
       "Notes": "投げ無敵時金投げ"
    },
    "236A": {
       "Input": "↓↘→+A",
       "Damage": "750",
       "Hit Type": "Mid",
       "Active On": "7",
       "Active For": "15",
       "Recovery": "20",
       "Overall": "41",
       "Frame Advantage": "-13",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "236B": {
       "Input": "↓↘→+B",
       "Damage": "750",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "27",
       "Recovery": "28",
       "Overall": "63",
       "Frame Advantage": "-33",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "236C": {
       "Input": "↓↘→+C",
       "Damage": "1836",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "9",
       "Active For": "15",
       "Recovery": "27",
       "Overall": "50",
       "Frame Advantage": "-12",
       "Invincibility": "1～3 Throw / 2～23 Projectile",
       "Attribute": "",
       "Notes": ""
    },
    "236XA": {
       "Input": "→+A",
       "Damage": "890",
       "Hit Type": "Mid",
       "Active On": "17",
       "Active For": "10",
       "Recovery": "23",
       "Overall": "49",
       "Frame Advantage": "-7",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "236XB": {
       "Input": "→+B",
       "Damage": "730",
       "Hit Type": "Overhead",
       "Active On": "24",
       "Active For": "5",
       "Recovery": "20",
       "Overall": "48",
       "Frame Advantage": "-7",
       "Invincibility": "16～28 Foot",
       "Attribute": "",
       "Notes": ""
    },
    "236XC": {
       "Input": "→+C",
       "Damage": "956",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "14",
       "Active For": "3",
       "Recovery": "23",
       "Overall": "39",
       "Frame Advantage": "-",
       "Invincibility": "6～16 Projectile / 14～16 All",
       "Attribute": "",
       "Notes": ""
    },
    "623A": {
       "Input": "→↓↘+A",
       "Damage": "1131",
       "Hit Type": "Mid",
       "Active On": "7",
       "Active For": "7",
       "Recovery": "38",
       "Overall": "51",
       "Frame Advantage": "-23",
       "Invincibility": "4～13 Dive / 7～13 Head",
       "Attribute": "",
       "Notes": ""
    },
    "623B": {
       "Input": "→↓↘+B",
       "Damage": "1359",
       "Hit Type": "Mid",
       "Active On": "6",
       "Active For": "10",
       "Recovery": "45",
       "Overall": "60",
       "Frame Advantage": "-31",
       "Invincibility": "1～9 All / 10～15 Head / 10～15 Dive",
       "Attribute": "",
       "Notes": ""
    },
    "623C": {
       "Input": "→↓↘+C",
       "Damage": "1670～2216",
       "Hit Type": "Mid",
       "Active On": "7",
       "Active For": "16",
       "Recovery": "58",
       "Overall": "80",
       "Frame Advantage": "-50",
       "Invincibility": "1～6 All / 7～10 Strike",
       "Attribute": "",
       "Notes": "硬直差は立ち状態のハイドにガードさせた場合のもの\n方向キー入力でダメージ増加"
    },
    "214A": {
       "Input": "↓↙←+A",
       "Damage": "1355",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "17",
       "Active For": "18",
       "Recovery": "28",
       "Overall": "62",
       "Frame Advantage": "-9",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "214B": {
       "Input": "↓↙←+B",
       "Damage": "1355",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "13",
       "Active For": "18",
       "Recovery": "28",
       "Overall": "58",
       "Frame Advantage": "-9",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "214C": {
       "Input": "↓↙←+C",
       "Damage": "1670",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "12",
       "Active For": "18",
       "Recovery": "29",
       "Overall": "58",
       "Frame Advantage": "+3",
       "Invincibility": "1～3 Throw",
       "Attribute": "",
       "Notes": ""
    },
    "214XA": {
       "Input": "A",
       "Damage": "800",
       "Hit Type": "Overhead",
       "Active On": "14",
       "Active For": "Until Landing",
       "Recovery": "27 Upon Landing",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Dive",
       "Notes": ""
    },
    "214XB": {
       "Input": "B",
       "Damage": "800",
       "Hit Type": "Overhead",
       "Active On": "16",
       "Active For": "Until Landing",
       "Recovery": "25 Upon Landing",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Dive",
       "Notes": ""
    },
    "214XC": {
       "Input": "C",
       "Damage": "800",
       "Hit Type": "Overhead",
       "Active On": "20",
       "Active For": "Until Landing",
       "Recovery": "27 Upon Landing",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Dive",
       "Notes": ""
    },
    "j.236A": {
       "Input": "空中↓↘→+A",
       "Damage": "750",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "20",
       "Active For": "-",
       "Recovery": "10 Upon Landing",
       "Overall": "38",
       "Frame Advantage": "+10",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "硬直差は最低空で出した場合のもの"
    },
    "j.236[A]": {
       "Input": "空中↓↘→+A",
       "Damage": "750",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "24",
       "Active For": "-",
       "Recovery": "12 Upon Landing",
       "Overall": "42",
       "Frame Advantage": "+10",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "硬直差は最低空で出した場合のもの"
    },
    "j.236B": {
       "Input": "空中↓↘→+B",
       "Damage": "750(444)",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "21",
       "Active For": "-",
       "Recovery": "10 Upon Landing",
       "Overall": "40",
       "Frame Advantage": "+17",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "硬直差は最低空で出した場合のもの\n()内のダメージは地面接地後のもの"
    },
    "j.236[B]": {
       "Input": "空中↓↘→+B",
       "Damage": "750(444)",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "28",
       "Active For": "-",
       "Recovery": "12 Upon Landing",
       "Overall": "49",
       "Frame Advantage": "+7",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "硬直差は最低空で出した場合のもの\n()内のダメージは地面接地後のもの"
    },
    "j.236C": {
       "Input": "空中↓↘→+C",
       "Damage": "1523",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "7",
       "Active For": "-",
       "Recovery": "13 Upon Landing",
       "Overall": "52",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "硬直差は最低空で出した場合のもの"
    },
    "IW": {
       "Input": "←↙↓↘→+D",
       "Damage": "3230",
       "Hit Type": "Mid / Mid (Air Blockable)",
       "Active On": "13",
       "Active For": "4",
       "Recovery": "57",
       "Overall": "73",
       "Frame Advantage": "-41",
       "Invincibility": "1～36 All / 37～44 Throw",
       "Attribute": "",
       "Notes": ""
    },
    "IWEXS": {
       "Input": "A+B+C+D",
       "Damage": "3750",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "6",
       "Recovery": "47",
       "Overall": "67",
       "Frame Advantage": "-25",
       "Invincibility": "1～26 All",
       "Attribute": "",
       "Notes": ""
    }
 }