export default {
    "5A": {
       "Input": "",
       "Damage": "180",
       "Hit Type": "Mid",
       "Acitve On": "6",
       "Active For": "2",
       "Recovery": "13",
       "Overall": "20",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "5B": {
       "Input": "",
       "Damage": "480",
       "Hit Type": "Mid",
       "Acitve On": "9",
       "Active For": "2",
       "Recovery": "19",
       "Overall": "29",
       "Frame Advantage": "-4",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "5C": {
       "Input": "",
       "Damage": "580",
       "Hit Type": "Mid",
       "Acitve On": "12",
       "Active For": "4",
       "Recovery": "22",
       "Overall": "37",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "2A": {
       "Input": "",
       "Damage": "140",
       "Hit Type": "Low",
       "Acitve On": "5",
       "Active For": "2",
       "Recovery": "12",
       "Overall": "18",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "Foot",
       "Notes": ""
    },
    "2B": {
       "Input": "",
       "Damage": "420",
       "Hit Type": "Mid",
       "Acitve On": "8",
       "Active For": "3",
       "Recovery": "14",
       "Overall": "24",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attribute": "Foot",
       "Notes": ""
    },
    "2C": {
       "Input": "",
       "Damage": "580",
       "Hit Type": "Low",
       "Acitve On": "9",
       "Active For": "5",
       "Recovery": "23",
       "Overall": "36",
       "Frame Advantage": "-10",
       "Invincibility": "",
       "Attribute": "Foot",
       "Notes": ""
    },
    "j.A": {
       "Input": "",
       "Damage": "140",
       "Hit Type": "Overhead",
       "Acitve On": "8",
       "Active For": "2",
       "Recovery": "17",
       "Overall": "26",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.B": {
       "Input": "",
       "Damage": "370",
       "Hit Type": "Overhead",
       "Acitve On": "9",
       "Active For": "3",
       "Recovery": "18",
       "Overall": "29",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.C": {
       "Input": "",
       "Damage": "520",
       "Hit Type": "Overhead",
       "Acitve On": "12",
       "Active For": "6",
       "Recovery": "12",
       "Overall": "29",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "66B": {
       "Input": "",
       "Damage": "660",
       "Hit Type": "Mid",
       "Acitve On": "10",
       "Active For": "2",
       "Recovery": "12",
       "Overall": "23",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "66C": {
       "Input": "",
       "Damage": "978",
       "Hit Type": "Mid",
       "Acitve On": "12",
       "Active For": "24",
       "Recovery": "23",
       "Overall": "58",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "6B": {
       "Input": "",
       "Damage": "480",
       "Hit Type": "Overhead",
       "Acitve On": "26",
       "Active For": "4",
       "Recovery": "20",
       "Overall": "49",
       "Frame Advantage": "-7",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "3B": {
       "Input": "",
       "Damage": "380",
       "Hit Type": "Mid",
       "Acitve On": "7",
       "Active For": "3",
       "Recovery": "22",
       "Overall": "31",
       "Frame Advantage": "-7",
       "Invincibility": "7～9 Head",
       "Attribute": "",
       "Notes": ""
    },
    "3C": {
       "Input": "",
       "Damage": "720",
       "Hit Type": "Mid",
       "Acitve On": "16",
       "Active For": "4",
       "Recovery": "11",
       "Overall": "30",
       "Frame Advantage": "-3",
       "Invincibility": "8～19 Foot",
       "Attribute": "",
       "Notes": ""
    },
    "4C": {
       "Input": "",
       "Damage": "590",
       "Hit Type": "Mid",
       "Acitve On": "16",
       "Active For": "5",
       "Recovery": "18",
       "Overall": "38",
       "Frame Advantage": "-7",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "j.2C": {
       "Input": "",
       "Damage": "620",
       "Hit Type": "Mid",
       "Acitve On": "14",
       "Active For": "7",
       "Recovery": "5 Upon Landing",
       "Overall": "40",
       "Frame Advantage": "±0",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "FF": {
       "Input": "B+C",
       "Damage": "0",
       "Hit Type": "",
       "Acitve On": "0",
       "Active For": "",
       "Recovery": "5 Upon Landing",
       "Overall": "48",
       "Frame Advantage": "",
       "Invincibility": "1～6 Throw",
       "Attribute": "",
       "Notes": "27Fから空中で行動可能\nレバー入力で移動距離、滞空時間変化可能"
    },
    "FF (Vorpal)": {
       "Input": "B+C",
       "Damage": "0",
       "Hit Type": "",
       "Acitve On": "0",
       "Active For": "",
       "Recovery": "5 Upon Landing",
       "Overall": "47",
       "Frame Advantage": "",
       "Invincibility": "1～3 Throw",
       "Attribute": "",
       "Notes": "21Fから空中で行動可能\nレバー入力で移動距離、滞空時間変化可能"
    },
    "j.FF": {
       "Input": "空中B+C",
       "Damage": "0",
       "Hit Type": "",
       "Acitve On": "0",
       "Active For": "",
       "Recovery": "5 Upon Landing",
       "Overall": "46",
       "Frame Advantage": "",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "25Fから空中で行動可能\nレバー入力で移動距離、滞空時間変化可能"
    },
    "j.FF (Vorpal)": {
       "Input": "空中B+C",
       "Damage": "0",
       "Hit Type": "",
       "Acitve On": "0",
       "Active For": "",
       "Recovery": "5 Upon Landing",
       "Overall": "42",
       "Frame Advantage": "",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "19Fから空中で行動可能\nレバー入力で移動距離、滞空時間変化可能"
    },
    "Throw": {
       "Input": "A+D",
       "Damage": "1570",
       "Hit Type": "Throw",
       "Acitve On": "4",
       "Active For": "1",
       "Recovery": "-",
       "Overall": "26",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Throw",
       "Notes": "投げ無敵時金投げ"
    },
    "236A": {
       "Input": "↓↘→+A",
       "Damage": "860",
       "Hit Type": "Mid",
       "Acitve On": "9",
       "Active For": "4",
       "Recovery": "22",
       "Overall": "34",
       "Frame Advantage": "-4",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "236B": {
       "Input": "↓↘→+B",
       "Damage": "1250",
       "Hit Type": "Mid",
       "Acitve On": "13",
       "Active For": "7",
       "Recovery": "23",
       "Overall": "42",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "236[B]": {
       "Input": "↓↘→+B",
       "Damage": "1620",
       "Hit Type": "Mid",
       "Acitve On": "21",
       "Active For": "9",
       "Recovery": "29",
       "Overall": "58",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "236C": {
       "Input": "↓↘→+C",
       "Damage": "1395",
       "Hit Type": "Mid",
       "Acitve On": "7",
       "Active For": "5",
       "Recovery": "34",
       "Overall": "45",
       "Frame Advantage": "-10",
       "Invincibility": "1～3 Throw",
       "Attribute": "",
       "Notes": ""
    },
    "623A": {
       "Input": "→↓↘+A",
       "Damage": "1136",
       "Hit Type": "Mid",
       "Acitve On": "6",
       "Active For": "3",
       "Recovery": "37",
       "Overall": "45",
       "Frame Advantage": "-20",
       "Invincibility": "1～4 Throw / 5～8 Dive・Head",
       "Attribute": "",
       "Notes": ""
    },
    "623B": {
       "Input": "→↓↘+B",
       "Damage": "1330",
       "Hit Type": "Mid",
       "Acitve On": "6",
       "Active For": "6",
       "Recovery": "49",
       "Overall": "60",
       "Frame Advantage": "-32",
       "Invincibility": "1～4 Throw / 5～11 Dive・Head",
       "Attribute": "",
       "Notes": ""
    },
    "623C": {
       "Input": "→↓↘+C",
       "Damage": "1872",
       "Hit Type": "Mid",
       "Acitve On": "6",
       "Active For": "7",
       "Recovery": "49",
       "Overall": "61",
       "Frame Advantage": "-32",
       "Invincibility": "1～4 All / 5～12 Strike",
       "Attribute": "",
       "Notes": ""
    },
    "214A": {
       "Input": "↓↙←+A",
       "Damage": "777",
       "Hit Type": "Low",
       "Acitve On": "15",
       "Active For": "5",
       "Recovery": "18",
       "Overall": "37",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attribute": "Foot",
       "Notes": ""
    },
    "214B": {
       "Input": "↓↙←+B",
       "Damage": "777",
       "Hit Type": "Mid (Air Blockable)",
       "Acitve On": "18",
       "Active For": "3",
       "Recovery": "14",
       "Overall": "34",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "214C": {
       "Input": "↓↙←+C",
       "Damage": "1785",
       "Hit Type": "Mid (Air Blockable)",
       "Acitve On": "11",
       "Active For": "20",
       "Recovery": "10",
       "Overall": "40",
       "Frame Advantage": "+7",
       "Invincibility": "1～3 Throw",
       "Attribute": "",
       "Notes": ""
    },
    "214XA": {
       "Input": "←+A",
       "Damage": "1066",
       "Hit Type": "Mid (Air Blockable)",
       "Acitve On": "16",
       "Active For": "3(7)2",
       "Recovery": "13",
       "Overall": "40",
       "Frame Advantage": "-11",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "214XB": {
       "Input": "←+BorC",
       "Damage": "777",
       "Hit Type": "Mid",
       "Acitve On": "22",
       "Active For": "4",
       "Recovery": "10",
       "Overall": "35",
       "Frame Advantage": "+4",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "22A": {
       "Input": "↓↓+A",
       "Damage": "740",
       "Hit Type": "Mid (Air Blockable)",
       "Acitve On": "51",
       "Active For": "10",
       "Recovery": "-",
       "Overall": "38",
       "Frame Advantage": "+41",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "30～67まで飛び道具相殺"
    },
    "22B": {
       "Input": "↓↓+B",
       "Damage": "740",
       "Hit Type": "Mid (Air Blockable)",
       "Acitve On": "52",
       "Active For": "10",
       "Recovery": "-",
       "Overall": "40",
       "Frame Advantage": "+40",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "31～68まで飛び道具相殺"
    },
    "22C": {
       "Input": "↓↓+C",
       "Damage": "1935",
       "Hit Type": "Mid (Air Blockable)",
       "Acitve On": "53",
       "Active For": "58",
       "Recovery": "-",
       "Overall": "34",
       "Frame Advantage": "+102",
       "Invincibility": "1～3 Throw",
       "Attribute": "",
       "Notes": "32～110まで飛び道具相殺"
    },
    "j.214A": {
       "Input": "空中↓↙←+A",
       "Damage": "777",
       "Hit Type": "Mid (Air Blockable)",
       "Acitve On": "16",
       "Active For": "4",
       "Recovery": "13 Upon Landing",
       "Overall": "56",
       "Frame Advantage": "-18",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "硬直差はジャンプの昇りから最速で出して立ち状態のハイドにガードさせた場合のもの"
    },
    "j.214B": {
       "Input": "空中↓↙←+B",
       "Damage": "999",
       "Hit Type": "Mid (Air Blockable)",
       "Acitve On": "22",
       "Active For": "5",
       "Recovery": "10 Upon Landing",
       "Overall": "58",
       "Frame Advantage": "-14",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "硬直差はジャンプの昇りから最速で出して立ち状態のハイドにガードさせた場合のもの"
    },
    "j.214C": {
       "Input": "空中↓↙←+C",
       "Damage": "1785",
       "Hit Type": "Mid (Air Blockable)",
       "Acitve On": "15",
       "Active For": "20",
       "Recovery": "13 Upon Landing",
       "Overall": "29",
       "Frame Advantage": "+22",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "硬直差はジャンプの昇りから最速で出して立ち状態のハイドにガードさせた場合のもの"
    },
    "41236C": {
       "Input": "←↙↓↘→+C",
       "Damage": "2070",
       "Hit Type": "Mid (Air Blockable)",
       "Acitve On": "8",
       "Active For": "24(5)4",
       "Recovery": "40",
       "Overall": "80",
       "Frame Advantage": "-17",
       "Invincibility": "1～19 All / f20～23 Throw",
       "Attribute": "",
       "Notes": ""
    },
    "IW": {
       "Input": "←↙↓↘→+D",
       "Damage": "3150",
       "Hit Type": "Mid (Air Blockable)",
       "Acitve On": "12",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "78",
       "Frame Advantage": "-29",
       "Invincibility": "1～26 All / 27～31 Throw",
       "Attribute": "",
       "Notes": ""
    },
    "IWEXS": {
       "Input": "A+B+C+D",
       "Damage": "3750",
       "Hit Type": "Mid (Air Blockable)",
       "Acitve On": "15",
       "Active For": "6",
       "Recovery": "47",
       "Overall": "67",
       "Frame Advantage": "-25",
       "Invincibility": "1～26 All",
       "Attribute": "",
       "Notes": ""
    }
 }