export default {
    "5A": {
       "Command": "",
       "Damage": "180",
       "Hit Type": "Mid",
       "Active On": "6",
       "Active For": "2",
       "Recovery": "13",
       "Total": "20",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "5B": {
       "Command": "",
       "Damage": "480",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "3",
       "Recovery": "18",
       "Total": "30",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "5C": {
       "Command": "",
       "Damage": "1177",
       "Hit Type": "Mid/Low",
       "Active On": "12",
       "Active For": "4(9)3",
       "Recovery": "15",
       "Total": "42",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "5[C]": {
       "Command": "",
       "Damage": "1194",
       "Hit Type": "Mid/Low",
       "Active On": "12",
       "Active For": "4(16)3",
       "Recovery": "17",
       "Total": "51",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "2A": {
       "Command": "",
       "Damage": "150",
       "Hit Type": "Low",
       "Active On": "5",
       "Active For": "2",
       "Recovery": "14",
       "Total": "20",
       "Frame Advantage": "-4",
       "Invincibility": "",
       "Attributes": "Foot",
       "Notes": ""
    },
    "2B": {
       "Command": "",
       "Damage": "490",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "3",
       "Recovery": "18",
       "Total": "29",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attributes": "Foot",
       "Notes": ""
    },
    "2C": {
       "Command": "",
       "Damage": "600",
       "Hit Type": "Low",
       "Active On": "11",
       "Active For": "4",
       "Recovery": "21",
       "Total": "35",
       "Frame Advantage": "-7",
       "Invincibility": "",
       "Attributes": "Foot",
       "Notes": ""
    },
    "j.A": {
       "Command": "",
       "Damage": "140",
       "Hit Type": "Overhead",
       "Active On": "8",
       "Active For": "4",
       "Recovery": "8",
       "Total": "19",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.B": {
       "Command": "",
       "Damage": "420",
       "Hit Type": "Overhead",
       "Active On": "10",
       "Active For": "2",
       "Recovery": "22",
       "Total": "33",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.C": {
       "Command": "",
       "Damage": "590",
       "Hit Type": "Overhead",
       "Active On": "13",
       "Active For": "4",
       "Recovery": "14",
       "Total": "30",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.[C]": {
       "Command": "",
       "Damage": "750",
       "Hit Type": "Overhead",
       "Active On": "20",
       "Active For": "4",
       "Recovery": "16",
       "Total": "39",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "66B": {
       "Command": "",
       "Damage": "749",
       "Hit Type": "Mid",
       "Active On": "14",
       "Active For": "4(4)6",
       "Recovery": "22",
       "Total": "49",
       "Frame Advantage": "-9",
       "Invincibility": "9～13 Foot / 20～27 Head",
       "Attributes": "",
       "Notes": ""
    },
    "66[B]": {
       "Command": "",
       "Damage": "840",
       "Hit Type": "Overhead",
       "Active On": "30",
       "Active For": "6",
       "Recovery": "30",
       "Total": "65",
       "Frame Advantage": "-18",
       "Invincibility": "9～13 Foot / 28～35 Head",
       "Attributes": "",
       "Notes": ""
    },
    "66C": {
       "Command": "",
       "Damage": "540",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "6",
       "Recovery": "24",
       "Total": "41",
       "Frame Advantage": "-9",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "4B": {
       "Command": "",
       "Damage": "480",
       "Hit Type": "Mid",
       "Active On": "15",
       "Active For": "2",
       "Recovery": "35",
       "Total": "51",
       "Frame Advantage": "-19",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "3C": {
       "Command": "",
       "Damage": "600",
       "Hit Type": "Low",
       "Active On": "17",
       "Active For": "10",
       "Recovery": "22",
       "Total": "48",
       "Frame Advantage": "-14",
       "Invincibility": "",
       "Attributes": "Foot",
       "Notes": ""
    },
    "j.2B": {
       "Command": "",
       "Damage": "320",
       "Hit Type": "Overhead",
       "Active On": "8",
       "Active For": "4",
       "Recovery": "29",
       "Total": "40",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": ""
    },
    "j.2[B]": {
       "Command": "",
       "Damage": "420",
       "Hit Type": "Overhead",
       "Active On": "15",
       "Active For": "3",
       "Recovery": "29",
       "Total": "46",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": ""
    },
    "j.4B": {
       "Command": "",
       "Damage": "470",
       "Hit Type": "Overhead",
       "Active On": "10",
       "Active For": "2",
       "Recovery": "12",
       "Total": "23",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Head",
       "Notes": ""
    },
    "5BB": {
       "Command": "",
       "Damage": "480",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "4",
       "Recovery": "19",
       "Total": "34",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "FF": {
       "Command": "B+C",
       "Damage": "1122",
       "Hit Type": "Mid/Mid (Air Blockable)",
       "Active On": "17",
       "Active For": "9(6)5",
       "Recovery": "19",
       "Total": "55",
       "Frame Advantage": "-6",
       "Invincibility": "10～25 Head",
       "Attributes": "",
       "Notes": ""
    },
    "[FF]": {
       "Command": "B+C",
       "Damage": "1850",
       "Hit Type": "Mid/Mid (Air Blockable)",
       "Active On": "17",
       "Active For": "27(5)5",
       "Recovery": "19",
       "Total": "72",
       "Frame Advantage": "-6",
       "Invincibility": "10～43 Head",
       "Attributes": "",
       "Notes": ""
    },
    "FF (Vorpal)": {
       "Command": "B+C",
       "Damage": "1122",
       "Hit Type": "Mid/Mid (Air Blockable)",
       "Active On": "13",
       "Active For": "9(6)5",
       "Recovery": "19",
       "Total": "51",
       "Frame Advantage": "-6",
       "Invincibility": "7～21Head",
       "Attributes": "",
       "Notes": ""
    },
    "[FF] (Vorpal)": {
       "Command": "B+C",
       "Damage": "1850",
       "Hit Type": "Mid/Mid (Air Blockable)",
       "Active On": "13",
       "Active For": "27(5)5",
       "Recovery": "19",
       "Total": "68",
       "Frame Advantage": "-6",
       "Invincibility": "7～39 Head",
       "Attributes": "",
       "Notes": ""
    },
    "Throw": {
       "Command": "A+D",
       "Damage": "1635",
       "Hit Type": "Throw",
       "Active On": "4",
       "Active For": "1",
       "Recovery": "22",
       "Total": "26",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attributes": "Throw",
       "Notes": "投げ無敵時金投げ"
    },
    "236A": {
       "Command": "↓↘→+A",
       "Damage": "800",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "18",
       "Active For": "-",
       "Recovery": "-",
       "Total": "48",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attributes": "Projectile",
       "Notes": "硬直差は密着からガードさせた場合のもの"
    },
    "236[A}": {
       "Command": "↓↘→+A",
       "Damage": "928",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "25",
       "Active For": "-",
       "Recovery": "-",
       "Total": "59",
       "Frame Advantage": "+1",
       "Invincibility": "",
       "Attributes": "Projectile",
       "Notes": "硬直差は密着からガードさせた場合のもの"
    },
    "236B": {
       "Command": "↓↘→+B",
       "Damage": "800",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "14",
       "Active For": "-",
       "Recovery": "-",
       "Total": "50",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Attributes": "Projectile",
       "Notes": "硬直差は密着からガードさせた場合のもの"
    },
    "236[B]": {
       "Command": "↓↘→+B",
       "Damage": "1206",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "21",
       "Active For": "-",
       "Recovery": "-",
       "Total": "61",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attributes": "Projectile",
       "Notes": "硬直差は密着からガードさせた場合のもの"
    },
    "236C": {
       "Command": "↓↘→+C",
       "Damage": "1560",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "9",
       "Active For": "-",
       "Recovery": "-",
       "Total": "39",
       "Frame Advantage": "+19",
       "Invincibility": "1～3 Throw",
       "Attributes": "Projectile",
       "Notes": "硬直差は密着からガードさせた場合のもの"
    },
    "j.236A": {
       "Command": "空中↓↘→+A",
       "Damage": "800",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "16",
       "Active For": "-",
       "Recovery": "Upon Landing 8",
       "Total": "-",
       "Frame Advantage": "-15",
       "Invincibility": "",
       "Attributes": "Projectile",
       "Notes": "硬直差はジャンプの昇りから最速で出した場合のもの"
    },
    "j.236B": {
       "Command": "空中↓↘→+B",
       "Damage": "800",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "16",
       "Active For": "-",
       "Recovery": "Upon Landing 8",
       "Total": "-",
       "Frame Advantage": "+6",
       "Invincibility": "",
       "Attributes": "Projectile",
       "Notes": "硬直差はジャンプの昇りから最速で出した場合のもの"
    },
    "j.236C": {
       "Command": "空中↓↘→+C",
       "Damage": "1560",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "8",
       "Active For": "-",
       "Recovery": "Upon Landing 8",
       "Total": "-",
       "Frame Advantage": "+28",
       "Invincibility": "",
       "Attributes": "Projectile",
       "Notes": "硬直差はジャンプの昇りから最速で出した場合のもの"
    },
    "623A": {
       "Command": "→↓↘+A",
       "Damage": "1224",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "12",
       "Recovery": "27",
       "Total": "47",
       "Frame Advantage": "-8",
       "Invincibility": "5～15 Head / 5～15 Dive",
       "Attributes": "Projectile",
       "Notes": ""
    },
    "623B": {
       "Command": "→↓↘+B",
       "Damage": "1314",
       "Hit Type": "Mid",
       "Active On": "11",
       "Active For": "12",
       "Recovery": "27",
       "Total": "49",
       "Frame Advantage": "-8",
       "Invincibility": "7～17 Head / 7～17 Dive",
       "Attributes": "Projectile",
       "Notes": ""
    },
    "623C": {
       "Command": "→↓↘+C",
       "Damage": "1921",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "12",
       "Recovery": "42",
       "Total": "62",
       "Frame Advantage": "-19",
       "Invincibility": "1～15 All",
       "Attributes": "Projectile",
       "Notes": ""
    },
    "214A": {
       "Command": "↓↙←+A",
       "Damage": "450",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "6",
       "Recovery": "24",
       "Total": "41",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "214AA": {
       "Command": "←+AorBorC",
       "Damage": "1395",
       "Hit Type": "Mid",
       "Active On": "11",
       "Active For": "4(14)5",
       "Recovery": "33",
       "Total": "66",
       "Frame Advantage": "-16",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "214B": {
       "Command": "↓↙←+B",
       "Damage": "450",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "6",
       "Recovery": "29",
       "Total": "44",
       "Frame Advantage": "-10",
       "Invincibility": "7～15 Head /7～15 Dive",
       "Attributes": "",
       "Notes": ""
    },
    "214BB": {
       "Command": "←+AorBorC",
       "Damage": "1395",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "4(14)5",
       "Recovery": "31",
       "Total": "63",
       "Frame Advantage": "-14",
       "Invincibility": "",
       "Attributes": "",
       "Notes": ""
    },
    "214C": {
       "Command": "↓↙←+C",
       "Damage": "1917",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "6(12)5(9)4(11)5(14)5",
       "Recovery": "44",
       "Total": "123",
       "Frame Advantage": "-24",
       "Invincibility": "1～3 Throw",
       "Attributes": "",
       "Notes": ""
    },
    "22A": {
       "Command": "↓↓+A",
       "Damage": "1203",
       "Hit Type": "Mid/Mid (Air Blockable)",
       "Active On": "25",
       "Active For": "12",
       "Recovery": "29",
       "Total": "65",
       "Frame Advantage": "-28",
       "Invincibility": "1～7 Throw",
       "Attributes": "Projectile",
       "Notes": ""
    },
    "22B": {
       "Command": "↓↓+B",
       "Damage": "1435",
       "Hit Type": "Mid/Mid (Air Blockable)/Mid (Air Blockable)",
       "Active On": "28",
       "Active For": "14",
       "Recovery": "29",
       "Total": "70",
       "Frame Advantage": "-15",
       "Invincibility": "1～10 Throw",
       "Attributes": "Projectile",
       "Notes": ""
    },
    "22C": {
       "Command": "↓↓+C",
       "Damage": "1951",
       "Hit Type": "Overhead/Overhead/Mid (Air Blockable)",
       "Active On": "23",
       "Active For": "12",
       "Recovery": "30",
       "Total": "64",
       "Frame Advantage": "-16",
       "Invincibility": "1～6 Throw",
       "Attributes": "Projectile",
       "Notes": ""
    },
    "IW": {
       "Command": "←↙↓↘→+D",
       "Damage": "3133",
       "Hit Type": "Mid",
       "Active On": "13",
       "Active For": "8(27)3(4)13",
       "Recovery": "30",
       "Total": "97",
       "Frame Advantage": "-22",
       "Invincibility": "1～31All / 32～59 Strike",
       "Attributes": "",
       "Notes": ""
    },
    "IWEXS": {
       "Command": "A+B+C+D",
       "Damage": "3760",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "6",
       "Recovery": "47",
       "Total": "67",
       "Frame Advantage": "-25",
       "Invincibility": "1～26 All",
       "Attributes": "",
       "Notes": ""
    }
 }