export default {
    "5A": {
       "Input": "",
       "Damage": "170",
       "Hit Type": "Mid",
       "Active On": "5",
       "Active For": "2",
       "Recovery": "12",
       "Overall": "18",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "5B": {
       "Input": "",
       "Damage": "415",
       "Hit Type": "Mid",
       "Active On": "7",
       "Active For": "5",
       "Recovery": "15",
       "Overall": "26",
       "Frame Advantage": "-4",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "5C": {
       "Input": "",
       "Damage": "350",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "4",
       "Recovery": "17",
       "Overall": "30",
       "Frame Advantage": "-9",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "2A": {
       "Input": "",
       "Damage": "140",
       "Hit Type": "Low",
       "Active On": "5",
       "Active For": "2",
       "Recovery": "12",
       "Overall": "18",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "Foot",
       "Notes": ""
    },
    "2B": {
       "Input": "",
       "Damage": "410",
       "Hit Type": "Low",
       "Active On": "6",
       "Active For": "5",
       "Recovery": "13",
       "Overall": "23",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "Foot",
       "Notes": ""
    },
    "2C": {
       "Input": "",
       "Damage": "543",
       "Hit Type": "Low",
       "Active On": "8",
       "Active For": "2(2)2",
       "Recovery": "17",
       "Overall": "30",
       "Frame Advantage": "-1",
       "Invincibility": "",
       "Attribute": "Foot",
       "Notes": ""
    },
    "j.A": {
       "Input": "",
       "Damage": "140",
       "Hit Type": "Overhead",
       "Active On": "8",
       "Active For": "4",
       "Recovery": "12",
       "Overall": "23",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.B": {
       "Input": "",
       "Damage": "410",
       "Hit Type": "Overhead",
       "Active On": "10",
       "Active For": "3",
       "Recovery": "18",
       "Overall": "30",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.C": {
       "Input": "",
       "Damage": "510",
       "Hit Type": "Overhead",
       "Active On": "12",
       "Active For": "3",
       "Recovery": "18",
       "Overall": "32",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "66B": {
       "Input": "",
       "Damage": "608",
       "Hit Type": "Mid",
       "Active On": "7",
       "Active For": "2(4)4",
       "Recovery": "14",
       "Overall": "30",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "66C": {
       "Input": "",
       "Damage": "690",
       "Hit Type": "Mid",
       "Active On": "11",
       "Active For": "4",
       "Recovery": "16",
       "Overall": "30",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "Fastfall": {
       "Input": "空中↓↓",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "16 Upon Landing",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "j.22~6X": {
       "Input": "→+AorBorC",
       "Damage": "810",
       "Hit Type": "Mid",
       "Active On": "16",
       "Active For": "4",
       "Recovery": "21",
       "Overall": "40",
       "Frame Advantage": "-7",
       "Invincibility": "4～19 Throw",
       "Attribute": "",
       "Notes": ""
    },
    "Air Backdash": {
       "Input": "空中←←",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "12 Upon Landing",
       "Overall": "17",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "18Fから空中で行動可能"
    },
    "3B": {
       "Input": "",
       "Damage": "430",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "4",
       "Recovery": "17",
       "Overall": "30",
       "Frame Advantage": "-3",
       "Invincibility": "8～13 Head",
       "Attribute": "",
       "Notes": ""
    },
    "6C": {
       "Input": "",
       "Damage": "600",
       "Hit Type": "Overhead",
       "Active On": "28",
       "Active For": "1",
       "Recovery": "16",
       "Overall": "44",
       "Frame Advantage": "-5",
       "Invincibility": "15～28 Foot",
       "Attribute": "",
       "Notes": ""
    },
    "3C": {
       "Input": "",
       "Damage": "590",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "3",
       "Recovery": "27",
       "Overall": "39",
       "Frame Advantage": "-12",
       "Invincibility": "8～12 Head",
       "Attribute": "",
       "Notes": ""
    },
    "j.2C": {
       "Input": "",
       "Damage": "420",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "Until Landing",
       "Recovery": "13 upon landing",
       "Overall": "22",
       "Frame Advantage": "-1",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "ヒットorガード後14Fから空中で行動可"
    },
    "j.6C": {
       "Input": "",
       "Damage": "510",
       "Hit Type": "Overhead",
       "Active On": "26",
       "Active For": "6",
       "Recovery": "17",
       "Overall": "44",
       "Frame Advantage": "-9",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "低空で出した場合は高さに応じて発生が高速化（最低空で23）\n硬直差は最低空でガードさせた場合のもの"
    },
    "5CC": {
       "Input": "",
       "Damage": "388",
       "Hit Type": "Mid",
       "Active On": "4",
       "Active For": "4",
       "Recovery": "21",
       "Overall": "28",
       "Frame Advantage": "-7",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "FF": {
       "Input": "B+C",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "29",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "[FF]": {
       "Input": "B+C",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "38",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "Throw": {
       "Input": "A+D",
       "Damage": "1575",
       "Hit Type": "Throw",
       "Active On": "4",
       "Active For": "1",
       "Recovery": "22",
       "Overall": "26",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Throw",
       "Notes": "投げ無敵時金投げ"
    },
    "236A": {
       "Input": "↓↘→+A",
       "Damage": "810",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "105",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "35",
       "Frame Advantage": "+64",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "淵侵のジオメトリー(インクリース)使用後は発生が65"
    },
    "236B": {
       "Input": "↓↘→+B",
       "Damage": "810",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "105",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "35",
       "Frame Advantage": "+64",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "淵侵のジオメトリー(インクリース)使用後は発生が65"
    },
    "236C": {
       "Input": "↓↘→+C",
       "Damage": "1466",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "111",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "53",
       "Frame Advantage": "+46",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "淵侵のジオメトリー(インクリース)使用後は発生が31"
    },
    "j.236A": {
       "Input": "空中↓↘→+A",
       "Damage": "810",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "117",
       "Active For": "-",
       "Recovery": "9 upon landing",
       "Overall": "37",
       "Frame Advantage": "+63",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "淵侵のジオメトリー(インクリース)使用後は発生が77"
    },
    "j.236B": {
       "Input": "空中↓↘→+B",
       "Damage": "810",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "118",
       "Active For": "-",
       "Recovery": "9 upon landing",
       "Overall": "38",
       "Frame Advantage": "+62",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "淵侵のジオメトリー(インクリース)使用後は発生が78"
    },
    "j.236C": {
       "Input": "空中↓↘→+C",
       "Damage": "1466",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "137",
       "Active For": "-",
       "Recovery": "10 upon landing",
       "Overall": "58",
       "Frame Advantage": "+42",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "淵侵のジオメトリー(インクリース)使用後は発生が47"
    },
    "623A": {
       "Input": "→↓↘+A",
       "Damage": "810",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "12",
       "Active For": "8",
       "Recovery": "21",
       "Overall": "40",
       "Frame Advantage": "-7",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "硬直差は密着でガードさせた場合のもの"
    },
    "623B": {
       "Input": "→↓↘+B",
       "Damage": "810",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "9",
       "Recovery": "25",
       "Overall": "48",
       "Frame Advantage": "-12",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "硬直差は密着でガードさせた場合のもの"
    },
    "623C": {
       "Input": "→↓↘+C",
       "Damage": "2075",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "11",
       "Active For": "7",
       "Recovery": "32",
       "Overall": "49",
       "Frame Advantage": "-17",
       "Invincibility": "1～13 All",
       "Attribute": "",
       "Notes": "硬直差は密着でガードさせた場合のもの"
    },
    "214A": {
       "Input": "↓↙←+A",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "0",
       "Overall": "46",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "214B": {
       "Input": "↓↙←+B",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "3 upon landing",
       "Overall": "36",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "動作後は空中で行動可"
    },
    "214C": {
       "Input": "↓↙←+C",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "3 upon landing",
       "Overall": "31",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "動作後は空中で行動可"
    },
    "214XA": {
       "Input": "A",
       "Damage": "789\n(1192)",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "16+1",
       "Active For": "6",
       "Recovery": "0",
       "Overall": "35",
       "Frame Advantage": "+64",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "発生は消失のコンフュージョンから最速で出した場合のもの\n17～26まで当て身投げ判定\n()内のダメージは当身投げ成立時のもの\n攻撃判定は連続技中のみヒットする"
    },
    "214XB": {
       "Input": "B",
       "Damage": "819",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "16+1",
       "Active For": "6",
       "Recovery": "3 upon landing",
       "Overall": "41",
       "Frame Advantage": "+80",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "発生は消失のコンフュージョンから最速で出した場合のもの\n攻撃判定は連続技中のみヒットする"
    },
    "214XC": {
       "Input": "C",
       "Damage": "1563",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "16+1",
       "Active For": "6(21)2",
       "Recovery": "26",
       "Overall": "65",
       "Frame Advantage": "-11",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "発生は消失のコンフュージョンから最速で出した場合のもの\n初段は連続技中のみヒットする"
    },
    "214XX8X": {
       "Input": "↑+AorBorC",
       "Damage": "1359",
       "Hit Type": "Mid (Air Blockable) / Overhead",
       "Active On": "13+1",
       "Active For": "6(21)2",
       "Recovery": "22 upon landing",
       "Overall": "61",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "発生は消失のコンフュージョンから最速で出した場合のもの\n初段は連続技中のみヒットする"
    },
    "632146A": {
       "Input": "→↘↓↙←→+A",
       "Damage": "1050",
       "Hit Type": "Throw",
       "Active On": "6",
       "Active For": "1",
       "Recovery": "24",
       "Overall": "30",
       "Frame Advantage": "-",
       "Invincibility": "1～6 Throw",
       "Attribute": "Throw",
       "Notes": ""
    },
    "632146B": {
       "Input": "→↘↓↙←→+B",
       "Damage": "1050",
       "Hit Type": "Throw",
       "Active On": "8",
       "Active For": "2",
       "Recovery": "21",
       "Overall": "30",
       "Frame Advantage": "-",
       "Invincibility": "7～9 Head / 7～9 Dive",
       "Attribute": "Throw",
       "Notes": ""
    },
    "632146C": {
       "Input": "→↘↓↙←→+C",
       "Damage": "1393",
       "Hit Type": "Throw",
       "Active On": "6",
       "Active For": "1(1)2",
       "Recovery": "21",
       "Overall": "30",
       "Frame Advantage": "-",
       "Invincibility": "1～7 All",
       "Attribute": "Throw",
       "Notes": "二段目は連続技中のみヒットする"
    },
    "j.214A": {
       "Input": "空中↓↙←+A",
       "Damage": "732",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "9",
       "Active For": "Up to 2 frames after landing",
       "Recovery": "23 upon landing",
       "Overall": "33",
       "Frame Advantage": "-7",
       "Invincibility": "",
       "Attribute": "Dive",
       "Notes": ""
    },
    "j.214B": {
       "Input": "空中↓↙←+B",
       "Damage": "1450",
       "Hit Type": "Throw",
       "Active On": "30",
       "Active For": "Until landing",
       "Recovery": "23 upon landing",
       "Overall": "52",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Throw",
       "Notes": ""
    },
    "j.214C": {
       "Input": "空中↓↙←+C",
       "Damage": "1810",
       "Hit Type": "Overhead",
       "Active On": "8",
       "Active For": "Up to 2 frames after landing",
       "Recovery": "27 upon landing",
       "Overall": "36",
       "Frame Advantage": "-6",
       "Invincibility": "1～Landing All",
       "Attribute": "",
       "Notes": ""
    },
    "IW": {
       "Input": "←↙↓↘→+D",
       "Damage": "3269",
       "Hit Type": "Mid",
       "Active On": "13",
       "Active For": "34",
       "Recovery": "10",
       "Overall": "56",
       "Frame Advantage": "-21",
       "Invincibility": "1～16 All /17～46 Strike",
       "Attribute": "",
       "Notes": ""
    },
    "IWEXS": {
       "Input": "A+B+C+D",
       "Damage": "3780",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "6",
       "Recovery": "47",
       "Overall": "67",
       "Frame Advantage": "-25",
       "Invincibility": "1～26 All",
       "Attribute": "",
       "Notes": ""
    }
 }