module.exports = {
    "5A": {
       "Input": "",
       "Damage": "160",
       "Hit Type": "Mid",
       "Active On": "6",
       "Active For": "3",
       "Recovery": "12",
       "Overall": "20",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "5B": {
       "Input": "",
       "Damage": "422",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "9",
       "Recovery": "18",
       "Overall": "38",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "5C": {
       "Input": "",
       "Damage": "690",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "5",
       "Recovery": "22",
       "Overall": "38",
       "Frame Advantage": "-11",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "2A": {
       "Input": "",
       "Damage": "140",
       "Hit Type": "Mid",
       "Active On": "6",
       "Active For": "3",
       "Recovery": "12",
       "Overall": "20",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "2B": {
       "Input": "",
       "Damage": "399",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "9",
       "Recovery": "29",
       "Overall": "47",
       "Frame Advantage": "-13",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "2C": {
       "Input": "",
       "Damage": "621",
       "Hit Type": "Low",
       "Active On": "10",
       "Active For": "13",
       "Recovery": "24",
       "Overall": "46",
       "Frame Advantage": "-16",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "j.A": {
       "Input": "",
       "Damage": "140",
       "Hit Type": "Overhead",
       "Active On": "6",
       "Active For": "3",
       "Recovery": "21",
       "Overall": "29",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "備考": "Behaviour in air allowed after use"
    },
    "j.B": {
       "Input": "",
       "Damage": "410",
       "Hit Type": "Overhead",
       "Active On": "11",
       "Active For": "6",
       "Recovery": "18",
       "Overall": "34",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "備考": "Behaviour in air allowed after use"
    },
    "j.C": {
       "Input": "",
       "Damage": "478",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "10",
       "Recovery": "8",
       "Overall": "29",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "備考": "Behaviour in air allowed after use"
    },
    "66B": {
       "Input": "",
       "Damage": "650",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "2",
       "Recovery": "12",
       "Overall": "23",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "66C": {
       "Input": "",
       "Damage": "930",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "18",
       "Recovery": "20",
       "Overall": "49",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attribute": "",
       "備考": "硬直差は最終段をガードさせた場合のもの"
    },
    "5BB": {
       "Input": "",
       "Damage": "415",
       "Hit Type": "Mid",
       "Active On": "3",
       "Active For": "6",
       "Recovery": "25",
       "Overall": "33",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "2BB": {
       "Input": "",
       "Damage": "418",
       "Hit Type": "Mid",
       "Active On": "3",
       "Active For": "6",
       "Recovery": "25",
       "Overall": "33",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "j.AB (Leviosa)": {
       "Input": "空中A+B",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "32",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "",
       "備考": "動作後は空中で行動可"
    },
    "FF": {
       "Input": "B+C",
       "Damage": "845",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "3(3)2(5)6",
       "Recovery": "14",
       "Overall": "42",
       "Frame Advantage": "-4",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "[FF]": {
       "Input": "B+C",
       "Damage": "1365",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "5(13)16",
       "Recovery": "17",
       "Overall": "60",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "[FF8]": {
       "Input": "↑",
       "Damage": "1545",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "5(10)14(2)4",
       "Recovery": "14 Upon Landing",
       "Overall": "68",
       "Frame Advantage": "-24",
       "Invincibility": "",
       "Attribute": "",
       "備考": "硬直差は上派生後、レバー↓入力で低空でガードさせた場合のもの"
    },
    "2FF": {
       "Input": "↓+B+C",
       "Damage": "787",
       "Hit Type": "Low",
       "Active On": "12",
       "Active For": "17",
       "Recovery": "18",
       "Overall": "46",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attribute": "",
       "備考": ""
    },
    "j.FF": {
       "Input": "空中B+C",
       "Damage": "499",
       "Hit Type": "Mid",
       "Active On": "14",
       "Active For": "6(2)4",
       "Recovery": "9 Upon Landing",
       "Overall": "51",
       "Frame Advantage": "-12",
       "Invincibility": "",
       "Attribute": "",
       "備考": "硬直差はレバー↓入力で低空でガードさせた場合のもの"
    },
    "j.[FF]": {
       "Input": "空中B+C",
       "Damage": "1290",
       "Hit Type": "Mid",
       "Active On": "13",
       "Active For": "16(5)14(2)4",
       "Recovery": "14 Upon Landing",
       "Overall": "97",
       "Frame Advantage": "-24",
       "Invincibility": "",
       "Attribute": "",
       "備考": "硬直差はレバー↓入力で低空でガードさせた場合のもの"
    },
    "Throw": {
       "Input": "A+D",
       "Damage": "1580",
       "Hit Type": "Throw",
       "Active On": "4",
       "Active For": "1",
       "Recovery": "22",
       "Overall": "26",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Throw",
       "備考": "投げ無敵時金投げ"
    },
    "[4]6A": {
       "Input": "←タメ→+A",
       "Damage": "819",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "21",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "39",
       "Frame Advantage": "+8",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": ""
    },
    "[4]6B": {
       "Input": "←タメ→+B",
       "Damage": "819",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "19",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "51",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": ""
    },
    "[4]6C": {
       "Input": "←タメ→+C",
       "Damage": "1258",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "38",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "67",
       "Frame Advantage": "+68",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": "発射前にCSした時のダメージは1236"
    },
    "j.[4]6A": {
       "Input": "空中←タメ→+A",
       "Damage": "819",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "13",
       "Active For": "-",
       "Recovery": "29\n(0 Upon Landing)",
       "Overall": "42",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": "動作後は空中で行動可\n硬直差はジャンプの昇りから出してガードさせた場合のもの"
    },
    "j.[4]6B": {
       "Input": "空中←タメ→+B",
       "Damage": "819",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "13",
       "Active For": "-",
       "Recovery": "29\n(0 Upon Landing)",
       "Overall": "42",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": "動作後は空中で行動可\n硬直差はジャンプの昇りから出してガードさせた場合のもの"
    },
    "j.[4]6C": {
       "Input": "空中←タメ→+C",
       "Damage": "1258",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "36",
       "Active For": "-",
       "Recovery": "23\n(0 Upon Landing)",
       "Overall": "59",
       "Frame Advantage": "+75",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": "発射前にCSした時のダメージは1236\n動作後は空中で行動可\n硬直差はジャンプの昇りから出してガードさせた場合のもの"
    },
    "[2]8A": {
       "Input": "↓タメ↑+A",
       "Damage": "1530",
       "Hit Type": "Mid",
       "Active On": "4",
       "Active For": "3(3)8",
       "Recovery": "33",
       "Overall": "50",
       "Frame Advantage": "-16",
       "Invincibility": "1～4 All / 5～17 Strike",
       "Attribute": "",
       "備考": ""
    },
    "[2]8B": {
       "Input": "↓タメ↑+B",
       "Damage": "1811",
       "Hit Type": "Mid",
       "Active On": "4",
       "Active For": "3(3)8",
       "Recovery": "44",
       "Overall": "61",
       "Frame Advantage": "-26",
       "Invincibility": "1～4 All / 5～17 Strike",
       "Attribute": "",
       "備考": ""
    },
    "[2]8C": {
       "Input": "↓タメ↑+C",
       "Damage": "2014\n(2121)",
       "Hit Type": "Mid/Mid (Air Blockable)/Mid",
       "Active On": "4",
       "Active For": "3(3)8(16)13(7)3(3)10",
       "Recovery": "54",
       "Overall": "123",
       "Frame Advantage": "-46",
       "Invincibility": "1～46 All / 47～53 Strike / 54～109 All",
       "Attribute": "",
       "備考": "ダメージは18ヒット時のもの、()内のダメージは19ヒット時のもの\n硬直差は最終段をガードさせた場合のもの"
    },
    "[6]4A": {
       "Input": "→タメ←+A",
       "Damage": "1250",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "14",
       "Active For": "5",
       "Recovery": "25",
       "Overall": "43",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": ""
    },
    "[6]4B": {
       "Input": "→タメ←+B",
       "Damage": "1250",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "5",
       "Recovery": "22",
       "Overall": "41",
       "Frame Advantage": "±0",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": ""
    },
    "[6]4C": {
       "Input": "→タメ←+C",
       "Damage": "1532",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "8",
       "Active For": "25",
       "Recovery": "29",
       "Overall": "61",
       "Frame Advantage": "+7",
       "Invincibility": "1～3 Throw",
       "Attribute": "Projectile",
       "備考": ""
    },
    "j.[6]4A": {
       "Input": "空中→タメ←+A",
       "Damage": "1250",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "14",
       "Active For": "5",
       "Recovery": "27\n(0 Upon Landing)",
       "Overall": "45",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": "動作後は空中で行動可\n硬直差はジャンプの昇りから出してガードさせた場合のもの"
    },
    "j.[6]4B": {
       "Input": "空中→タメ←+B",
       "Damage": "1250",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "17",
       "Active For": "5",
       "Recovery": "42\n(0 Upon Landing)",
       "Overall": "63",
       "Frame Advantage": "-20",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": "動作後は空中で行動可\n硬直差はジャンプの昇りから出してガードさせた場合のもの"
    },
    "j.[6]4C": {
       "Input": "空中→タメ←+C",
       "Damage": "1450",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "8",
       "Active For": "25",
       "Recovery": "27\n(0 Upon Landing)",
       "Overall": "59",
       "Frame Advantage": "+11",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": "動作後は空中で行動可\n硬直差はジャンプの昇りから出してガードさせた場合のもの"
    },
    "{A}": {
       "Input": "Aタメて離す",
       "Damage": "1484",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "0",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "26",
       "Frame Advantage": "+73",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": ""
    },
    "{B}": {
       "Input": "Bタメて離す",
       "Damage": "1484",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "0",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "26",
       "Frame Advantage": "+73",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": ""
    },
    "{C}": {
       "Input": "Cタメて離す",
       "Damage": "1484",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "0",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "26",
       "Frame Advantage": "+73",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": ""
    },
    "2{A}": {
       "Input": "Aタメてしゃがみで離す",
       "Damage": "1484",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "0",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "26",
       "Frame Advantage": "+73",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": ""
    },
    "2{B}": {
       "Input": "Bタメてしゃがみで離す",
       "Damage": "1484",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "0",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "26",
       "Frame Advantage": "+73",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": ""
    },
    "2{C}": {
       "Input": "Cタメてしゃがみで離す",
       "Damage": "1484",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "0",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "26",
       "Frame Advantage": "+73",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": ""
    },
    "j.{A}": {
       "Input": "Aタメて空中で離す",
       "Damage": "1484",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "0",
       "Active For": "-",
       "Recovery": "Until Landing",
       "Overall": "32",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": "動作後は空中で行動可"
    },
    "j.{B}": {
       "Input": "Bタメて空中で離す",
       "Damage": "1484",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "0",
       "Active For": "-",
       "Recovery": "Until Landing",
       "Overall": "32",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": "動作後は空中で行動可"
    },
    "j.{C}": {
       "Input": "Cタメて空中で離す",
       "Damage": "1484",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "0",
       "Active For": "-",
       "Recovery": "Until Landing",
       "Overall": "32",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": "動作後は空中で行動可"
    },
    "j.[8]2A": {
       "Input": "空中↑タメ↓+A",
       "Damage": "1284",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "7",
       "Active For": "3 Upon Landing",
       "Recovery": "18",
       "Overall": "22",
       "Frame Advantage": "+2",
       "Invincibility": "",
       "Attribute": "Dive",
       "備考": "ダメージは立ち状態のハイドにヒットさせた場合のもの"
    },
    "j.[8]2B": {
       "Input": "空中↑タメ↓+B",
       "Damage": "1498",
       "Hit Type": "Overhea / Mid",
       "Active On": "20",
       "Active For": "3 Upon Landing(20)6",
       "Recovery": "22",
       "Overall": "51",
       "Frame Advantage": "-7",
       "Invincibility": "",
       "Attribute": "Dive",
       "備考": "ダメージは立ち状態のハイドにヒットさせた場合のもの"
    },
    "j.[8]2C": {
       "Input": "空中↑タメ↓+C",
       "Damage": "1596",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "5",
       "Active For": "19(12)5(28)7",
       "Recovery": "18",
       "Overall": "-",
       "Frame Advantage": "-1",
       "Invincibility": "1～3 All / 4～Until Landing・Strike",
       "Attribute": "",
       "備考": "ダメージは立ち状態のハイドにヒットさせた場合のもの"
    },
    "{ABC}": {
       "Input": "AorBorCタメて離す",
       "Damage": "920",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "13",
       "Active For": "10",
       "Recovery": "9 Upon Landing",
       "Overall": "70",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Projectile",
       "備考": ""
    },
    "IW": {
       "Input": "←↙↓↘→+D",
       "Damage": "3066",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "12",
       "Active For": "141",
       "Recovery": "66",
       "Overall": "218",
       "Frame Advantage": "-33",
       "Invincibility": "1～147 All",
       "Attribute": "",
       "備考": ""
    },
    "IWEXS": {
       "Input": "A+B+C+D",
       "Damage": "3775",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "6",
       "Recovery": "47",
       "Overall": "67",
       "Frame Advantage": "-25",
       "Invincibility": "1～26 All",
       "Attribute": "",
       "備考": ""
    }
 }