module.exports = {
    "5A": {
       "Input": "",
       "Damage": "180",
       "Hit Type": "",
       "Active On": "5",
       "Active For": "2",
       "Recovery": "12",
       "Overall": "18",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Notes": ""
    },
    "5B": {
       "Input": "",
       "Damage": "480",
       "Hit Type": "",
       "Active On": "7",
       "Active For": "3",
       "Recovery": "18",
       "Overall": "27",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Notes": ""
    },
    "5C": {
       "Input": "",
       "Damage": "680",
       "Hit Type": "",
       "Active On": "12",
       "Active For": "4",
       "Recovery": "25",
       "Overall": "40",
       "Frame Advantage": "-11",
       "Invincibility": "",
       "Notes": ""
    },
    "5[C]": {
       "Input": "",
       "Damage": "780",
       "Hit Type": "",
       "Active On": "20",
       "Active For": "4",
       "Recovery": "28",
       "Overall": "51",
       "Frame Advantage": "-14",
       "Invincibility": "",
       "Notes": ""
    },
    "2A": {
       "Input": "",
       "Damage": "150",
       "Hit Type": "Foot",
       "Active On": "5",
       "Active For": "2",
       "Recovery": "12",
       "Overall": "18",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Notes": ""
    },
    "2B": {
       "Input": "",
       "Damage": "490",
       "Hit Type": "Foot",
       "Active On": "9",
       "Active For": "2",
       "Recovery": "19",
       "Overall": "29",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Notes": ""
    },
    "2C": {
       "Input": "",
       "Damage": "620",
       "Hit Type": "Foot",
       "Active On": "9",
       "Active For": "5",
       "Recovery": "18",
       "Overall": "31",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Notes": ""
    },
    "j.A": {
       "Input": "",
       "Damage": "140",
       "Hit Type": "Head",
       "Active On": "8",
       "Active For": "3",
       "Recovery": "17",
       "Overall": "27",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.B": {
       "Input": "",
       "Damage": "420",
       "Hit Type": "Head",
       "Active On": "9",
       "Active For": "4",
       "Recovery": "18",
       "Overall": "30",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.C": {
       "Input": "",
       "Damage": "590",
       "Hit Type": "Head",
       "Active On": "12",
       "Active For": "3",
       "Recovery": "18",
       "Overall": "32",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.[C]": {
       "Input": "",
       "Damage": "750",
       "Hit Type": "Head",
       "Active On": "20",
       "Active For": "3",
       "Recovery": "18",
       "Overall": "40",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Notes": "Behaviour in air allowed after use"
    },
    "66B": {
       "Input": "",
       "Damage": "610",
       "Hit Type": "",
       "Active On": "9",
       "Active For": "2",
       "Recovery": "13",
       "Overall": "23",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Notes": ""
    },
    "66C": {
       "Input": "",
       "Damage": "850",
       "Hit Type": "Foot",
       "Active On": "10",
       "Active For": "3",
       "Recovery": "26",
       "Overall": "38",
       "Frame Advantage": "-11",
       "Invincibility": "",
       "Notes": ""
    },
    "2AD": {
       "Input": "↓+A+D",
       "Damage": "1090",
       "Hit Type": "",
       "Active On": "10",
       "Active For": "3",
       "Recovery": "17",
       "Overall": "29",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Notes": ""
    },
    "6B": {
       "Input": "",
       "Damage": "1087",
       "Hit Type": "",
       "Active On": "8",
       "Active For": "2(8)3",
       "Recovery": "24",
       "Overall": "44",
       "Frame Advantage": "-9",
       "Invincibility": "",
       "Notes": ""
    },
    "6C": {
       "Input": "",
       "Damage": "690",
       "Hit Type": "",
       "Active On": "24",
       "Active For": "4",
       "Recovery": "19",
       "Overall": "46",
       "Frame Advantage": "-5",
       "Invincibility": "10～27 Foot",
       "Notes": "持続1～2Fは連続技中のみヒットする。\n通常は持続3～4F目のみヒットする。"
    },
    "3C": {
       "Input": "",
       "Damage": "660",
       "Hit Type": "",
       "Active On": "9",
       "Active For": "3",
       "Recovery": "26",
       "Overall": "37",
       "Frame Advantage": "-11",
       "Invincibility": "7～11 Head",
       "Notes": ""
    },
    "j.2C": {
       "Input": "",
       "Damage": "650",
       "Hit Type": "Head",
       "Active On": "14",
       "Active For": "Until Landing",
       "Recovery": "13f After Landing",
       "Overall": "-",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Notes": "硬直差は密着でジャンプの昇りから最速で出してガードさせた場合のもの"
    },
    "FF": {
       "Input": "B+C",
       "Damage": "720",
       "Hit Type": "",
       "Active On": "15",
       "Active For": "2",
       "Recovery": "27",
       "Overall": "43",
       "Frame Advantage": "-2",
       "Invincibility": "3～16 Projectile",
       "Notes": "3～16弾属性相殺判定あり\n飛び道具を相殺すると弾属性無敵消失\nローエンガルデで強化中は7～14打撃相殺判定あり"
    },
    "[FF]": {
       "Input": "B+C",
       "Damage": "1050",
       "Hit Type": "",
       "Active On": "28",
       "Active For": "2",
       "Recovery": "36",
       "Overall": "65",
       "Frame Advantage": "-10",
       "Invincibility": "3～29 Projectile",
       "Notes": "3～29弾属性相殺判定あり\n飛び道具を相殺すると弾属性無敵消失\nローエンガルデで強化中は7～27打撃相殺判定あり"
    },
    "Throw": {
       "Input": "A+D",
       "Damage": "1644",
       "Hit Type": "Throw",
       "Active On": "4",
       "Active For": "1",
       "Recovery": "22",
       "Overall": "26",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Notes": "投げ無敵時金投げ"
    },
    "236A": {
       "Input": "↓↘→+A",
       "Damage": "1200",
       "Hit Type": "",
       "Active On": "10",
       "Active For": "16",
       "Recovery": "25",
       "Overall": "50",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Notes": ""
    },
    "236A (Inst)": {
       "Input": "↓↘→+A",
       "Damage": "1236",
       "Hit Type": "",
       "Active On": "10",
       "Active For": "16",
       "Recovery": "25",
       "Overall": "50",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Notes": ""
    },
    "236B": {
       "Input": "↓↘→+B",
       "Damage": "1258",
       "Hit Type": "",
       "Active On": "10",
       "Active For": "12",
       "Recovery": "35",
       "Overall": "56",
       "Frame Advantage": "-14",
       "Invincibility": "8～21 Head",
       "Notes": "硬直差は密着から立ち状態のハイドにガードさせた場合のもの"
    },
    "236B (Inst)": {
       "Input": "↓↘→+B",
       "Damage": "1294",
       "Hit Type": "",
       "Active On": "10",
       "Active For": "12",
       "Recovery": "35",
       "Overall": "56",
       "Frame Advantage": "-14",
       "Invincibility": "8～21 Head",
       "Notes": "硬直差は密着から立ち状態のハイドにガードさせた場合のもの"
    },
    "236C": {
       "Input": "↓↘→+C",
       "Damage": "1890",
       "Hit Type": "",
       "Active On": "7",
       "Active For": "12",
       "Recovery": "38",
       "Overall": "56",
       "Frame Advantage": "-22",
       "Invincibility": "1～3 Throw / 7～21 Head",
       "Notes": "硬直差は密着から立ち状態のハイドにガードさせた場合のもの"
    },
    "236XX": {
       "Input": "AorBorC",
       "Damage": "576",
       "Hit Type": "",
       "Active On": "7",
       "Active For": "9",
       "Recovery": "着地9",
       "Overall": "-",
       "Frame Advantage": "-13",
       "Invincibility": "",
       "Notes": "硬直差はA版からの派生で出した場合のもの"
    },
    "236XX (Inst)": {
       "Input": "AorBorC",
       "Damage": "727",
       "Hit Type": "",
       "Active On": "7",
       "Active For": "15",
       "Recovery": "着地9",
       "Overall": "-",
       "Frame Advantage": "-9",
       "Invincibility": "",
       "Notes": "硬直差はA版からの派生で出した場合のもの\n使用後、剣強化状態終了"
    },
    "623A": {
       "Input": "→↓↘+A",
       "Damage": "1244",
       "Hit Type": "",
       "Active On": "5",
       "Active For": "19",
       "Recovery": "34",
       "Overall": "57",
       "Frame Advantage": "-26",
       "Invincibility": "5～18 Dive / 9～18 Sky",
       "Notes": "硬直差は密着から立ち状態のハイドにガードさせた場合のもの"
    },
    "623B": {
       "Input": "→↓↘+B",
       "Damage": "1520",
       "Hit Type": "",
       "Active On": "5",
       "Active For": "18",
       "Recovery": "36",
       "Overall": "58",
       "Frame Advantage": "-33",
       "Invincibility": "1～6 All / 7～11 Strike \n12～22 Dive・Head",
       "Notes": "硬直差は密着から立ち状態のハイドにガードさせた場合のもの"
    },
    "623C": {
       "Input": "→↓↘+C",
       "Damage": "1854",
       "Hit Type": "",
       "Active On": "3",
       "Active For": "21",
       "Recovery": "44",
       "Overall": "86",
       "Frame Advantage": "-39",
       "Invincibility": "1～6 All / 7～18 Strike",
       "Notes": "硬直差は密着から立ち状態のハイドにガードさせた場合のもの"
    },
    "214A": {
       "Input": "↓↙←+A",
       "Damage": "950",
       "Hit Type": "",
       "Active On": "12",
       "Active For": "9",
       "Recovery": "14",
       "Overall": "34",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Notes": "硬直差は密着からガードさせた場合のもの"
    },
    "214A (Inst)": {
       "Input": "↓↙←+A",
       "Damage": "950",
       "Hit Type": "",
       "Active On": "12",
       "Active For": "9",
       "Recovery": "14",
       "Overall": "34",
       "Frame Advantage": "±0",
       "Invincibility": "4～20 Projectile",
       "Notes": "7～11 Guard Point\n硬直差は密着からガードさせた場合のもの\n使用後、盾強化状態終了"
    },
    "214[A]": {
       "Input": "↓↙←+A",
       "Damage": "1410",
       "Hit Type": "",
       "Active On": "22",
       "Active For": "9",
       "Recovery": "19",
       "Overall": "49",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Notes": "硬直差は密着からガードさせた場合のもの"
    },
    "214[A] (Inst)": {
       "Input": "↓↙←+A",
       "Damage": "1410",
       "Hit Type": "",
       "Active On": "22",
       "Active For": "9",
       "Recovery": "19",
       "Overall": "49",
       "Frame Advantage": "+4",
       "Invincibility": "4～30 Projectile",
       "Notes": "7～21 Guard Point\n硬直差は密着からガードさせた場合のもの\n使用後、盾強化状態終了"
    },
    "214B": {
       "Input": "↓↙←+B",
       "Damage": "950",
       "Hit Type": "",
       "Active On": "12",
       "Active For": "12",
       "Recovery": "14",
       "Overall": "37",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Notes": "硬直差は密着からガードさせた場合のもの"
    },
    "214B (Inst)": {
       "Input": "↓↙←+B",
       "Damage": "950",
       "Hit Type": "",
       "Active On": "12",
       "Active For": "12",
       "Recovery": "14",
       "Overall": "37",
       "Frame Advantage": "-3",
       "Invincibility": "4～23 Projectile",
       "Notes": "7～11 Guard Point\n硬直差は密着からガードさせた場合のもの\n使用後、盾強化状態終了"
    },
    "214[B]": {
       "Input": "↓↙←+B",
       "Damage": "1410",
       "Hit Type": "",
       "Active On": "22",
       "Active For": "12",
       "Recovery": "19",
       "Overall": "52",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Notes": "硬直差は密着からガードさせた場合のもの"
    },
    "214[B] (Inst)": {
       "Input": "↓↙←+B",
       "Damage": "1410",
       "Hit Type": "",
       "Active On": "22",
       "Active For": "12",
       "Recovery": "19",
       "Overall": "52",
       "Frame Advantage": "+1",
       "Invincibility": "4～33 Projectile",
       "Notes": "7～21打撃相殺判定あり\n硬直差は密着からガードさせた場合のもの\n使用後、盾強化状態終了"
    },
    "214C": {
       "Input": "↓↙←+C",
       "Damage": "1708",
       "Hit Type": "",
       "Active On": "8",
       "Active For": "20",
       "Recovery": "20",
       "Overall": "47",
       "Frame Advantage": "-6",
       "Invincibility": "1～3 Throw / 3～27 Projectile",
       "Notes": "硬直差は密着からガードさせた場合のもの"
    },
    "22A": {
       "Input": "↓↓+A",
       "Damage": "0",
       "Hit Type": "",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "37",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Notes": "使用後、剣強化"
    },
    "22A (Vorpal)": {
       "Input": "↓↓+A",
       "Damage": "0",
       "Hit Type": "",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "34",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Notes": "使用後、剣強化"
    },
    "22B": {
       "Input": "↓↓+B",
       "Damage": "0",
       "Hit Type": "",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "39",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Notes": "使用後、盾強化"
    },
    "22B (Vorpal)": {
       "Input": "↓↓+B",
       "Damage": "0",
       "Hit Type": "",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "36",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Notes": "使用後、盾強化"
    },
    "22C": {
       "Input": "↓↓+C",
       "Damage": "1304",
       "Hit Type": "",
       "Active On": "7",
       "Active For": "6",
       "Recovery": "26",
       "Overall": "38",
       "Frame Advantage": "+9",
       "Invincibility": "1～3 Throw",
       "Notes": "使用後、剣･盾強化"
    },
    "22C (Both Inst)": {
       "Input": "↓↓+C",
       "Damage": "1550",
       "Hit Type": "",
       "Active On": "7",
       "Active For": "6",
       "Recovery": "26",
       "Overall": "38",
       "Frame Advantage": "+9",
       "Invincibility": "1～3 Throw",
       "Notes": "ヒット後、時間経過で追加ダメージ発生（最大852）\n使用後、剣・盾共に強化状態終了"
    },
    "j.236A": {
       "Input": "↓↘→+A",
       "Damage": "1420",
       "Hit Type": "Dive",
       "Active On": "12",
       "Active For": "Until Landing+2",
       "Recovery": "36",
       "Overall": "-",
       "Frame Advantage": "-4",
       "Invincibility": "",
       "Notes": "硬直差は密着でジャンプの昇りから最速で出してガードさせた場合のもの"
    },
    "j.236A (Inst)": {
       "Input": "(Air)↓↘→+A",
       "Damage": "1440",
       "Hit Type": "Dive",
       "Active On": "12",
       "Active For": "Until Landing+2",
       "Recovery": "36",
       "Overall": "-",
       "Frame Advantage": "-4",
       "Invincibility": "",
       "Notes": "硬直差は密着でジャンプの昇りから最速で出してガードさせた場合のもの"
    },
    "j.236[A]": {
       "Input": "(Air)↓↘→+A",
       "Damage": "1546",
       "Hit Type": "Dive",
       "Active On": "25",
       "Active For": "Until Landing+2",
       "Recovery": "40",
       "Overall": "-",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Notes": "硬直差は密着でジャンプの昇りから最速で出してガードさせた場合のもの"
    },
    "j.236[A] (Inst)": {
       "Input": "(Air)↓↘→+A",
       "Damage": "1566",
       "Hit Type": "Dive",
       "Active On": "25",
       "Active For": "Until Landing+2",
       "Recovery": "40",
       "Overall": "-",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Notes": "硬直差は密着でジャンプの昇りから最速で出してガードさせた場合のもの"
    },
    "j.236B": {
       "Input": "(Air)↓↘→+B",
       "Damage": "1420",
       "Hit Type": "Dive",
       "Active On": "12",
       "Active For": "Until Landing+2",
       "Recovery": "38",
       "Overall": "-",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Notes": "硬直差は密着でジャンプの昇りから最速で出してガードさせた場合のもの"
    },
    "j.236B (Inst)": {
       "Input": "(Air)↓↘→+B",
       "Damage": "1440",
       "Hit Type": "Dive",
       "Active On": "12",
       "Active For": "Until Landing+2",
       "Recovery": "38",
       "Overall": "-",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Notes": "硬直差は密着でジャンプの昇りから最速で出してガードさせた場合のもの"
    },
    "j.236[B]": {
       "Input": "(Air)↓↘→+B",
       "Damage": "1546",
       "Hit Type": "Dive",
       "Active On": "25",
       "Active For": "Until Landing+2",
       "Recovery": "43",
       "Overall": "-",
       "Frame Advantage": "-11",
       "Invincibility": "",
       "Notes": "硬直差は密着でジャンプの昇りから最速で出してガードさせた場合のもの"
    },
    "j.236[B] (Inst)": {
       "Input": "(Air)↓↘→+B",
       "Damage": "1566",
       "Hit Type": "Dive",
       "Active On": "25",
       "Active For": "Until Landing+2",
       "Recovery": "43",
       "Overall": "-",
       "Frame Advantage": "-11",
       "Invincibility": "",
       "Notes": "硬直差は密着でジャンプの昇りから最速で出してガードさせた場合のもの"
    },
    "j.236C": {
       "Input": "(Air)↓↘→+C",
       "Damage": "1676",
       "Hit Type": "Dive",
       "Active On": "8",
       "Active For": "Until Landing+2",
       "Recovery": "37",
       "Overall": "-",
       "Frame Advantage": "±0",
       "Invincibility": "",
       "Notes": "硬直差は密着でジャンプの昇りから最速で出してガードさせた場合のもの"
    },
    "j.236XX": {
       "Input": "AorBorC",
       "Damage": "576",
       "Hit Type": "",
       "Active On": "7",
       "Active For": "9",
       "Recovery": "9 Upon Landing",
       "Overall": "54",
       "Frame Advantage": "-18",
       "Invincibility": "",
       "Notes": ""
    },
    "j.236XX (Inst)": {
       "Input": "AorBorC",
       "Damage": "727",
       "Hit Type": "",
       "Active On": "7",
       "Active For": "15",
       "Recovery": "9 Upon Landing",
       "Overall": "54",
       "Frame Advantage": "-14",
       "Invincibility": "",
       "Notes": "使用後、剣強化状態終了"
    },
    "IW": {
       "Input": "←↙↓↘→+D",
       "Damage": "3241",
       "Hit Type": "",
       "Active On": "10",
       "Active For": "19",
       "Recovery": "57",
       "Overall": "85",
       "Frame Advantage": "-46",
       "Invincibility": "1～31All / 32～43 Strike",
       "Notes": ""
    },
    "IWEXS": {
       "Input": "A+B+C+D",
       "Damage": "3760",
       "Hit Type": "",
       "Active On": "15",
       "Active For": "6",
       "Recovery": "47",
       "Overall": "67",
       "Frame Advantage": "-25",
       "Invincibility": "1～26 All",
       "Notes": ""
    }
 }