module.exports = {
    "5A": {
       "Input": "",
       "Damage": "210",
       "Hit Type": "Mid",
       "Active On": "8",
       "Active For": "3",
       "Recovery": "19",
       "Overall": "29",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "5B": {
       "Input": "",
       "Damage": "610",
       "Hit Type": "Mid",
       "Active On": "13",
       "Active For": "3",
       "Recovery": "21",
       "Overall": "36",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "5C": {
       "Input": "",
       "Damage": "720",
       "Hit Type": "Mid",
       "Active On": "15",
       "Active For": "2",
       "Recovery": "22",
       "Overall": "38",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "13～16 kills projectiles"
    },
    "2A": {
       "Input": "",
       "Damage": "210",
       "Hit Type": "Mid",
       "Active On": "8",
       "Active For": "2",
       "Recovery": "18",
       "Overall": "27",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "2B": {
       "Input": "",
       "Damage": "520",
       "Hit Type": "Low",
       "Active On": "11",
       "Active For": "4",
       "Recovery": "17",
       "Overall": "31",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Attribute": "Foot",
       "Notes": ""
    },
    "2C": {
       "Input": "",
       "Damage": "710",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "5",
       "Recovery": "27",
       "Overall": "43",
       "Frame Advantage": "-14",
       "Invincibility": "10～13 head",
       "Attribute": "",
       "Notes": "10～16 kills projectiles"
    },
    "j.A": {
       "Input": "",
       "Damage": "210",
       "Hit Type": "Overhead",
       "Active On": "9",
       "Active For": "3",
       "Recovery": "16",
       "Overall": "27",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.B": {
       "Input": "",
       "Damage": "410",
       "Hit Type": "Overhead",
       "Active On": "10",
       "Active For": "6",
       "Recovery": "13",
       "Overall": "28",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.C": {
       "Input": "",
       "Damage": "610",
       "Hit Type": "Overhead",
       "Active On": "15",
       "Active For": "3",
       "Recovery": "14",
       "Overall": "31",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.[C]": {
       "Input": "",
       "Damage": "810",
       "Hit Type": "Overhead",
       "Active On": "26",
       "Active For": "3",
       "Recovery": "15",
       "Overall": "43",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use\n25～28 kills projectiles"
    },
    "66B": {
       "Input": "",
       "Damage": "810",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "2",
       "Recovery": "23",
       "Overall": "34",
       "Frame Advantage": "-13",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "66C": {
       "Input": "",
       "Damage": "1110",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "10(2)7",
       "Recovery": "9",
       "Overall": "36",
       "Frame Advantage": "+7",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "Frame Advantage is against a standing hyde\nHit 2 is -10"
    },
    "1A": {
       "Input": "",
       "Damage": "456",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "2",
       "Recovery": "14",
       "Overall": "24",
       "Frame Advantage": "+2",
       "Invincibility": "",
       "Attribute": "Foot",
       "Notes": ""
    },
    "4B": {
       "Input": "",
       "Damage": "1210",
       "Hit Type": "Mis",
       "Active On": "22",
       "Active For": "13",
       "Recovery": "8",
       "Overall": "42",
       "Frame Advantage": "+2",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "6C": {
       "Input": "",
       "Damage": "1400(1700)",
       "Hit Type": "Mid/Overhead",
       "Active On": "11",
       "Active For": "5(31)8",
       "Recovery": "13",
       "Overall": "67",
       "Frame Advantage": "+5",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "Damage in () is for second hit."
    },
    "3C": {
       "Input": "",
       "Damage": "1500",
       "Hit Type": "Throw",
       "Active On": "10",
       "Active For": "2",
       "Recovery": "27",
       "Overall": "38",
       "Frame Advantage": "",
       "Invincibility": "8～11 head",
       "Attribute": "",
       "Notes": ""
    },
    "j.6C": {
       "Input": "",
       "Damage": "710",
       "Hit Type": "Overhead",
       "Active On": "10",
       "Active For": "4",
       "Recovery": "11",
       "Overall": "24",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.2C": {
       "Input": "",
       "Damage": "510",
       "Hit Type": "Mid",
       "Active On": "7",
       "Active For": "Until landing",
       "Recovery": "23 After Landing",
       "Overall": "44",
       "Frame Advantage": "-20",
       "Invincibility": "",
       "Attribute": "Head",
       "Notes": "Frame advantage is frame perfectly after a jump against a standing hyde"
    },
    "FF": {
       "Input": "B+C",
       "Damage": "1426(810)",
       "Hit Type": "Mid (Air Blockable) / Mid (Air Blockable)",
       "Active On": "13",
       "Active For": "3(15) Rock active until landing",
       "Recovery": "31",
       "Overall": "66",
       "Frame Advantage": "-36",
       "Invincibility": "",
       "Attribute": "Projectile※",
       "Notes": "7～15 kills bullets\n34～35弾属性相殺判定あり（頭上のみ）\nDamage in () is only projectile\n※Rock is projectile\n硬直差は岩空振り時"
    },
    "[FF]": {
       "Input": "B+C",
       "Damage": "1563(980)",
       "Hit Type": "Mid (Air Blockable) / Mid (Air Blockable)",
       "Active On": "11",
       "Active For": "3(15) Rock active until landing",
       "Recovery": "29",
       "Overall": "59",
       "Frame Advantage": "-31",
       "Invincibility": "",
       "Attribute": "Projectile※",
       "Notes": "6～13弾属性相殺判定あり\n29～30弾属性相殺判定あり（頭上のみ）\n()内のダメージは岩のみヒットした場合のもの\n※岩は弾属性\n硬直差は岩空振り時"
    },
    "Throw": {
       "Input": "A+D",
       "Damage": "1770",
       "Hit Type": "Throw",
       "Active On": "4",
       "Active For": "1",
       "Recovery": "22",
       "Overall": "26",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Throw",
       "Notes": "Invincible during entire throwing animation."
    },
    "236A": {
       "Input": "↓↘→+A",
       "Damage": "1520",
       "Hit Type": "Mid",
       "Active On": "17",
       "Active For": "3",
       "Recovery": "29",
       "Overall": "48",
       "Frame Advantage": "-20",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "236B": {
       "Input": "↓↘→+B",
       "Damage": "1520",
       "Hit Type": "Overhead",
       "Active On": "26",
       "Active For": "3",
       "Recovery": "25",
       "Overall": "53",
       "Frame Advantage": "-16",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "236C": {
       "Input": "↓↘→+C",
       "Damage": "1750",
       "Hit Type": "Mid",
       "Active On": "18",
       "Active For": "3",
       "Recovery": "21",
       "Overall": "41",
       "Frame Advantage": "-6",
       "Invincibility": "1～3 throw",
       "Attribute": "",
       "Notes": ""
    },
    "623A": {
       "Input": "→↓↘+A",
       "Damage": "1180",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "3(9)4(10)5",
       "Recovery": "13",
       "Overall": "52",
       "Frame Advantage": "-6",
       "Invincibility": "7～11 Dive / 9～11 head",
       "Attribute": "",
       "Notes": ""
    },
    "623B": {
       "Input": "→↓↘+B",
       "Damage": "1180",
       "Hit Type": "Mid",
       "Active On": "8",
       "Active For": "3(9)4(10)5",
       "Recovery": "17",
       "Overall": "55",
       "Frame Advantage": "-10",
       "Invincibility": "6～10 Dive / 8～10 head",
       "Attribute": "",
       "Notes": ""
    },
    "623C": {
       "Input": "→↓↘+C",
       "Damage": "2049",
       "Hit Type": "Mid",
       "Active On": "17",
       "Active For": "2(12)2(11)2(8)4",
       "Recovery": "22",
       "Overall": "79",
       "Frame Advantage": "-8",
       "Invincibility": "1～16 all / 17～18 throw",
       "Attribute": "",
       "Notes": ""
    },
    "360A": {
       "Input": "１回転+A",
       "Damage": "1910",
       "Hit Type": "Throw",
       "Active On": "3",
       "Active For": "1",
       "Recovery": "29",
       "Overall": "32",
       "Frame Advantage": "",
       "Invincibility": "1～3 throw",
       "Attribute": "Throw",
       "Notes": "Invincible during entire throwing animation."
    },
    "360B": {
       "Input": "１回転+B",
       "Damage": "1910",
       "Hit Type": "Throw",
       "Active On": "6",
       "Active For": "2",
       "Recovery": "36",
       "Overall": "43",
       "Frame Advantage": "",
       "Invincibility": "1～7 throw",
       "Attribute": "Throw",
       "Notes": "Invincible during entire throwing animation.・Goldthrows"
    },
    "360C": {
       "Input": "１回転+C",
       "Damage": "2332",
       "Hit Type": "Throw",
       "Active On": "9",
       "Active For": "2",
       "Recovery": "29",
       "Overall": "39",
       "Frame Advantage": "",
       "Invincibility": "1～10 all",
       "Attribute": "Throw",
       "Notes": "Invincible during entire throwing animation."
    },
    "2*360A": {
       "Input": "２回転+A",
       "Damage": "2010",
       "Hit Type": "Throw",
       "Active On": "3",
       "Active For": "1",
       "Recovery": "29",
       "Overall": "32",
       "Frame Advantage": "",
       "Invincibility": "1～3 throw",
       "Attribute": "Throw",
       "Notes": "Invincible during entire throwing animation."
    },
    "2*360B": {
       "Input": "２回転+B",
       "Damage": "2010",
       "Hit Type": "Throw",
       "Active On": "6",
       "Active For": "2",
       "Recovery": "36",
       "Overall": "43",
       "Frame Advantage": "",
       "Invincibility": "1～7 throw",
       "Attribute": "Throw",
       "Notes": "Invincible during entire throwing animation.・Goldthrows"
    },
    "2*360C": {
       "Input": "２回転+C",
       "Damage": "2410",
       "Hit Type": "Throw",
       "Active On": "9",
       "Active For": "2",
       "Recovery": "29",
       "Overall": "39",
       "Frame Advantage": "",
       "Invincibility": "1～10 all",
       "Attribute": "Throw",
       "Notes": "Invincible during entire throwing animation."
    },
    "214A": {
       "Input": "↓↙←+A",
       "Damage": "1220",
       "Hit Type": "Mid",
       "Active On": "16",
       "Active For": "5",
       "Recovery": "12",
       "Overall": "32",
       "Frame Advantage": "+1",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "15～20 kills projectiles"
    },
    "214B": {
       "Input": "↓↙←+B",
       "Damage": "1410",
       "Hit Type": "Mid",
       "Active On": "22",
       "Active For": "4",
       "Recovery": "10",
       "Overall": "35",
       "Frame Advantage": "+4",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "20～25 kills projectiles"
    },
    "214[B]": {
       "Input": "↓↙←+B",
       "Damage": "1620",
       "Hit Type": "Mid",
       "Active On": "29",
       "Active For": "4",
       "Recovery": "10",
       "Overall": "42",
       "Frame Advantage": "+7",
       "Invincibility": "",
       "Attribute": "",
       "Notes": "27～32 kills projectiles"
    },
    "214C": {
       "Input": "↓↙←+C",
       "Damage": "2150",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "7",
       "Active For": "6",
       "Recovery": "13",
       "Overall": "25",
       "Frame Advantage": "-1",
       "Invincibility": "1～3 throw",
       "Attribute": "",
       "Notes": "5～12 kills projectiles"
    },
    "j.214A": {
       "Input": "空中↓↙←+A",
       "Damage": "1410",
       "Hit Type": "Throw",
       "Active On": "7",
       "Active For": "4",
       "Recovery": "9 upon landing",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Throw",
       "Notes": ""
    },
    "j.214B": {
       "Input": "空中↓↙←+B",
       "Damage": "1410",
       "Hit Type": "Throw",
       "Active On": "7",
       "Active For": "4",
       "Recovery": "9 upon landing",
       "Overall": "24",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Throw",
       "Notes": ""
    },
    "j.214C": {
       "Input": "空中↓↙←+C",
       "Damage": "1825",
       "Hit Type": "Throw",
       "Active On": "5",
       "Active For": "4",
       "Recovery": "9 upon landing",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "Throw",
       "Notes": ""
    },
    "[4]6A": {
       "Input": "←タメ→+A",
       "Damage": "1840",
       "Hit Type": "Throw",
       "Active On": "27",
       "Active For": "Until hits wall",
       "Recovery": "45",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "[4]6B": {
       "Input": "←タメ→+B",
       "Damage": "1840",
       "Hit Type": "Throw",
       "Active On": "30",
       "Active For": "Until hits wall",
       "Recovery": "46",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Attribute": "",
       "Notes": ""
    },
    "[4]6C": {
       "Input": "←タメ→+C",
       "Damage": "2250",
       "Hit Type": "Throw",
       "Active On": "13",
       "Active For": "Until hits wall",
       "Recovery": "46",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "1～hits corner・throw / 6 ~hits corner・projectile",
       "Attribute": "",
       "Notes": ""
    },
    "IW": {
       "Input": "←↙↓↘→+D",
       "Damage": "3115",
       "Hit Type": "Throw",
       "Active On": "13",
       "Active For": "2",
       "Recovery": "36",
       "Overall": "50",
       "Frame Advantage": "-",
       "Invincibility": "1～14 all / 15～31 throw",
       "Attribute": "Throw",
       "Notes": ""
    },
    "IWEXS": {
       "Input": "A+B+C+D",
       "Damage": "3788",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "6",
       "Recovery": "47",
       "Overall": "67",
       "Frame Advantage": "-25",
       "Invincibility": "1～26 all",
       "Attribute": "",
       "Notes": ""
    }
 }