export default {
    "5A": {
       "Input": "",
       "Damage": "180",
       "Hit Type": "Low",
       "Active On": "5",
       "Active For": "2",
       "Recovery": "12",
       "Overall": "18",
       "Frame Advantage": "-2",
       "Invincibility": "",
       "Atttribute": "Foot",
       "Notes": ""
    },
    "5B": {
       "Input": "",
       "Damage": "525",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "3",
       "Recovery": "22",
       "Overall": "34",
       "Frame Advantage": "-6",
       "Invincibility": "",
       "Atttribute": "",
       "Notes": ""
    },
    "5C": {
       "Input": "",
       "Damage": "680",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "4",
       "Recovery": "24",
       "Overall": "39",
       "Frame Advantage": "-10",
       "Invincibility": "10～15 Head",
       "Atttribute": "",
       "Notes": ""
    },
    "2A": {
       "Input": "",
       "Damage": "140",
       "Hit Type": "Mid",
       "Active On": "5",
       "Active For": "3",
       "Recovery": "12",
       "Overall": "19",
       "Frame Advantage": "-3",
       "Invincibility": "",
       "Atttribute": "",
       "Notes": ""
    },
    "2B": {
       "Input": "",
       "Damage": "450",
       "Hit Type": "Low",
       "Active On": "9",
       "Active For": "6",
       "Recovery": "11",
       "Overall": "25",
       "Frame Advantage": "±0",
       "Invincibility": "",
       "Atttribute": "Foot",
       "Notes": ""
    },
    "2C": {
       "Input": "",
       "Damage": "673",
       "Hit Type": "Low",
       "Active On": "12",
       "Active For": "10",
       "Recovery": "25",
       "Overall": "46",
       "Frame Advantage": "-9",
       "Invincibility": "",
       "Atttribute": "Foot (First hit only)",
       "Notes": ""
    },
    "j.A": {
       "Input": "",
       "Damage": "140",
       "Hit Type": "Overhead",
       "Active On": "8",
       "Active For": "Until Landing",
       "Recovery": "83",
       "Overall": "-",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Atttribute": "Head",
       "Notes": ""
    },
    "j.B": {
       "Input": "",
       "Damage": "398",
       "Hit Type": "Overhead",
       "Active On": "9",
       "Active For": "3",
       "Recovery": "20",
       "Overall": "31",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Atttribute": "Head",
       "Notes": "Behaviour in air allowed after use"
    },
    "j.C": {
       "Input": "",
       "Damage": "498",
       "Hit Type": "Overhead",
       "Active On": "12",
       "Active For": "4",
       "Recovery": "35",
       "Overall": "50",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Atttribute": "Head",
       "Notes": ""
    },
    "66B": {
       "Input": "",
       "Damage": "720",
       "Hit Type": "Mid",
       "Active On": "9",
       "Active For": "2",
       "Recovery": "23",
       "Overall": "33",
       "Frame Advantage": "-5",
       "Invincibility": "",
       "Atttribute": "",
       "Notes": ""
    },
    "66C": {
       "Input": "",
       "Damage": "760",
       "Hit Type": "Mid",
       "Active On": "10",
       "Active For": "3(3)3",
       "Recovery": "41",
       "Overall": "59",
       "Frame Advantage": "-26",
       "Invincibility": "10～18 Foot",
       "Atttribute": "",
       "Notes": ""
    },
    "6A": {
       "Input": "→+A",
       "Damage": "580",
       "Hit Type": "Mid",
       "Active On": "16\n【6】",
       "Active For": "2",
       "Recovery": "24",
       "Overall": "41\n【31】",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-3\n【】内の値は威気静心之構使用中のもの (TRANSLATOR NOTE: i think this says \"everything in brackets is ONLY during stance"
    },
    "6B": {
       "Input": "→+B",
       "Damage": "580",
       "Hit Type": "Mid",
       "Active On": "16\n【6】",
       "Active For": "2",
       "Recovery": "24",
       "Overall": "41\n【31】",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-3\n【】内の値は威気静心之構使用中のもの"
    },
    "6C": {
       "Input": "→+C",
       "Damage": "580",
       "Hit Type": "Low",
       "Active On": "16\n【6】",
       "Active For": "2",
       "Recovery": "24",
       "Overall": "41\n【31】",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Atttribute": "Projectile",
       "Notes": "跡切でキャンセルすると硬直-3\n【】内の値は威気静心之構使用中のもの"
    },
    "j.6A": {
       "Input": "空中→+A",
       "Damage": "580",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15\n【5】",
       "Active For": "3",
       "Recovery": "着地11",
       "Overall": "33",
       "Frame Advantage": "-15",
       "Invincibility": "",
       "Atttribute": "Head",
       "Notes": "跡切でキャンセルすると硬直(落下開始まで)-1\n【】内の値は威気静心之構使用中のもの\n硬直差はジャンプの昇りから最速で出してガードさせた場合のもの"
    },
    "j.6B": {
       "Input": "空中→+B",
       "Damage": "580",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15\n【5】",
       "Active For": "3",
       "Recovery": "着地11",
       "Overall": "33",
       "Frame Advantage": "-15",
       "Invincibility": "",
       "Atttribute": "Head",
       "Notes": "跡切でキャンセルすると硬直(落下開始まで)-1\n【】内の値は威気静心之構使用中のもの\n硬直差はジャンプの昇りから最速で出してガードさせた場合のもの"
    },
    "j.6C": {
       "Input": "空中→+C",
       "Damage": "580",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15\n【5】",
       "Active For": "3",
       "Recovery": "着地11",
       "Overall": "33",
       "Frame Advantage": "-15",
       "Invincibility": "",
       "Atttribute": "Head",
       "Notes": "跡切でキャンセルすると硬直(落下開始まで)-1\n【】内の値は威気静心之構使用中のもの\n硬直差はジャンプの昇りから最速で出してガードさせた場合のもの"
    },
    "4B": {
       "Input": "",
       "Damage": "720\n(1050)",
       "Hit Type": "Mid",
       "Active On": "17",
       "Active For": "3",
       "Recovery": "24",
       "Overall": "43",
       "Frame Advantage": "-9",
       "Invincibility": "7～14 Head",
       "Atttribute": "",
       "Notes": "Parries on 7～14\nDamage in () is upon counter"
    },
    "4C": {
       "Input": "",
       "Damage": "1040",
       "Hit Type": "Mid",
       "Active On": "12",
       "Active For": "15",
       "Recovery": "20",
       "Overall": "46",
       "Frame Advantage": "-7",
       "Invincibility": "",
       "Atttribute": "",
       "Notes": ""
    },
    "j.2C": {
       "Input": "",
       "Damage": "420",
       "Hit Type": "Overhead",
       "Active On": "13",
       "Active For": "5",
       "Recovery": "15",
       "Overall": "32",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Atttribute": "Head",
       "Notes": "Can be cancelled into other air normals"
    },
    "j.2[C]": {
       "Input": "",
       "Damage": "710",
       "Hit Type": "Overhead",
       "Active On": "23",
       "Active For": "5",
       "Recovery": "21",
       "Overall": "48",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Atttribute": "Head",
       "Notes": "Can be cancelled into other air normals"
    },
    "FF": {
       "Input": "B+C",
       "Damage": "850",
       "Hit Type": "Mid",
       "Active On": "34\n【27】",
       "Active For": "2",
       "Recovery": "42",
       "Overall": "77\n【70】",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-1\n【】内の値は威気静心之構使用中のもの"
    },
    "[FF]": {
       "Input": "B+C",
       "Damage": "1220",
       "Hit Type": "Unblockable",
       "Active On": "84\n【77】",
       "Active For": "1",
       "Recovery": "54",
       "Overall": "138\n【131】",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-1\n【】内の値は威気静心之構使用中のもの"
    },
    "FF (Vorpal)": {
       "Input": "B+C",
       "Damage": "850",
       "Hit Type": "Mid",
       "Active On": "24\n【20】",
       "Active For": "2",
       "Recovery": "42",
       "Overall": "67\n【63】",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-1\n【】内の値は威気静心之構使用中のもの"
    },
    "[FF] (Vorpal)": {
       "Input": "B+C",
       "Damage": "1220",
       "Hit Type": "Unblockable",
       "Active On": "74\n【70】",
       "Active For": "1",
       "Recovery": "54",
       "Overall": "128\n【124】",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-1\n【】内の値は威気静心之構使用中のもの"
    },
    "j.FF": {
       "Input": "空中B+C",
       "Damage": "850",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "18\n【12】",
       "Active For": "5",
       "Recovery": "23\n(着地11)",
       "Overall": "45\n【39】",
       "Frame Advantage": "-42",
       "Invincibility": "",
       "Atttribute": "Head",
       "Notes": "跡切でキャンセルすると硬直-1\n【】内の値は威気静心之構使用中のもの"
    },
    "j.[FF]": {
       "Input": "空中B+C",
       "Damage": "890",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "18\n【12】",
       "Active For": "5",
       "Recovery": "23\n(着地11)",
       "Overall": "45\n【39】",
       "Frame Advantage": "-42",
       "Invincibility": "",
       "Atttribute": "Head",
       "Notes": "跡切でキャンセルすると硬直-1\n【】内の値は威気静心之構使用中のもの"
    },
    "Throw": {
       "Input": "A+D",
       "Damage": "1070",
       "Hit Type": "Throw",
       "Active On": "4",
       "Active For": "1",
       "Recovery": "22",
       "Overall": "26",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Atttribute": "Throw",
       "Notes": "Can be comboed from. Invincible during entire throwing animation."
    },
    "236A": {
       "Input": "↓↘→+A",
       "Damage": "950",
       "Hit Type": "Mid",
       "Active On": "17\n【9】",
       "Active For": "2",
       "Recovery": "36",
       "Overall": "54\n【46】",
       "Frame Advantage": "-8",
       "Invincibility": "13～18 Dive / 17～18 Head",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-1\n【】内の値は威気静心之構使用中のもの"
    },
    "236B": {
       "Input": "↓↘→+B",
       "Damage": "950",
       "Hit Type": "Mid",
       "Active On": "17\n【9】",
       "Active For": "2",
       "Recovery": "36",
       "Overall": "54\n【46】",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-1\n【】内の値は威気静心之構使用中のもの"
    },
    "236C": {
       "Input": "↓↘→+C",
       "Damage": "1754",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "14\n【7】",
       "Active For": "5",
       "Recovery": "38",
       "Overall": "56\n【49】",
       "Frame Advantage": "-16",
       "Invincibility": "1～3 Throw",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-1\n【】内の値は威気静心之構使用中のもの"
    },
    "j.236A": {
       "Input": "空中↓↘→+A",
       "Damage": "950",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "22\n【10】",
       "Active For": "5",
       "Recovery": "23\n(着地11)",
       "Overall": "49\n【37】",
       "Frame Advantage": "-12",
       "Invincibility": "",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-1\n【】内の値は威気静心之構使用中のもの\n硬直差はジャンプの昇りから最速で出してガードさせた場合のもの"
    },
    "j.236B": {
       "Input": "空中↓↘→+B",
       "Damage": "950",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "22\n【10】",
       "Active For": "5",
       "Recovery": "23\n(着地11)",
       "Overall": "49\n【37】",
       "Frame Advantage": "-7",
       "Invincibility": "",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-1\n【】内の値は威気静心之構使用中のもの\nFrame advantage is from frame perfect TK"
    },
    "j.236C": {
       "Input": "空中↓↘→+C",
       "Damage": "1642",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "19\n【10】",
       "Active For": "5",
       "Recovery": "23\n(着地11)",
       "Overall": "56\n【47】",
       "Frame Advantage": "-8",
       "Invincibility": "",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-1\n【】内の値は威気静心之構使用中のもの\nFrame advantage is from frame perfect TK"
    },
    "214A": {
       "Input": "↓↙←+A",
       "Damage": "1157",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "20\n【12】",
       "Active For": "5(4)16",
       "Recovery": "26",
       "Overall": "70\n【62】",
       "Frame Advantage": "-11",
       "Invincibility": "16～24 Foot",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると着地硬直-3\n【】内の値は威気静心之構使用中のもの"
    },
    "214B": {
       "Input": "↓↙←+B",
       "Damage": "1157",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "21\n【13】",
       "Active For": "5(4)16",
       "Recovery": "21",
       "Overall": "66\n【58】",
       "Frame Advantage": "-6",
       "Invincibility": "17～25 Foot",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると着地硬直-3\n【】内の値は威気静心之構使用中のもの"
    },
    "214C": {
       "Input": "↓↙←+C",
       "Damage": "2007",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15\n【10】",
       "Active For": "3(4)19",
       "Recovery": "30",
       "Overall": "70\n【65】",
       "Frame Advantage": "-6",
       "Invincibility": "1～17 All",
       "Atttribute": "",
       "Notes": "【】内の値は威気静心之構使用中のもの"
    },
    "j.214A": {
       "Input": "空中↓↙←+A",
       "Damage": "1157",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "22\n【12】",
       "Active For": "5(4)16",
       "Recovery": "着地23",
       "Overall": "56",
       "Frame Advantage": "±0",
       "Invincibility": "18～26 Foot",
       "Atttribute": "Dive (First hit only)",
       "Notes": "跡切でキャンセルすると着地硬直-3\n【】内の値は威気静心之構使用中のもの\nFrame advantage is from frame perfect TK"
    },
    "j.214B": {
       "Input": "空中↓↙←+B",
       "Damage": "1157",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "23\n【13】",
       "Active For": "5(4)16",
       "Recovery": "着地23",
       "Overall": "57",
       "Frame Advantage": "±0",
       "Invincibility": "19～27 Foot",
       "Atttribute": "Dive (First hit only)",
       "Notes": "跡切でキャンセルすると着地硬直-3\n【】内の値は威気静心之構使用中のもの\nFrame advantage is from frame perfect TK"
    },
    "j.214C": {
       "Input": "空中↓↙←+C",
       "Damage": "2007",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "13\n【11】",
       "Active For": "3(4)19",
       "Recovery": "着地33",
       "Overall": "74",
       "Frame Advantage": "±0",
       "Invincibility": "1～15 All",
       "Atttribute": "",
       "Notes": "【】内の値は威気静心之構使用中のもの\nFrame advantage is from frame perfect TK"
    },
    "421A": {
       "Input": "←↓↙+A",
       "Damage": "0",
       "Hit Type": "",
       "Active On": "0",
       "Active For": "",
       "Recovery": "0",
       "Overall": "50\n【39】",
       "Frame Advantage": "-",
       "Invincibility": "16～24 Strike\n【5～13 Strike】",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-1\n【】内の値は威気静心之構使用中のもの"
    },
    "421B": {
       "Input": "←↓↙+B",
       "Damage": "0",
       "Hit Type": "",
       "Active On": "0",
       "Active For": "",
       "Recovery": "0",
       "Overall": "50\n【39】",
       "Frame Advantage": "-",
       "Invincibility": "15～20 Strike\n【4～9 Strike】",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-1\n【】内の値は威気静心之構使用中のもの"
    },
    "421C": {
       "Input": "←↓↙+C",
       "Damage": "0",
       "Hit Type": "",
       "Active On": "0",
       "Active For": "",
       "Recovery": "着地11",
       "Overall": "59\n【48】",
       "Frame Advantage": "-",
       "Invincibility": "15～19 Strike / 20 All\n【4～8 Strike / 9 All】",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-1\n【】内の値は威気静心之構使用中のもの"
    },
    "j.421A": {
       "Input": "空中←↓↙+A",
       "Damage": "0",
       "Hit Type": "",
       "Active On": "0",
       "Active For": "",
       "Recovery": "着地11",
       "Overall": "44\n【35】",
       "Frame Advantage": "-",
       "Invincibility": "12～19 All\n【3～10 All】",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-1\n【】内の値は威気静心之構使用中のもの"
    },
    "j.421B": {
       "Input": "空中←↓↙+B",
       "Damage": "0",
       "Hit Type": "",
       "Active On": "0",
       "Active For": "",
       "Recovery": "着地11",
       "Overall": "44\n【35】",
       "Frame Advantage": "-",
       "Invincibility": "12～19 Strike\n【3～10 All】",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-1\n【】内の値は威気静心之構使用中のもの"
    },
    "j.421C": {
       "Input": "空中←↓↙+C",
       "Damage": "0",
       "Hit Type": "",
       "Active On": "0",
       "Active For": "",
       "Recovery": "着地31",
       "Overall": "49\n【40】",
       "Frame Advantage": "-",
       "Invincibility": "14～18 All / 19 Strike\n【5～9 All / 10 Strike】",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-1\n【】内の値は威気静心之構使用中のもの"
    },
    "(Stance) 4/6": {
       "Input": "←or→",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "45",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Atttribute": "",
       "Notes": "動作終了2F後にアイコン再点灯\nホールド解除すると動作を途中で終了し、8Fでニュートラルへ移行"
    },
    "(Stance) 44/66": {
       "Input": "←←or→→",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "35",
       "Frame Advantage": "-",
       "Invincibility": "9～19 Strike",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-1"
    },
    "(Stance) j.66": {
       "Input": "空中→→",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "39",
       "Frame Advantage": "-",
       "Invincibility": "6～18 All",
       "Atttribute": "",
       "Notes": "相手の裏に回った場合は全体38\n跡切でキャンセルすると硬直-1\nCan act in air after using"
    },
    "(Stance) j.44": {
       "Input": "空中←←",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "38",
       "Frame Advantage": "-",
       "Invincibility": "6～17 All",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-1\n動作後は空中で行動可"
    },
    "(Stance) 7/8/9": {
       "Input": "↖or↑or↗",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "23",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-1\n動作後は空中で行動可\n3F jumpsquat"
    },
    "(Stance) j.7/8/9": {
       "Input": "空中↖or↑or↗",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "20",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-1\n動作後は空中で行動可"
    },
    "(Stance) 22": {
       "Input": "↓↓",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "41",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-1\n1～17 acts as a parry without a hitbox"
    },
    "(Stance) j.22": {
       "Input": "空中↓↓",
       "Damage": "0",
       "Hit Type": "-",
       "Active On": "-",
       "Active For": "-",
       "Recovery": "-",
       "Overall": "35",
       "Frame Advantage": "-",
       "Invincibility": "",
       "Atttribute": "",
       "Notes": "跡切でキャンセルすると硬直-1\n1～15 acts as a parry without a hitbox"
    },
    "IW": {
       "Input": "←↙↓↘→+D",
       "Damage": "3033",
       "Hit Type": "Mid (Air Blockable) / Mid (Air Blockable)",
       "Active On": "13",
       "Active For": "3(20)3(31)6",
       "Recovery": "72",
       "Overall": "147",
       "Frame Advantage": "-30",
       "Invincibility": "1～31 All / 32～60 Strike\n61～92 All / 93～99 Strike",
       "Atttribute": "",
       "Notes": ""
    },
    "IWEXS": {
       "Input": "A+B+C+D",
       "Damage": "3770",
       "Hit Type": "Mid (Air Blockable)",
       "Active On": "15",
       "Active For": "6",
       "Recovery": "47",
       "Overall": "67",
       "Frame Advantage": "-25",
       "Invincibility": "1～26 All",
       "Atttribute": "",
       "Notes": ""
    }
 }